// questions.js
window.TEST_QUESTIONS = {
  int: [
    {
      q: "Which vein forms a porto-caval anastomosis with the esophageal veins?",
      a: [
        "Proper hepatic vein",
        "Common hepatic vein",
        "Right gastric vein",
        "Splenic vein",
        "Left gastric vein",
      ],
      correct: 4,
    },
    {
      q: "Identify the type of arthritis that occurs due to an increase in uric acid in the blood.",
      a: [
        "Osteoarthritis",
        "Gout",
        "Rheumatoid arthritis",
        "Seronegative arthritis",
        "Septic arthritis",
      ],
      correct: 1,
    },
    {
      q: "From which spinal cord segments does the phrenic nerve originate?",
      a: ["C1-C2", "C3-C5", "C5-C7", "C7-C8", "T1-T2"],
      correct: 1,
    },
    {
      q: "Which cells produce myelin in the central nervous system?",
      a: [
        "Microglia",
        "Oligodendrocytes",
        "Schwann cells",
        "Astrocytes",
        "Ependymal cells",
      ],
      correct: 1,
    },
    {
      q: "Identify the correct sequence of the connective tissue layers covering muscle, muscle fascicles, and muscle fibers.",
      a: [
        "Epimysium, Perimysium, Endomysium",
        "Perimysium, Epimysium, Endomysium",
        "Endomysium, Perimysium, Epimysium",
        "Epimysium, Endomysium, Perimysium",
        "Perimysium, Endomysium, Epimysium",
      ],
      correct: 0,
    },
    {
      q: "Which fibers carry sensory impulses for smell and taste to central nervous system?",
      a: [
        "Special visceral afferent fibers",
        "Special visceral efferent fibers",
        "General somatic afferent fibers",
        "General somatic efferent fibers",
        "General visceral afferent fibers",
      ],
      correct: 0,
    },
    {
      q: "In which vertebra is the promontory located?",
      a: ["C1", "C7", "L5", "S3", "S1"],
      correct: 4,
    },
    {
      q: "Where are the precursors of B and T lymphocytes produced?",
      a: ["Thymus", "Spleen", "Liver", "Lymph nodes", "Bone marrow"],
      correct: 4,
    },
    {
      q: "Before birth, through which structure of the heart does blood pass from the right atrium to the left atrium?",
      a: [
        "Foramina venarum minimarum cordis",
        "Foramen rotundum",
        "Conus arteriosus",
        "Mitral valve",
        "Foramen ovale",
      ],
      correct: 4,
    },
    {
      q: "A 27-year-old woman was brought to the maternity complex. After giving birth, it was observed that the newborn had abdominal organs protruding from the right side of the umbilicus, covered by peritoneum. What is the correct diagnosis?",
      a: [
        "Gastroschisis",
        "Omphalocele",
        "Congenital inguinal hernia",
        "Mesothelioma",
        "Congenital umbilical hernia",
      ],
      correct: 1,
    },
    {
      q: "What is the term for an abnormally increased lumbar curvature?",
      a: ["Osteomalacia", "Osteoporosis", "Lordosis", "Rickets", "Spondylosis"],
      correct: 2,
    },
    {
      q: "In a herniated disc, which structure protrudes through the annulus fibrosus?",
      a: [
        "Nucleus pulposus",
        "Pia mater",
        "Dura mater",
        "Periosteum",
        "Sensory nerve",
      ],
      correct: 0,
    },
    {
      q: "What is the term for the group of muscles innervated by a motor nerve emerging from a specific spinal segment?",
      a: ["Dermatome", "Myotome", "Sclerotome", "Collateral", "Somite"],
      correct: 1,
    },
    {
      q: "From where do the blood vessels supplying the heart with arterial blood originate?",
      a: [
        "Aorta",
        "Superior vena cava",
        "Internal carotid artery",
        "Left subclavian artery",
        "External carotid artery",
      ],
      correct: 0,
    },
    {
      q: "Mesothelioma is caused by exposure to which substance?",
      a: ["Asbestos", "Copper", "Coal", "Beryllium", "Zinc"],
      correct: 0,
    },
    {
      q: "Which structure normally functions as the pacemaker of the heart?",
      a: [
        "Sinoatrial node",
        "Atrioventricular node",
        "Bundle of His",
        "Purkinje fibers",
        "Chordae tendineae",
      ],
      correct: 0,
    },
    {
      q: "Which nerve can be transected to help treat a gastric ulcer?",
      a: [
        "Vagus nerve",
        "Glossopharyngeal nerve",
        "Hypoglossal nerve",
        "Trigeminal nerve",
        "Phrenic nerve",
      ],
      correct: 0,
    },
    {
      q: "What is an effect of the sympathetic nervous system activation?",
      a: [
        "Pupil constriction",
        "Increased saliva secretion",
        "Blood vessel dilation",
        "Contraction of the detrusor muscle",
        "Increased glycogen breakdown",
      ],
      correct: 4,
    },
    {
      q: "After birth, what does the left umbilical vein become?",
      a: [
        "Ligamentum teres hepatis",
        "Median umbilical ligament",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Inguinal ligament",
      ],
      correct: 0,
    },
    {
      q: "What is the causative agent of Pott’s disease?",
      a: [
        "Mycobacterium tuberculosis",
        "Herpes zoster",
        "Herpes simplex 1",
        "Pseudomonas aeruginosa",
        "Staphylococcus aureus",
      ],
      correct: 0,
    },
    {
      q: "A 24-year-old woman comes to the office for evaluation of a skin lesion. Biopsy shows condensed DNA bodies at the nuclear periphery. This region is most likely associated with which of the following genetic findings?",
      a: [
        "Extensive double-strand DNA break repair",
        "Histone acetylation",
        "Impaired mismatch repair",
        "Low transcription activity",
        "Reduced positive supercoiling",
      ],
      correct: 3,
    },
    {
      q: "In eukaryotic interphase, which protein is found outside the nucleosome core and promotes chromatin compaction?",
      a: [
        "Histone H1",
        "Histone H3",
        "Histone H4",
        "Small nuclear ribonucleoprotein",
        "Type II topoisomerase",
      ],
      correct: 0,
    },
    {
      q: "Which of the followings is a stop codon during protein synthesis?",
      a: ["UAA", "GGA", "CGC", "AUG", "AUU"],
      correct: 0,
    },
    {
      q: "In what stage of mitosis are maximally condensed chromosomes aligned at the equatorial plate?",
      a: [
        "Late prophase",
        "Early prophase",
        "Metaphase",
        "Anaphase",
        "Telophase",
      ],
      correct: 2,
    },
    {
      q: "In what stage of meiosis does crossing over occur?",
      a: [
        "prophase 1",
        "prophase 2",
        "metaphase 1",
        "Anaphase 2",
        "metaphase 2",
      ],
      correct: 0,
    },
    {
      q: "What is the net ion movement facilitated by the Na⁺-K⁺ pump with hydrolysis of a single ATP?",
      a: [
        "2 Na⁺ out, 3 K⁺ in",
        "3 Na⁺ out, 2 K⁺ in",
        "3 Na⁺ out, 3 K⁺ in",
        "2 Na⁺ out, 2 K⁺ in",
        "1 Na⁺ out, 2 K⁺ in",
      ],
      correct: 1,
    },
    {
      q: "Which type of G protein activates adenylate cyclase, leading to cAMP formation?",
      a: ["Gs", "Gi", "Gq", "G12/13", "Gt"],
      correct: 0,
    },
    {
      q: "Which cellular organelle is responsible for ATP synthesis via oxidative phosphorylation?",
      a: [
        "Endoplasmic reticulum",
        "Mitochondria",
        "Golgi apparatus",
        "Lysosomes",
        "Ribosomes",
      ],
      correct: 1,
    },
    {
      q: "Which cell organelle contains enzymes for breakdown of cellular waste?",
      a: [
        "Nucleus",
        "Lysosome",
        "Endoplasmic reticulum",
        "Peroxisome",
        "Ribosome",
      ],
      correct: 1,
    },
    {
      q: "A 3-month-old infant has empty peroxisomes lacking enzymes. Name the genetic disease.",
      a: [
        "Zellweger syndrome",
        "Parkinson disease",
        "Plasmalogen deficiency",
        "Alzheimer disease",
        "Daun syndrome",
      ],
      correct: 0,
    },
    {
      q: "What are the pyrimidine bases found in DNA nucleotides?",
      a: [
        "Adenine and guanine",
        "Cytosine and thymine",
        "Thymine and guanine",
        "Uracil and cytosine",
        "Adenine and uracil",
      ],
      correct: 1,
    },
    {
      q: "Which autoimmune disease produces antibodies against hemidesmosomes with chronic generalized skin blisters?",
      a: [
        "bullous pemphigoid",
        "Graves disease",
        "Knobloch syndrome",
        "Leigh disease",
        "Alzheimer disease",
      ],
      correct: 0,
    },
    {
      q: "Which type of cells are associated with capillaries, sharing basement membranes and pluripotential?",
      a: [
        "pericytes",
        "adipocytes",
        "osteoblasts",
        "endothelial cells",
        "chondroblasts",
      ],
      correct: 0,
    },
    {
      q: "Which type of cells arise from myeloid stem cells and resemble basophils?",
      a: ["mast cells", "myocyte", "adipocytes", "osteoblasts", "neuroglia"],
      correct: 0,
    },
    {
      q: "Which cells arise from B lymphocytes and produce antibodies?",
      a: ["Plasma cells", "T cells", "Eosinophils", "Basophils", "Macrophages"],
      correct: 0,
    },
    {
      q: "Hay fever develops as a result of excessive release of which substance?",
      a: [
        "Histamine",
        "Epinephrine",
        "Norepinephrine",
        "Serotonin",
        "Dopamine",
      ],
      correct: 0,
    },
    {
      q: "Failure of the developmental anterior neuropore to close results in?",
      a: [
        "Anencephaly",
        "Spina bifida",
        "Hirschsprung disease",
        "Astrocytoma",
        "Meningomyelocele",
      ],
      correct: 0,
    },
    {
      q: "Which of the following diseases is caused by demyelination?",
      a: [
        "Multiple sclerosis",
        "Huntington disease",
        "Parkinson disease",
        "Alzheimer disease",
        "Spina bifida",
      ],
      correct: 0,
    },
    {
      q: "Loss of neurons producing which neurotransmitter causes Parkinson disease?",
      a: ["dopamine", "GABA", "Norepinephrine", "Serotonin", "Substance P"],
      correct: 0,
    },
    {
      q: "A patient with Hirschsprung disease is most likely to present with which symptoms?",
      a: [
        "Large, dilated colon",
        "Absent cranial vault",
        "Exposed spinal cord",
        "Pulmonary hypoplasia",
        "Absent small intestine",
      ],
      correct: 0,
    },
  ],
  block1: [
    {
      q: "Which nitrogenous base is found only in RNA?",
      a: ["Uracil", "Thymine", "Cytosine", "Guanine", "Adenine"],
      correct: 0,
    },
    {
      q: "MELAS is a disease associated with which organelle?",
      a: ["Mitochondria", "Golgi apparatus", "Ribosome", "Lysosome", "Vacuole"],
      correct: 0,
    },
    {
      q: "Which metal is necessary for collagen synthesis?",
      a: ["Lead", "Iron", "Copper", "Potassium", "Calcium"],
      correct: 2,
    },
    {
      q: "Which mutation causes premature termination of protein synthesis?",
      a: ["Deletion", "Frameshift", "Silent", "Nonsense", "Missense"],
      correct: 3,
    },
    {
      q: "Angelman syndrome is caused by a mutation on which chromosome?",
      a: ["15", "21", "22", "23", "14"],
      correct: 0,
    },
    {
      q: "Heteroplasmy occurs in which type of inheritance?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 0,
    },
    {
      q: "Macroorchidism is a characteristic of which disorder?",
      a: [
        "Huntington",
        "Prader-Willi",
        "Parkinson",
        "Myotonic dystrophy",
        "Fragile X",
      ],
      correct: 4,
    },
    {
      q: "Which lipoprotein carries excess cholesterol to the liver?",
      a: ["LDL", "VLDL", "HDL", "IDL", "Chylomicron"],
      correct: 2,
    },
    {
      q: "Fluid endocytosis is called?",
      a: [
        "Simple diffusion",
        "Facilitated diffusion",
        "Phagocytosis",
        "Pinocytosis",
        "Secondary active transport",
      ],
      correct: 3,
    },
    {
      q: "Which organelle degrades misfolded proteins?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Proteasome",
        "Peroxisome",
      ],
      correct: 3,
    },
    {
      q: "Osteogenesis imperfecta is caused by a defect in which type of collagen?",
      a: ["Type I", "Type II", "Type III", "Type IV", "Type V"],
      correct: 0,
    },
    {
      q: "Lysyl oxidase ensures which process in collagen synthesis?",
      a: [
        "Hydroxylation",
        "Glycosylation",
        "Oxidation",
        "Cross-linking",
        "Methylation",
      ],
      correct: 3,
    },
    {
      q: "Which feature is characteristic for the lagging strand during DNA replication?",
      a: [
        "Elongation 3' to 5'",
        "Removal of RNA primers",
        "Synthesis of short RNA chains",
        "Reverse transcriptase activity",
        "Synthesis of multiple RNA primers",
      ],
      correct: 4,
    },
    {
      q: "Which enzyme unwinds hydrogen bonds between DNA strands?",
      a: [
        "Helicase",
        "Primase",
        "DNA polymerase",
        "Topoisomerase I",
        "Topoisomerase II",
      ],
      correct: 0,
    },
    {
      q: "Which part of heterogeneous RNA contains information for protein synthesis?",
      a: ["Exon", "Intron", "Promoter", "Inducer", "Silencer"],
      correct: 0,
    },
    {
      q: "During which stage of meiosis does crossing over occur?",
      a: [
        "Telophase I",
        "Anaphase II",
        "Metaphase I",
        "Prophase I",
        "Metaphase II",
      ],
      correct: 3,
    },
    {
      q: "At the end of meiosis I, how many chromosomes and chromatids does each cell have?",
      a: [
        "46 chromosomes, 46 chromatids",
        "46 chromosomes, 23 chromatids",
        "23 chromosomes, 46 chromatids",
        "23 chromosomes, 23 chromatids",
        "46 chromosomes, 92 chromatids",
      ],
      correct: 2,
    },
    {
      q: "Which RNA 3'-end contains diguanine modifications in tRNA?",
      a: ["AUG", "CCA", "Methylguanosine triphosphate", "Poly-A", "TATA"],
      correct: 1,
    },
    {
      q: "Condensed DNA bodies at the nuclear periphery are most likely associated with?",
      a: [
        "Extensive double-strand DNA break repair",
        "Histone acetylation",
        "Impaired mismatch repair",
        "Low transcription activity",
        "Reduced positive supercoiling",
      ],
      correct: 3,
    },
    {
      q: "A single missense mutation in cystathionine beta-synthase causing multiple tissue effects is an example of?",
      a: [
        "Dominant negative mutation",
        "Genetic linkage",
        "Incomplete penetrance",
        "Locus heterogeneity",
        "Pleiotropy",
      ],
      correct: 4,
    },
    {
      q: "Which peritoneal ligament is part of the lesser omentum?",
      a: [
        "Hepatogastric",
        "Gastrosplenic",
        "Gastrorenal",
        "Gastrococolic",
        "Gastrofrenic",
      ],
      correct: 0,
    },
    {
      q: "The inferior vena cava passes through which diaphragm opening?",
      a: ["T12", "L1", "T10", "L3", "T8"],
      correct: 4,
    },
    {
      q: "Sympathetic nervous system causes which effect?",
      a: [
        "Pupil dilation",
        "Increased saliva secretion",
        "Vasodilation",
        "Bronchoconstriction",
        "Increased intestinal peristalsis",
      ],
      correct: 0,
    },
    {
      q: "Accumulation of lymph fluid in pleural cavity is called?",
      a: ["Empyema", "Chylothorax", "Hydrothorax", "Hemothorax", "Pyothorax"],
      correct: 1,
    },
    {
      q: "Which midline structure lies between the rectus abdominis muscles?",
      a: [
        "Linea alba",
        "Median umbilical ligament",
        "Lateral umbilical ligament",
        "Falciform ligament",
        "Ligamentum teres",
      ],
      correct: 0,
    },
    {
      q: "Where is cerebrospinal fluid located?",
      a: [
        "Subarachnoid space",
        "Epidural space",
        "Subdural space",
        "Beneath cerebral cortex",
        "Under pia mater",
      ],
      correct: 0,
    },
    {
      q: "The odontoid process is characteristic of which vertebra?",
      a: ["C2", "C1", "C7", "L5", "S1"],
      correct: 0,
    },
    {
      q: "Which vertebral levels are used for lumbar puncture to obtain cerebrospinal fluid?",
      a: ["L4-L5", "S1-S2", "T12-L1", "L1-L2", "C1-C2"],
      correct: 0,
    },
    {
      q: "Before birth, which heart structure allows blood to pass from the right to left atrium?",
      a: [
        "Foramen ovale",
        "Foramina venarum minimarum cordis",
        "Foramen rotundum",
        "Conus arteriosus",
        "Mitral valve",
      ],
      correct: 0,
    },
    {
      q: "Obliterated umbilical artery forms which structure?",
      a: [
        "Median umbilical ligament",
        "Ovarian ligament",
        "Medial umbilical ligament",
        "Inguinal ligament",
        "Lateral umbilical ligament",
      ],
      correct: 2,
    },
    {
      q: "Spina bifida during pregnancy results from deficiency of which vitamin?",
      a: ["Folic acid", "Vitamin B6", "Vitamin B1", "Vitamin B12", "Vitamin A"],
      correct: 0,
    },
    {
      q: "Abnormal increased thoracic spine curvature is called?",
      a: ["Osteomalacia", "Osteoporosis", "Kyphosis", "Rickets", "Spondylosis"],
      correct: 2,
    },
    {
      q: "Which skin area is innervated by a sensory nerve from a specific spinal segment?",
      a: ["Dermatome", "Myotome", "Sclerotome", "Collateral", "Somite"],
      correct: 0,
    },
    {
      q: "Ptosis, miosis, and anhidrosis are features of which syndrome?",
      a: [
        "Horner syndrome",
        "Parkinson disease",
        "Huntington disease",
        "Friedreich ataxia",
        "Marfan syndrome",
      ],
      correct: 0,
    },
    {
      q: "Collapse of alveoli in the lungs is called?",
      a: [
        "Atelectasis",
        "Emphysema",
        "Chronic bronchitis",
        "Pulmonary artery embolism",
        "Pulmonary hypertension",
      ],
      correct: 0,
    },
    {
      q: "Which nerve can be cut to help treat a gastric ulcer?",
      a: [
        "Vagus nerve",
        "Glossopharyngeal nerve",
        "Hypoglossal nerve",
        "Trigeminal nerve",
        "Phrenic nerve",
      ],
      correct: 0,
    },
    {
      q: "Which rib pairs are considered floating ribs?",
      a: ["11-12", "1-7", "8-10", "1-5", "5-12"],
      correct: 0,
    },
    {
      q: "Which nerve carries sensory impulses from internal organs to CNS?",
      a: [
        "General somatic afferent fibers",
        "Special somatic efferent fibers",
        "Special visceral afferent fibers",
        "Special visceral efferent fibers",
        "General visceral afferent fibers",
      ],
      correct: 4,
    },
    {
      q: "Which organ has the ability to synthesize vitamin D?",
      a: ["Skin", "Lungs", "Bone", "Spleen", "Heart"],
      correct: 0,
    },
    {
      q: "Where does fertilization (egg fertilization) usually occur?",
      a: ["Uterine tube", "Uterus", "Ovary", "Vagina", "Abdominal cavity"],
      correct: 0,
    },
  ],
  block2: [
    {
      q: "Which type of transport occurs without energy expenditure?",
      a: [
        "Pinocytosis",
        "Phagocytosis",
        "Secondary active transport",
        "Primary active transport",
        "Facilitated diffusion",
      ],
      correct: 4,
    },
    {
      q: "Zellweger syndrome is associated with dysfunction of which organelle?",
      a: [
        "Mitochondria",
        "Golgi apparatus",
        "Ribosome",
        "Lysosome",
        "Peroxisome",
      ],
      correct: 4,
    },
    {
      q: "Which enzyme deficiency causes emphysema?",
      a: [
        "Alpha1-antitrypsin",
        "Lysyl oxidase",
        "5-alpha-reductase",
        "11-beta hydroxylase",
        "21-alpha hydroxylase",
      ],
      correct: 0,
    },
    {
      q: "Which part of tRNA ensures binding to the ribosome?",
      a: ["T loop", "D loop", "Acceptor stem", "Anticodon", "Variable loop"],
      correct: 0,
    },
    {
      q: "One gene affecting multiple traits is called?",
      a: [
        "Codominance",
        "Expressivity",
        "Penetrance",
        "Pleiotropy",
        "Anticipation",
      ],
      correct: 3,
    },
    {
      q: "Marfan syndrome is inherited in which manner?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 3,
    },
    {
      q: "Finding a Barr body in male somatic cells suggests which disorder?",
      a: [
        "Klinefelter syndrome",
        "Huntington disease",
        "Edwards syndrome",
        "Down syndrome",
        "Turner syndrome",
      ],
      correct: 0,
    },
    {
      q: "Which is a purine base?",
      a: ["Guanine", "Cytosine", "Thymine", "Uracil", "Histidine"],
      correct: 0,
    },
    {
      q: "Bortezomib inhibits which organelle?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Proteasome",
        "Mitochondria",
      ],
      correct: 3,
    },
    {
      q: "Programmed cell death is called?",
      a: ["Apoptosis", "Necrosis", "Granulomatosis", "Gangrene", "Ischemia"],
      correct: 0,
    },
    {
      q: "Which disorder is associated with copper transport defect?",
      a: [
        "Marfan syndrome",
        "Menkes disease",
        "Singh disease",
        "Osteogenesis imperfecta",
        "Turner syndrome",
      ],
      correct: 1,
    },
    {
      q: "Vitamin C acts as a cofactor in which collagen synthesis step?",
      a: [
        "Hydroxylation",
        "Glycosylation",
        "Oxidation",
        "Reduction",
        "Methylation",
      ],
      correct: 0,
    },
    {
      q: "Polypeptide chain encounters UGA codon. What happens?",
      a: [
        "Polypeptide synthesis terminates here",
        "Protein synthesis starts at this amino acid",
        "Translation activates",
        "Protein synthesis is 50% complete",
        "Exon initial part",
      ],
      correct: 0,
    },
    {
      q: "Which RNA requires a 5'-cap for maturation?",
      a: ["hnRNA", "tRNA", "mRNA", "rRNA", "pre-rRNA"],
      correct: 0,
    },
    {
      q: "Protein synthesis initiation in humans begins with which amino acid?",
      a: ["Lysine", "Leucine", "Phenylalanine", "Proline", "Methionine"],
      correct: 4,
    },
    {
      q: "During which mitotic phase is the mitotic spindle formed?",
      a: ["Telophase", "Anaphase", "Metaphase", "Prophase", "Cytokinesis"],
      correct: 3,
    },
    {
      q: "Leber hereditary optic neuropathy is inherited in which manner?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 0,
    },
    {
      q: "Which feature is characteristic of the lagging DNA strand in replication?",
      a: [
        "3'→5' exonuclease activity",
        "3'→5' polymerase activity",
        "5'→3' exonuclease activity",
        "RNA primer synthesis before DNA",
        "Synthesis of multiple short DNA fragments",
      ],
      correct: 4,
    },
    {
      q: "Enzyme adding nucleotides containing uracil in bacterial DNA replication?",
      a: [
        "DNA ligase",
        "DNA polymerase I",
        "DNA polymerase III",
        "Gyrase",
        "Primase",
      ],
      correct: 4,
    },
    {
      q: "Which protein promotes chromatin compaction outside nucleosome core?",
      a: [
        "Histone H1",
        "Histone H3",
        "Histone H4",
        "Small nuclear ribonucleoprotein",
        "Type II topoisomerase",
      ],
      correct: 0,
    },
    {
      q: "Left gastric arteries originate from which artery?",
      a: [
        "Proper hepatic artery",
        "Common hepatic artery",
        "Right gastric artery",
        "Splenic artery",
        "Celiac trunk",
      ],
      correct: 4,
    },
    {
      q: "Which cells produce myelin in the CNS?",
      a: [
        "Microglia",
        "Oligodendrocytes",
        "Schwann cells",
        "Astrocytes",
        "Ependymal cells",
      ],
      correct: 1,
    },
    {
      q: "Chronic dilation of bronchi is called?",
      a: [
        "Emphysema",
        "Bronchiectasis",
        "Atelectasis",
        "Pneumothorax",
        "Pyothorax",
      ],
      correct: 1,
    },
    {
      q: "Which effect is due to parasympathetic nervous system?",
      a: [
        "Pupil dilation",
        "Increased saliva secretion",
        "Vasoconstriction",
        "Bronchial dilation",
        "Decreased intestinal motility",
      ],
      correct: 1,
    },
    {
      q: "Peripheral nervous system is composed of?",
      a: [
        "12 cranial, 31 spinal nerves and ganglia",
        "Brain and spinal cord",
        "Sympathetic and parasympathetic nerves",
        "Neurons and neuroglia",
        "Spinal cord and 31 pairs of spinal nerves",
      ],
      correct: 0,
    },
    {
      q: "Lesion of optic nerve fibers causes which vision problem?",
      a: [
        "Special somatic afferent fibers",
        "Special somatic efferent fibers",
        "Special visceral afferent fibers",
        "Special visceral efferent fibers",
        "General visceral afferent fibers",
      ],
      correct: 0,
    },
    {
      q: "Blood vessels supplying the heart arise from?",
      a: [
        "Aorta",
        "Superior vena cava",
        "Internal carotid artery",
        "Left subclavian artery",
        "External carotid artery",
      ],
      correct: 0,
    },
    {
      q: "Phrenic nerve damage during surgery causes which complication?",
      a: [
        "Phrenic nerve",
        "Wrong nerve",
        "Hypoglossal nerve",
        "Trochlear nerve",
        "Trigeminal nerve",
      ],
      correct: 0,
    },
    {
      q: "Newborn with abdominal organs protruding through umbilicus covered by peritoneum diagnosis?",
      a: [
        "Gastroschisis",
        "Omphalocele",
        "Congenital inguinal hernia",
        "Mesothelioma",
        "Congenital umbilical hernia",
      ],
      correct: 1,
    },
    {
      q: "Obliterated umbilical artery forms which structure?",
      a: [
        "Median umbilical ligament",
        "Ovarian ligament",
        "Medial umbilical ligament",
        "Inguinal ligament",
        "Lateral umbilical ligament",
      ],
      correct: 2,
    },
    {
      q: "Which ligament is part of the lesser omentum?",
      a: [
        "Hepatoduodenal ligament",
        "Gastrosplenic ligament",
        "Lienorenal ligament",
        "Gastrofrenic ligament",
        "Gastrococolic ligament",
      ],
      correct: 0,
    },
    {
      q: "Which brain structure herniates in Arnold-Chiari malformation?",
      a: ["Cerebellum", "Pons", "Diencephalon", "Midbrain", "Medulla"],
      correct: 0,
    },
    {
      q: "Inflammation of brain meninges is called?",
      a: [
        "Meningitis",
        "Spondylitis",
        "Spondylosis",
        "Encephalitis",
        "Poliomyelitis",
      ],
      correct: 0,
    },
    {
      q: "Which condition can cause Horner syndrome?",
      a: [
        "Pancoast tumor",
        "Meningitis",
        "Encephalitis",
        "Pneumonia",
        "Pericarditis",
      ],
      correct: 0,
    },
    {
      q: "Ductus arteriosus connects aorta to which structure?",
      a: [
        "Pulmonary artery",
        "Superior vena cava",
        "Subclavian artery",
        "Coronary artery",
        "Pulmonary vein",
      ],
      correct: 0,
    },
    {
      q: "After birth, left umbilical vein becomes which structure?",
      a: [
        "Ligamentum teres hepatis",
        "Median umbilical ligament",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Inguinal ligament",
      ],
      correct: 0,
    },
    {
      q: "Which effect is caused by sympathetic nervous system?",
      a: [
        "Pupil constriction",
        "Increased salivation",
        "Vasodilation",
        "Detrusor contraction",
        "Increased glycogen breakdown",
      ],
      correct: 4,
    },
    {
      q: "Ductus deferens belongs to which system?",
      a: [
        "Reproductive",
        "Excretory",
        "Respiratory",
        "Digestive",
        "Covering system",
      ],
      correct: 0,
    },
    {
      q: "Cerebrospinal fluid flows in which space?",
      a: [
        "Subarachnoid",
        "Subdural",
        "Epidural",
        "Epiarachnoid",
        "Sagittal sinus",
      ],
      correct: 0,
    },
    {
      q: "Causative agent of Pott disease?",
      a: [
        "Mycobacterium tuberculosis",
        "Herpes zoster",
        "Herpes simplex 1",
        "Pseudomonas aeruginosa",
        "Staphylococcus aureus",
      ],
      correct: 0,
    },
  ],
  block3: [
    {
      q: "SGLT2 transporter is an example of which type of transport?",
      a: [
        "Pinocytosis",
        "Phagocytosis",
        "Secondary active transport",
        "Primary active transport",
        "Facilitated diffusion",
      ],
      correct: 2,
    },
    {
      q: "Turner syndrome involves aneuploidy of which chromosome pair?",
      a: ["8", "23", "21", "22", "14"],
      correct: 1,
    },
    {
      q: "Which histone subunit is NOT part of the nucleosome core octamer?",
      a: ["H2A", "H1", "H2B", "H3", "H4"],
      correct: 1,
    },
    {
      q: "Pre-tRNA matures into tRNA through which process?",
      a: [
        "Methylation",
        "Capping",
        "Acetylation",
        "Hydroxylation",
        "Glycosylation",
      ],
      correct: 1,
    },
    {
      q: "Hemophilia A is inherited in which manner?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 1,
    },
    {
      q: "Which disorder is caused by trinucleotide repeat expansion?",
      a: [
        "Huntington",
        "Prader-Willi",
        "Parkinson",
        "Marfan syndrome",
        "Angelman syndrome",
      ],
      correct: 0,
    },
    {
      q: "In Down syndrome, Robertsonian translocation usually occurs between which chromosomes?",
      a: ["11 and 22", "14 and 21", "8 and 21", "13 and 21", "15 and 23"],
      correct: 1,
    },
    {
      q: "Carbon dioxide crosses the cell membrane by which mechanism?",
      a: [
        "Simple diffusion",
        "Facilitated diffusion",
        "Phagocytosis",
        "Primary active transport",
        "Secondary active transport",
      ],
      correct: 0,
    },
    {
      q: "Where does alpha-oxidation of very long chain fatty acids occur?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Peroxisome",
        "Mitochondria",
      ],
      correct: 3,
    },
    {
      q: "When a cell affects a neighboring cell via molecules it secretes, this is called?",
      a: ["Paracrine", "Endocrine", "Autocrine", "Carcinogenic", "Cytostatic"],
      correct: 0,
    },
    {
      q: "Vitamin C is a cofactor for which enzyme in collagen synthesis?",
      a: [
        "Lysyl oxidase",
        "Pyruvate kinase",
        "Prolyl hydroxylase",
        "1-alpha hydroxylase",
        "5-alpha reductase",
      ],
      correct: 2,
    },
    {
      q: "Long limbs and Berry aneurysms are characteristic of which disorder?",
      a: [
        "Marfan syndrome",
        "Menkes disease",
        "Singh disease",
        "Osteogenesis imperfecta",
        "Turner syndrome",
      ],
      correct: 0,
    },
    {
      q: "Which RNA type contains both exons and introns?",
      a: ["hnRNA", "tRNA", "mRNA", "rRNA", "pre-rRNA"],
      correct: 0,
    },
    {
      q: "The acceptor stem of tRNA carries which sequence?",
      a: ["GAA", "AAA", "CCA", "GAG", "CGA"],
      correct: 2,
    },
    {
      q: "The 5' cap of mature tRNA consists of which structure?",
      a: [
        "7-methylguanosine",
        "7-methyladenosine",
        "Methionine",
        "Uridine",
        "1-methylthymidine",
      ],
      correct: 0,
    },
    {
      q: "At the end of meiosis II, each cell contains how many chromosomes and chromatids?",
      a: [
        "46 chromosomes, 46 chromatids",
        "46 chromosomes, 23 chromatids",
        "23 chromosomes, 46 chromatids",
        "23 chromosomes, 23 chromatids",
        "46 chromosomes, 92 chromatids",
      ],
      correct: 3,
    },
    {
      q: "Which disorder is characterized by frequent laughter and a happy demeanor?",
      a: [
        "Huntington",
        "Angelman syndrome",
        "Parkinson",
        "Myotonic dystrophy",
        "Fragile X",
      ],
      correct: 1,
    },
    {
      q: "A nonsense mutation near the 3' end of an mRNA will affect tRNA incorporation of which anticodon for the last amino acid?",
      a: ["5'-AAC-3'", "5'-AUC-3'", "5'-CAA-3'", "5'-GCU-3'", "5'-UCG-3'"],
      correct: 2,
    },
    {
      q: "A condensed, heavily methylated DNA region in a melanocytic nevus indicates?",
      a: [
        "Extensive double-strand break repair",
        "Histone acetylation",
        "Impaired mismatch repair",
        "Low transcription activity",
        "Reduced positive supercoiling",
      ],
      correct: 3,
    },
    {
      q: "Uracil incorporation in replicating bacterial DNA is mediated by which enzyme?",
      a: [
        "DNA ligase",
        "DNA polymerase I",
        "DNA polymerase III",
        "Gyrase",
        "Primase",
      ],
      correct: 4,
    },
    {
      q: "Esophageal veins form porto-caval anastomosis with which vein?",
      a: [
        "Proper hepatic vein",
        "v. hepatica communis",
        "v. gastrica dextra",
        "v. splenica",
        "v. gastrica sinistra",
      ],
      correct: 4,
    },
    {
      q: "Which type of arthritis is caused by excessive uric acid?",
      a: [
        "Osteoarthritis",
        "Gout (Podagra)",
        "Rheumatoid arthritis",
        "Seronegative arthritis",
        "Septic arthritis",
      ],
      correct: 1,
    },
    {
      q: "The phrenic nerve originates from which spinal segments?",
      a: ["C1-C2", "C3-C5", "C5-C7", "C7-C8", "T1-T2"],
      correct: 1,
    },
    {
      q: "Which cells produce myelin in the CNS?",
      a: [
        "Microglia",
        "Oligodendrocytes",
        "Schwann cells",
        "Astrocytes",
        "Ependymal cells",
      ],
      correct: 1,
    },
    {
      q: "Layers covering muscles, fascicles, and fibers in order?",
      a: [
        "Epimysium, Perimysium, Endomysium",
        "Perimysium, Epimysium, Endomysium",
        "Endomysium, Perimysium, Epimysium",
        "Epimysium, Endomysium, Perimysium",
        "Perimysium, Endomysium, Epimysium",
      ],
      correct: 0,
    },
    {
      q: "Which fibers carry taste and visceral sensation impulses?",
      a: [
        "Special visceral afferent fibers",
        "Special visceral efferent fibers",
        "General somatic afferent fibers",
        "General somatic efferent fibers",
        "General visceral afferent fibers",
      ],
      correct: 0,
    },
    {
      q: "The promontory is located on which vertebra?",
      a: ["S1", "C1", "C7", "L5", "S3"],
      correct: 0,
    },
    {
      q: "Precursor cells of B and T lymphocytes are produced in?",
      a: ["Bone marrow", "Thymus", "Spleen", "Liver", "Lymph nodes"],
      correct: 0,
    },
    {
      q: "Before birth, blood passes from right atrium to left atrium through which structure?",
      a: [
        "Foramen ovale",
        "Foramina venarum minimarum cordis",
        "Foramen rotundum",
        "Conus arteriosus",
        "Mitral valve",
      ],
      correct: 0,
    },
    {
      q: "Newborn with abdominal organs protruding through umbilical sac diagnosis?",
      a: [
        "Gastroschisis",
        "Omphalocele",
        "Congenital inguinal hernia",
        "Mesothelioma",
        "Congenital umbilical hernia",
      ],
      correct: 1,
    },
    {
      q: "Abnormal exaggerated lumbar curvature is called?",
      a: ["Osteomalacia", "Osteoporosis", "Lordosis", "Rickets", "Spondylosis"],
      correct: 2,
    },
    {
      q: "In a herniated disc, which structure protrudes through annulus fibrosus?",
      a: [
        "Nucleus pulposus",
        "Pia mater",
        "Dura mater",
        "Periosteum",
        "Sensory nerve",
      ],
      correct: 0,
    },
    {
      q: "Muscle group innervated by a motor nerve from a spinal segment is called?",
      a: ["Dermatom", "Myotome", "Sclerotome", "Collateral", "Somit"],
      correct: 1,
    },
    {
      q: "Which gland secretes thymosin hormone?",
      a: ["Thymus", "Thyroid", "Parathyroid", "Adrenal", "Pituitary"],
      correct: 0,
    },
    {
      q: "Mesothelioma is caused by exposure to which substance?",
      a: ["Asbestos", "Copper", "Coal", "Beryllium", "Zinc"],
      correct: 0,
    },
    {
      q: "Normal cardiac pacemaker is which structure?",
      a: [
        "Sinoatrial node",
        "Atrioventricular node",
        "Bundle of His",
        "Purkinje fibers",
        "Chordae tendineae",
      ],
      correct: 0,
    },
    {
      q: "Cutting which nerve can help treat gastric ulcers?",
      a: [
        "Vagus nerve",
        "Glossopharyngeal nerve",
        "Hypoglossal nerve",
        "Trigeminal nerve",
        "Phrenic nerve",
      ],
      correct: 0,
    },
    {
      q: "Which effect is caused by the sympathetic nervous system?",
      a: [
        "Pupil constriction",
        "Increased salivation",
        "Vasodilation",
        "Detrusor contraction",
        "Increased glycogen breakdown",
      ],
      correct: 4,
    },
    {
      q: "Epididymis belongs to which system?",
      a: ["Reproductive", "Excretory", "Respiratory", "Digestive", "Covering"],
      correct: 0,
    },
    {
      q: "Causative agent of Pott disease?",
      a: [
        "Mycobacterium tuberculosis",
        "Herpes zoster",
        "Herpes simplex 1",
        "Pseudomonas aeruginosa",
        "Staphylococcus aureus",
      ],
      correct: 0,
    },
  ],
  block4: [
    {
      q: "Which organelle is surrounded by a double membrane?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Mitochondria",
        "Lysosome",
        "Vacuole",
      ],
      correct: 2,
    },
    {
      q: "Which phase is NOT part of interphase?",
      a: ["G1", "G2", "S", "Mitosis", "DNA synthesis"],
      correct: 3,
    },
    {
      q: "Bloom syndrome results from deficiency of which enzyme?",
      a: [
        "Primase",
        "DNA polymerase",
        "Topoisomerase 2",
        "Helicase",
        "Topoisomerase 1",
      ],
      correct: 3,
    },
    {
      q: "Which codon is a stop codon?",
      a: ["GAA", "AAA", "UAG", "GAG", "CGA"],
      correct: 2,
    },
    {
      q: "Cystic fibrosis is inherited in which manner?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 4,
    },
    {
      q: "Which triplet repeats are expanded in Friedreich ataxia?",
      a: ["GAA", "AAA", "UAG", "GAG", "CGA"],
      correct: 0,
    },
    {
      q: "Down syndrome increases risk of which condition?",
      a: [
        "Duodenal atresia",
        "Spina bifida",
        "Gastritis",
        "Pancreatitis",
        "Intussusception",
      ],
      correct: 0,
    },
    {
      q: "Oxygen crosses the cell membrane via which mechanism?",
      a: [
        "Simple diffusion",
        "Facilitated diffusion",
        "Phagocytosis",
        "Primary active transport",
        "Secondary active transport",
      ],
      correct: 0,
    },
    {
      q: "Which organelle contains digestive enzymes?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Lysosome",
        "Mitochondria",
      ],
      correct: 3,
    },
    {
      q: "When a cell affects itself via molecules it secretes, this is called?",
      a: ["Paracrine", "Endocrine", "Autocrine", "Carcinogenic", "Cytostatic"],
      correct: 2,
    },
    {
      q: "Blue sclerae are a feature of which disorder?",
      a: [
        "Osteogenesis imperfecta",
        "Marfan syndrome",
        "Singh disease",
        "Prader-Willi syndrome",
        "Friedreich ataxia",
      ],
      correct: 0,
    },
    {
      q: "Which enzyme cofactor is required for collagen crosslinking?",
      a: [
        "Lysyl oxidase",
        "Lysine hydroxylase",
        "Prolyl hydroxylase",
        "1-alpha hydroxylase",
        "5-alpha reductase",
      ],
      correct: 0,
    },
    {
      q: "The presence of UGA in a polypeptide chain indicates?",
      a: [
        "Polypeptide synthesis terminates here",
        "Protein synthesis starts at this amino acid",
        "Translation is activated",
        "50% of protein synthesized",
        "Exon initial sequence",
      ],
      correct: 0,
    },
    {
      q: "Which molecule requires a Poly-A tail to mature?",
      a: ["hnRNA", "tRNA", "mRNA", "rRNA", "pre-rRNA"],
      correct: 0,
    },
    {
      q: "In Huntington disease, which phenomenon explains earlier onset in successive generations?",
      a: [
        "Codominance",
        "Expressivity",
        "Penetrance",
        "Pleiotropy",
        "Anticipation",
      ],
      correct: 4,
    },
    {
      q: "At the end of mitosis, each daughter cell has how many chromosomes and chromatids?",
      a: [
        "46 chromosomes, 46 chromatids",
        "46 chromosomes, 23 chromatids",
        "23 chromosomes, 46 chromatids",
        "23 chromosomes, 23 chromatids",
        "46 chromosomes, 92 chromatids",
      ],
      correct: 0,
    },
    {
      q: "Which disorder is characterized by hyperphagia?",
      a: [
        "Huntington",
        "Prader-Willi",
        "Parkinson",
        "Myotonic dystrophy",
        "Fragile X",
      ],
      correct: 1,
    },
    {
      q: "A 45-year-old alcoholic man with purpura, swollen gums, and muscle pain likely has?",
      a: [
        "Scurvy",
        "Menkes disease",
        "Iron deficiency anemia",
        "Dengue fever",
        "Hemophilia",
      ],
      correct: 0,
    },
    {
      q: "Heavily methylated DNA at the nuclear periphery indicates?",
      a: [
        "Extensive double-strand break repair",
        "Histone acetylation",
        "Impaired mismatch repair",
        "Low transcription activity",
        "Reduced positive supercoiling",
      ],
      correct: 3,
    },
    {
      q: "A missense mutation in cystathionine beta-synthase affects multiple tissues due to?",
      a: [
        "Dominant negative mutation",
        "Genetic linkage",
        "Incomplete penetrance",
        "Locus heterogeneity",
        "Pleiotropy",
      ],
      correct: 4,
    },
    {
      q: "Which effect is caused by the sympathetic nervous system?",
      a: [
        "Pupil constriction",
        "Decreased salivation",
        "Vasodilation",
        "Bronchial constriction",
        "Increased glycogen breakdown",
      ],
      correct: 1,
    },
    {
      q: "Closure of which valves produces the first heart sound?",
      a: [
        "Aortic and pulmonary",
        "Aortic and mitral",
        "Pulmonary and mitral",
        "Aortic and tricuspid",
        "Mitral and tricuspid",
      ],
      correct: 4,
    },
    {
      q: "Accumulation of lymph in the pleural cavity is called?",
      a: ["Empyema", "Chylothorax", "Hydrothorax", "Hemothorax", "Pyothorax"],
      correct: 1,
    },
    {
      q: "Which ligament lies between rectus abdominis muscles?",
      a: [
        "Linea alba",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Falciform ligament",
        "Ligamentum teres",
      ],
      correct: 0,
    },
    {
      q: "Peripheral nervous system consists of?",
      a: [
        "12 cranial pairs, 31 spinal pairs, and ganglia",
        "Brain and spinal cord",
        "Sympathetic and parasympathetic nerves",
        "Neuron and neuroglia",
        "Spinal cord and 31 exiting nerves",
      ],
      correct: 0,
    },
    {
      q: "Damage to which fibers causes vision problems in a patient with optic nerve tumor?",
      a: [
        "Special somatic afferent fibers",
        "Special somatic efferent fibers",
        "Special visceral afferent fibers",
        "Special visceral efferent fibers",
        "General visceral afferent fibers",
      ],
      correct: 0,
    },
    {
      q: "Which vessels supply arterial blood to the heart?",
      a: [
        "Aorta",
        "Superior vena cava",
        "Internal carotid artery",
        "Left subclavian artery",
        "External carotid artery",
      ],
      correct: 0,
    },
    {
      q: "Which is NOT part of the sternum?",
      a: [
        "Linea alba",
        "Manubrium",
        "Corpus",
        "Clavicular notch (Incisura clavicularis)",
        "Sternal angle",
      ],
      correct: 0,
    },
    {
      q: "Phrenic nerve injury during aortocoronary bypass may cause?",
      a: [
        "Phrenic nerve",
        "Accessory nerve",
        "Hypoglossal nerve",
        "Trochlear nerve",
        "Trigeminal nerve",
      ],
      correct: 0,
    },
    {
      q: "Urachus obliteration forms which structure?",
      a: [
        "Median umbilical ligament",
        "Ovarian ligament",
        "Medial umbilical ligament",
        "Inguinal ligament",
        "Lateral umbilical ligament",
      ],
      correct: 0,
    },
    {
      q: "Organ responsible for absorption affected in severe diarrhea in a 7-year-old?",
      a: ["Stomach", "Gallbladder", "Large intestine", "Liver", "Pancreas"],
      correct: 2,
    },
    {
      q: "Spina bifida results from deficiency of which vitamin during pregnancy?",
      a: ["Folic acid", "Vitamin B6", "Vitamin B1", "Vitamin B12", "Vitamin A"],
      correct: 0,
    },
    {
      q: "Abnormal exaggerated thoracic curvature is called?",
      a: ["Osteomalacia", "Osteoporosis", "Kyphosis", "Rickets", "Spondylosis"],
      correct: 2,
    },
    {
      q: "Protrusion of meninges through vertebral defect is called?",
      a: [
        "Meningocele",
        "Meningomyelocele",
        "Spina bifida",
        "Spina bifida occulta",
        "Klippel-Feil syndrome",
      ],
      correct: 0,
    },
    {
      q: "Which condition can cause Horner syndrome?",
      a: [
        "Pancoast tumor",
        "Meningitis",
        "Encephalitis",
        "Pneumonia",
        "Pericarditis",
      ],
      correct: 0,
    },
    {
      q: "Rapid accumulation of fluid or blood in pericardial cavity causing heart compression?",
      a: [
        "Cardiac tamponade",
        "Pericarditis",
        "Peritonitis",
        "Pleuritis",
        "Endocarditis",
      ],
      correct: 0,
    },
    {
      q: "After birth, the left umbilical vein becomes?",
      a: [
        "Ligamentum teres hepatis",
        "Median umbilical ligament",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Inguinal ligament",
      ],
      correct: 0,
    },
    {
      q: "Which effect is caused by the sympathetic nervous system?",
      a: [
        "Pupil constriction",
        "Salivation increase",
        "Vasodilation",
        "Detrusor contraction",
        "Glycogen breakdown increase",
      ],
      correct: 4,
    },
    {
      q: "Fertilization usually occurs in which structure?",
      a: ["Uterine tube", "Uterus", "Ovary", "Vagina", "Peritoneal cavity"],
      correct: 0,
    },
    {
      q: "Ductus deferens belongs to which system?",
      a: ["Reproductive", "Excretory", "Respiratory", "Digestive", "Covering"],
      correct: 0,
    },
  ],
  block5: [
    {
      q: "Which organelle provides donor sites for the endoplasmic reticulum?",
      a: ["Mitochondria", "Golgi apparatus", "Ribosome", "Lysosome", "Vacuole"],
      correct: 2,
    },
    {
      q: "Which vitamin is necessary for collagen synthesis?",
      a: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B6", "Vitamin B1"],
      correct: 2,
    },
    {
      q: "Which enzyme unwinds DNA before the hydrogen bonds are broken?",
      a: [
        "Primase",
        "DNA polymerase",
        "DNA ligase",
        "Helicase",
        "Topoisomerase",
      ],
      correct: 4,
    },
    {
      q: "The acceptor site of tRNA ends with which triplet?",
      a: ["GAA", "AAA", "UAG", "GAG", "CCA"],
      correct: 4,
    },
    {
      q: "In Huntington disease, which process causes earlier onset in successive generations?",
      a: [
        "Codominance",
        "Expressivity",
        "Penetrance",
        "Pleiotropy",
        "Anticipation",
      ],
      correct: 4,
    },
    {
      q: "Duchenne muscular dystrophy is inherited in which manner?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 1,
    },
    {
      q: "Which amino acid is coded by the CAG triplet?",
      a: ["Valine", "Glutamine", "Alanine", "Lysine", "Histidine"],
      correct: 1,
    },
    {
      q: "Which one is a purine base?",
      a: ["Adenine", "Cytosine", "Thymine", "Uracil", "Histidine"],
      correct: 0,
    },
    {
      q: "Where is the electron transport chain located?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Lysosome",
        "Mitochondria",
      ],
      correct: 4,
    },
    {
      q: "Which structure is targeted by drugs that inhibit mitosis?",
      a: [
        "Dynein",
        "Myosin",
        "Actin",
        "Microtubules",
        "Intermediate filaments",
      ],
      correct: 3,
    },
    {
      q: "Osteogenesis imperfecta results from a defect in which protein?",
      a: ["Collagen", "Fibrillin", "Elastin", "Actin", "Myosin"],
      correct: 0,
    },
    {
      q: "Which protein inhibits elastase activity?",
      a: [
        "Trypsin",
        "Pepsin",
        "Alpha-1 antitrypsin",
        "Lysyl oxidase",
        "Lysine hydroxylase",
      ],
      correct: 2,
    },
    {
      q: "Which feature is characteristic of the lagging strand at the replication fork?",
      a: [
        "Elongation 3' → 5'",
        "Removal of RNA primers",
        "Synthesis of a short RNA strand",
        "Reverse transcriptase activity",
        "Synthesis of multiple RNA primers",
      ],
      correct: 4,
    },
    {
      q: "Which codon is a stop codon?",
      a: ["GAA", "AAA", "UAG", "GAG", "CGA"],
      correct: 2,
    },
    {
      q: "Which amino acid is added at the initiation of protein synthesis?",
      a: ["Lysine", "Leucine", "Phenylalanine", "Proline", "Methionine"],
      correct: 4,
    },
    {
      q: "During which mitotic phase do chromatids separate?",
      a: ["Telophase", "Anaphase", "Metaphase", "Prophase", "Cytokinesis"],
      correct: 1,
    },
    {
      q: "At the end of meiosis II, how many chromosomes and chromatids does each cell have?",
      a: [
        "46 chromosomes, 46 chromatids",
        "46 chromosomes, 23 chromatids",
        "23 chromosomes, 46 chromatids",
        "23 chromosomes, 23 chromatids",
        "46 chromosomes, 92 chromatids",
      ],
      correct: 3,
    },
    {
      q: "A 24-year-old woman has a 5 mm brown, oval macule on her anterior thigh. Biopsy shows normal nevus cells. Condensed, heavily methylated DNA is observed at the nuclear periphery. This DNA region is most likely associated with:",
      a: [
        "Enhanced double-strand DNA repair",
        "Histone acetylation",
        "Impaired mismatch repair",
        "Low transcription activity",
        "Reduced positive supercoiling",
      ],
      correct: 3,
    },
    {
      q: "A 34-year-old woman’s bacteria show uracil in partially replicated DNA. Which enzyme most likely mediates this?",
      a: [
        "DNA ligase",
        "DNA polymerase I",
        "DNA polymerase III",
        "Gyrase",
        "Primase",
      ],
      correct: 4,
    },
    {
      q: "Which protein is found outside the nucleosome core and promotes chromatin compaction?",
      a: [
        "Histone H1",
        "Histone H3",
        "Histone H4",
        "Small nuclear RNP",
        "Type II topoisomerase",
      ],
      correct: 0,
    },
    {
      q: "The aortic hiatus of the diaphragm is at which vertebral level?",
      a: ["T12", "L1", "T10", "L3", "T8"],
      correct: 0,
    },
    {
      q: "Excessive bone density due to impaired resorption is called?",
      a: [
        "Osteoporosis",
        "Osteopenia",
        "Osteopetrosis",
        "Osteomalacia",
        "Osteoarthritis",
      ],
      correct: 2,
    },
    {
      q: "Accumulation of lymph in the pleural cavity is called?",
      a: ["Empyema", "Chylothorax", "Hydrothorax", "Hemothorax", "Pyothorax"],
      correct: 1,
    },
    {
      q: "Which fibrous structure lies between the two rectus abdominis muscles?",
      a: [
        "Linea alba",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Falciform ligament",
        "Ligamentum teres",
      ],
      correct: 0,
    },
    {
      q: "The peripheral nervous system consists of?",
      a: [
        "12 cranial pairs, 31 spinal pairs, and ganglia",
        "Brain and spinal cord",
        "Sympathetic and parasympathetic nerves",
        "Neuron and neuroglia",
        "Spinal cord and 31 exiting nerves",
      ],
      correct: 0,
    },
    {
      q: "Which fibers carry taste and visceral sensory impulses?",
      a: [
        "Special visceral afferent fibers",
        "Special visceral efferent fibers",
        "General somatic afferent fibers",
        "General somatic efferent fibers",
        "General visceral afferent fibers",
      ],
      correct: 0,
    },
    {
      q: "The odontoid process is characteristic of which vertebra?",
      a: ["C2", "C1", "C7", "L5", "S1"],
      correct: 0,
    },
    {
      q: "For CSF collection, which vertebral level should the needle be inserted?",
      a: ["L4-L5", "S1-S2", "T12-L1", "L1-L2", "C1-C2"],
      correct: 0,
    },
    {
      q: "Before birth, blood passes from the right atrium to the left atrium via which structure?",
      a: [
        "Foramen ovale",
        "Foramina venarum minimarum cordis",
        "Foramen rotundum",
        "Conus arteriosus",
        "Mitral valve",
      ],
      correct: 0,
    },
    {
      q: "Newborn with abdominal organs protruding into a sac at the umbilicus has which condition?",
      a: [
        "Gastroschisis",
        "Omphalocele",
        "Congenital hernia",
        "Mesothelioma",
        "Umbilical hernia",
      ],
      correct: 1,
    },
    {
      q: "Which mesentery is part of the lesser omentum?",
      a: [
        "Hepatoduodenal ligament",
        "Gastrolienal ligament",
        "Lienorenal ligament",
        "Gastrofrenic ligament",
        "Gastocolic ligament",
      ],
      correct: 0,
    },
    {
      q: "Abnormal lateral curvature of the spine is called?",
      a: [
        "Osteomalacia",
        "Osteoporosis",
        "Scoliosis",
        "Rickets",
        "Spondylosis",
      ],
      correct: 2,
    },
    {
      q: "Degenerative changes in vertebral joints from osteoarthritis are called?",
      a: [
        "Spondylosis",
        "Kyphosis",
        "Spondylolisthesis",
        "Rickets",
        "Lordosis",
      ],
      correct: 0,
    },
    {
      q: "Which region of bone is innervated by a nerve exiting a single spinal segment?",
      a: ["Dermatom", "Myotome", "Sclerotome", "Collateral", "Somite"],
      correct: 2,
    },
    {
      q: "Ptosis, miosis, and anhidrosis are features of which syndrome?",
      a: [
        "Horner syndrome",
        "Parkinson disease",
        "Huntington disease",
        "Friedreich ataxia",
        "Marfan syndrome",
      ],
      correct: 0,
    },
    {
      q: "Collapse of alveoli is called?",
      a: [
        "Atelectasis",
        "Emphysema",
        "Chronic bronchitis",
        "Pulmonary embolism",
        "Pulmonary hypertension",
      ],
      correct: 0,
    },
    {
      q: "Which structure serves as the natural pacemaker of the heart?",
      a: [
        "Sinoatrial node",
        "Atrioventricular node",
        "Bundle of His",
        "Purkinje fibers",
        "Chordae tendineae",
      ],
      correct: 0,
    },
    {
      q: "Which ribs are considered floating ribs?",
      a: ["11–12", "1–7", "8–10", "1–5", "5–12"],
      correct: 0,
    },
    {
      q: "Which effect is caused by the sympathetic nervous system?",
      a: [
        "Pupil constriction",
        "Increased salivation",
        "Vasodilation",
        "Detrusor muscle relaxation",
        "Glycogen synthesis",
      ],
      correct: 3,
    },
    {
      q: "Epididymis belongs to which system?",
      a: ["Reproductive", "Excretory", "Respiratory", "Digestive", "Covering"],
      correct: 0,
    },
  ],
  block6: [
    {
      q: "Which organelle is non-membranous?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Lysosome",
        "Vacuole",
      ],
      correct: 2,
    },
    {
      q: "In which type of mutation does the amino acid sequence of the synthesized protein remain unchanged?",
      a: ["Deletion", "Frameshift", "Silent", "Nonsense", "Missense"],
      correct: 2,
    },
    {
      q: "Which codon is a stop codon?",
      a: ["GAA", "AAA", "UAA", "GAG", "CGA"],
      correct: 2,
    },
    {
      q: "For pre-tRNA to mature into functional tRNA, which process is required?",
      a: [
        "Methylation",
        "Polyadenylation",
        "Acetylation",
        "Hydroxylation",
        "Glycosylation",
      ],
      correct: 1,
    },
    {
      q: "Which disease is associated with genomic imprinting?",
      a: [
        "Huntington",
        "Prader-Willi",
        "Parkinson",
        "Myotonic dystrophy",
        "Fragile X",
      ],
      correct: 1,
    },
    {
      q: "In Huntington disease, which triplet repeats expand?",
      a: ["GAA", "AAA", "UAG", "CAG", "CGA"],
      correct: 3,
    },
    {
      q: "Which part of tRNA is recognized by aminoacyl-tRNA synthetase?",
      a: ["T arm", "D arm", "Acceptor stem", "Anticodon", "Variable loop"],
      correct: 1,
    },
    {
      q: "Which lipoprotein is the main cause of atherosclerosis?",
      a: ["LDL", "VLDL", "HDL", "IDL", "Chylomicron"],
      correct: 0,
    },
    {
      q: "Endocytosis of solid particles is called?",
      a: [
        "Simple diffusion",
        "Facilitated diffusion",
        "Phagocytosis",
        "Pinocytosis",
        "Secondary active transport",
      ],
      correct: 2,
    },
    {
      q: "Which organelle gives shape to the cell?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Cytoskeleton",
        "Mitochondria",
      ],
      correct: 3,
    },
    {
      q: "When a cell influences distant cells via molecules it produces, this is called?",
      a: ["Paracrine", "Endocrine", "Autocrine", "Carcinogenic", "Cytostatic"],
      correct: 1,
    },
    {
      q: "Alpha-1 antitrypsin deficiency causes which disease?",
      a: [
        "Emphysema",
        "Pneumonia",
        "Menkes disease",
        "Osteogenesis imperfecta",
        "Gastritis",
      ],
      correct: 0,
    },
    {
      q: "Which RNA contains both exons and introns?",
      a: ["hnRNA", "tRNA", "mRNA", "rRNA", "pre-rRNA"],
      correct: 0,
    },
    {
      q: "Which enzyme breaks hydrogen bonds between DNA strands?",
      a: [
        "Helicase",
        "Primase",
        "DNA polymerase",
        "Topoisomerase I",
        "Topoisomerase II",
      ],
      correct: 0,
    },
    {
      q: "Which part of heterogeneous RNA does NOT code for protein synthesis?",
      a: ["Exon", "Intron", "Promoter", "Inducer", "Silencer"],
      correct: 1,
    },
    {
      q: "During which mitotic phase do chromosomes align along the cell equator?",
      a: ["Telophase", "Anaphase", "Metaphase", "Prophase", "Cytokinesis"],
      correct: 2,
    },
    {
      q: "At the end of meiosis I, how many chromosomes and chromatids are in each cell?",
      a: [
        "46 chromosomes, 46 chromatids",
        "46 chromosomes, 23 chromatids",
        "23 chromosomes, 46 chromatids",
        "23 chromosomes, 23 chromatids",
        "46 chromosomes, 92 chromatids",
      ],
      correct: 2,
    },
    {
      q: "A 5-year-old boy shows poor growth, sparse, silvery hair, hypotonia, and delayed speech. Most likely diagnosis?",
      a: [
        "Menkes disease",
        "Wilson disease",
        "Osteoporosis",
        "Pellagra",
        "Rickets",
      ],
      correct: 0,
    },
    {
      q: "Bacterial uracil in partially replicated DNA is most likely mediated by which enzyme?",
      a: [
        "DNA ligase",
        "DNA polymerase I",
        "DNA polymerase III",
        "Gyrase",
        "Primase",
      ],
      correct: 4,
    },
    {
      q: "A boy with lens dislocation, intellectual disability, DVT, and a missense mutation in CBS gene demonstrates which genetic phenomenon?",
      a: [
        "Dominant negative mutation",
        "Genetic linkage",
        "Incomplete penetrance",
        "Locus heterogeneity",
        "Pleiotropy",
      ],
      correct: 4,
    },
    {
      q: "Which ligament is NOT part of the greater omentum?",
      a: [
        "Hepatogastric",
        "Gastrosplenic",
        "Gastrorenal",
        "Gastrococolic",
        "Gastrofrenic",
      ],
      correct: 0,
    },
    {
      q: "Epigastric veins form portocaval anastomosis with which vein?",
      a: [
        "Paraumbilical veins",
        "Common hepatic vein",
        "Right gastric vein",
        "Splenic vein",
        "Left gastric vein",
      ],
      correct: 0,
    },
    {
      q: "Which effect is caused by the parasympathetic nervous system?",
      a: [
        "Pupil dilation",
        "Increased salivation",
        "Vasoconstriction",
        "Bronchial dilation",
        "Decreased intestinal peristalsis",
      ],
      correct: 1,
    },
    {
      q: "Accumulation of pus in the pleural cavity is called?",
      a: [
        "Pneumothorax",
        "Chylothorax",
        "Hydrothorax",
        "Hemothorax",
        "Pyothorax",
      ],
      correct: 4,
    },
    {
      q: "Correct order of muscle connective tissue layers covering muscle, fascicle, and fiber?",
      a: [
        "Epimysium, perimysium, endomysium",
        "Perimysium, epimysium, endomysium",
        "Endomysium, perimysium, epimysium",
        "Epimysium, endomysium, perimysium",
        "Perimysium, endomysium, epimysium",
      ],
      correct: 0,
    },
    {
      q: "Where is cerebrospinal fluid located?",
      a: [
        "Subarachnoid space",
        "Epidural space",
        "Subdural space",
        "Below cerebral cortex",
        "Under pia mater",
      ],
      correct: 0,
    },
    {
      q: "A 65-year-old man has MI. Which artery's blood supply is affected?",
      a: ["Coronary", "Dermal", "Intercostal", "Brachial", "Diaphragmatic"],
      correct: 0,
    },
    {
      q: "The promontory is located on which vertebra?",
      a: ["S1", "C1", "C7", "L5", "S3"],
      correct: 0,
    },
    {
      q: "After a coronary artery bypass, hemidiaphragm paralysis occurred. Which nerve was damaged?",
      a: [
        "Phrenic nerve",
        "Recurrent laryngeal nerve",
        "Hypoglossal nerve",
        "Trochlear nerve",
        "Trigeminal nerve",
      ],
      correct: 0,
    },
    {
      q: "Obliterated urachus forms which structure?",
      a: [
        "Median umbilical ligament",
        "Ovarian ligament",
        "Medial umbilical ligament",
        "Inguinal ligament",
        "Lateral umbilical ligament",
      ],
      correct: 0,
    },
    {
      q: "Which ligament is part of the lesser omentum?",
      a: [
        "Hepatoduodenal ligament",
        "Gastrolienal ligament",
        "Lienorenal ligament",
        "Gastrofrenic ligament",
        "Gastrococolic ligament",
      ],
      correct: 0,
    },
    {
      q: "Spina bifida is caused by a deficiency of which vitamin during pregnancy?",
      a: ["Folic acid", "Vitamin B6", "Vitamin B1", "Vitamin B12", "Vitamin A"],
      correct: 0,
    },
    {
      q: "Forward slipping of one vertebra over another is called?",
      a: [
        "Osteomalacia",
        "Spondylitis",
        "Spondylolisthesis",
        "Rickets",
        "Spondylosis",
      ],
      correct: 2,
    },
    {
      q: "Bone region innervated by a single spinal segment is called?",
      a: ["Dermatom", "Myotome", "Sclerotome", "Collateral", "Somite"],
      correct: 2,
    },
    {
      q: "Which can cause Horner syndrome?",
      a: [
        "Pancoast tumor",
        "Meningitis",
        "Encephalitis",
        "Pneumonia",
        "Pericarditis",
      ],
      correct: 0,
    },
    {
      q: "Mesothelioma is caused by exposure to which substance?",
      a: ["Asbestos", "Copper", "Coal", "Beryllium", "Zinc"],
      correct: 0,
    },
    {
      q: "Ductus arteriosus connects the aorta with which structure?",
      a: [
        "Pulmonary artery",
        "Superior vena cava",
        "Subclavian artery",
        "Coronary artery",
        "Pulmonary vein",
      ],
      correct: 0,
    },
    {
      q: "Cutting which nerve can help treat a gastric ulcer?",
      a: [
        "Vagus nerve",
        "Glossopharyngeal nerve",
        "Hypoglossal nerve",
        "Trigeminal nerve",
        "Phrenic nerve",
      ],
      correct: 0,
    },
    {
      q: "Which nerve carries sensory impulses from internal organs to CNS?",
      a: [
        "General somatic afferent fibers",
        "Special somatic efferent fibers",
        "Special visceral afferent fibers",
        "Special visceral efferent fibers",
        "General visceral afferent fibers",
      ],
      correct: 4,
    },
    {
      q: "Which effect is caused by the sympathetic nervous system?",
      a: [
        "Pupil constriction",
        "Increased salivation",
        "Vasodilation",
        "Detrusor muscle relaxation",
        "Glycogen synthesis",
      ],
      correct: 3,
    },
  ],
};
