window.TEST_QUESTIONS = {
  eblock1: [
    {
      q: "Which ion enters the cell through the cell membrane during depolarization of the action potential, making the membrane potential more positive?",
      a: ["Na⁺", "K⁺", "Cl⁻", "Ca²⁺", "Mg²⁺"],
      correct: 0,
    },
    {
      q: "Which structure develops from the bulbus cordis?",
      a: [
        "Ascending aorta",
        "Pulmonary artery",
        "Coronary sinus",
        "Smooth part of the left ventricle",
        "Trabecular part of the left ventricle",
      ],
      correct: 3,
    },
    {
      q: "Which cells play an important role in the regeneration of peripheral nerves?",
      a: [
        "Schwann cells",
        "Oligodendrocytes",
        "Microglial cells",
        "Astrocytes",
        "Endothelial cells",
      ],
      correct: 0,
    },
    {
      q: "Constriction of which organ produces the 'triple bubble' sign on radiography?",
      a: ["Duodenum", "Stomach", "Jejunum", "Liver", "Esophagus"],
      correct: 2,
    },
    {
      q: "Which of the following is NOT a feature of Potter syndrome?",
      a: [
        "Renal agenesis",
        "Low-set ears",
        "Polyhydramnios",
        "Limb deformities",
        "Pulmonary hypoplasia",
      ],
      correct: 2,
    },
    {
      q: "The prostate gland develops from which structure?",
      a: [
        "Genital tubercle",
        "Urogenital fold",
        "Urogenital sinus",
        "Labioscrotal swelling",
        "Genital cleft",
      ],
      correct: 2,
    },
    {
      q: "The inferior parathyroid glands develop from which pharyngeal pouch?",
      a: ["Third", "Second", "First", "Fifth", "Fourth"],
      correct: 0,
    },
    {
      q: "Identify the remnant of the urachus.",
      a: [
        "Median umbilical ligament",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Falciform ligament",
        "Round ligament of the liver",
      ],
      correct: 0,
    },
    {
      q: "The left gastric artery arises from which artery?",
      a: [
        "Proper hepatic artery",
        "Common hepatic artery",
        "Right gastric artery",
        "Splenic artery",
        "Celiac trunk",
      ],
      correct: 4,
    },
    {
      q: "Which cells produce myelin in the central nervous system?",
      a: [
        "Microglia",
        "Oligodendrocytes",
        "Schwann cells",
        "Astrocytes",
        "Ependymal cells",
      ],
      correct: 1,
    },
    {
      q: "What is the term for chronic dilation of the bronchi?",
      a: [
        "Emphysema",
        "Bronchiectasis",
        "Atelectasis",
        "Pneumothorax",
        "Pyothorax",
      ],
      correct: 1,
    },
    {
      q: "Which bacterium is the primary cause of gastric ulcers?",
      a: [
        "Helicobacter pylori",
        "Staphylococcus aureus",
        "Streptococcus pyogenes",
        "Escherichia coli",
        "Salmonella typhi",
      ],
      correct: 0,
    },
    {
      q: "Which nerve provides sensation to the palmar surface of the first three fingers?",
      a: [
        "Ulnar nerve",
        "Radial nerve",
        "Medial antebrachial cutaneous nerve",
        "Median nerve",
        "Lateral antebrachial cutaneous nerve",
      ],
      correct: 3,
    },
    {
      q: "Which nitrogenous base is found only in RNA?",
      a: ["Uracil", "Thymine", "Cytosine", "Guanine", "Adenosine"],
      correct: 0,
    },
    {
      q: "MELAS is associated with dysfunction of which organelle?",
      a: ["Mitochondria", "Golgi apparatus", "Ribosome", "Lysosome", "Vacuole"],
      correct: 0,
    },
    {
      q: "Which metal is required for collagen synthesis?",
      a: ["Lead", "Iron", "Copper", "Potassium", "Calcium"],
      correct: 2,
    },
    {
      q: "Which mutation causes premature termination of protein synthesis?",
      a: ["Deletion", "Frameshift", "Silent", "Nonsense", "Missense"],
      correct: 3,
    },
    {
      q: "Angelman syndrome results from abnormalities involving which chromosome?",
      a: ["15", "21", "22", "23", "14"],
      correct: 0,
    },
    {
      q: "Heteroplasmy is a feature of which pattern of inheritance?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 0,
    },
    {
      q: "Macroorchidism is a characteristic feature of which disorder?",
      a: [
        "Huntington disease",
        "Prader-Willi syndrome",
        "Parkinson disease",
        "Myotonic dystrophy",
        "Fragile X syndrome",
      ],
      correct: 4,
    },
    {
      q: "A 43-year-old woman presents with severe right upper quadrant pain after eating a heavy meal. She has had previous milder episodes, especially after fatty meals. She recently injured her ankle and has been taking ibuprofen daily. BMI is 31 kg/m². Physical examination is limited due to pain. Which of the following substances is the most likely cause of the recurrent right upper quadrant pain in this patient?",
      a: [
        "Cholecystokinin",
        "Lactose",
        "Prostaglandin E₂",
        "Secretin",
        "Serotonin",
      ],
      correct: 0,
    },
    {
      q: "Which enzyme is responsible for synthesizing a complementary DNA strand from a template RNA molecule?",
      a: [
        "DNA polymerase",
        "RNA polymerase",
        "Reverse transcriptase",
        "Ligase",
        "Primase",
      ],
      correct: 2,
    },
    {
      q: "The nucleus pulposus, the central part of the intervertebral disc, develops from which structure?",
      a: [
        "Notochord",
        "Neuroectoderm",
        "Splanchnic mesoderm",
        "Surface ectoderm",
        "Somatic mesoderm",
      ],
      correct: 0,
    },
  ],
  eblock2: [
    {
      q: "Which anomaly occurs when the external opening of the urethra is located on the dorsal surface of the penis instead of the tip of the glans?",
      a: [
        "Epispadias",
        "Cryptorchidism",
        "Potter syndrome",
        "Varicocele",
        "Patent urachus",
      ],
      correct: 0,
    },
    {
      q: "In the maternity complex, a female infant was born with a large swelling in the caudal part. This swelling contains nerve, hair, and bone tissue, and arises from remnants of the primitive streak, which normally degenerates and disappears. What is the diagnosis?",
      a: [
        "Sacrococcygeal teratoma",
        "Amniotic band syndrome",
        "Spina bifida",
        "Omphalocele",
        "Potter syndrome",
      ],
      correct: 0,
    },
    {
      q: "Which type of cells arise from myeloid stem cells in bone marrow and usually reside near small blood vessels. They are similar to basophils but develop from different precursors and thus are not related?",
      a: ["Mast cells", "Myocytes", "Adipocytes", "Osteoblasts", "Neuroglia"],
      correct: 0,
    },
    {
      q: "Which structure develops from the third aortic arch?",
      a: [
        "Subclavian artery",
        "Superior vena cava",
        "Common carotid artery",
        "Truncus arteriosus",
        "Descending aorta",
      ],
      correct: 2,
    },
    {
      q: "Which structure develops from the right horn of the sinus venosus?",
      a: [
        "Ascending aorta",
        "Pulmonary artery",
        "Coronary sinus",
        "Smooth part of the right atrium",
        "Trabecular part of the right ventricle",
      ],
      correct: 3,
    },
    {
      q: "Following severe weight loss, the duodenum may be compressed beneath which structure?",
      a: [
        "Liver",
        "Inferior mesenteric artery",
        "Superior mesenteric artery",
        "Celiac artery",
        "Umbilical artery",
      ],
      correct: 2,
    },
    {
      q: "A horseshoe kidney becomes trapped beneath which artery?",
      a: [
        "Iliac artery",
        "Inferior mesenteric artery",
        "Superior mesenteric artery",
        "Celiac artery",
        "Umbilical artery",
      ],
      correct: 1,
    },
    {
      q: "Which nerve is NOT involved in tongue sensation?",
      a: ["CN XII", "CN VII", "CN X", "CN V", "CN IX"],
      correct: 0,
    },
    {
      q: "Which ligament is part of the lesser omentum?",
      a: [
        "Hepatogastric ligament",
        "Gastrosplenic ligament",
        "Gastrorenal ligament",
        "Gastrocolic ligament",
        "Gastrophrenic ligament",
      ],
      correct: 0,
    },
    {
      q: "At which vertebral level is the inferior vena cava opening of the diaphragm located?",
      a: ["T12", "L1", "T10", "L3", "T8"],
      correct: 4,
    },
    {
      q: "Which is an effect of sympathetic nerve stimulation?",
      a: [
        "Pupillary dilation",
        "Increased salivation",
        "Vasodilation",
        "Bronchoconstriction",
        "Increased intestinal peristalsis",
      ],
      correct: 0,
    },
    {
      q: "What is the accumulation of lymphatic fluid in the pleural cavity called?",
      a: ["Empyema", "Chylothorax", "Hydrothorax", "Hemothorax", "Pyothorax"],
      correct: 1,
    },
    {
      q: "Which ligament lies between the two rectus abdominis muscles?",
      a: [
        "Linea alba",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Falciform ligament",
        "Round ligament of the liver",
      ],
      correct: 0,
    },
    {
      q: "Which nerve innervates the lumbrical muscles of the hand?",
      a: [
        "Ulnar nerve",
        "Radial nerve",
        "Axillary nerve",
        "Suprascapular nerve",
        "Musculocutaneous nerve",
      ],
      correct: 0,
    },
    {
      q: "Which type of transport occurs without energy expenditure?",
      a: [
        "Pinocytosis",
        "Phagocytosis",
        "Secondary active transport",
        "Primary active transport",
        "Facilitated diffusion",
      ],
      correct: 4,
    },
    {
      q: "Zellweger syndrome is associated with dysfunction of which organelle?",
      a: [
        "Mitochondria",
        "Golgi apparatus",
        "Ribosome",
        "Lysosome",
        "Peroxisome",
      ],
      correct: 4,
    },
    {
      q: "Deficiency of which enzyme causes emphysema?",
      a: [
        "Alpha-1 antitrypsin",
        "Lysyl oxidase",
        "5-alpha dehydrogenase",
        "11-beta hydroxylase",
        "21-alpha hydroxylase",
      ],
      correct: 0,
    },
    {
      q: "Which part of tRNA is responsible for binding to the ribosome?",
      a: ["T arm", "D arm", "Acceptor stem", "Anticodon", "Variable loop"],
      correct: 0,
    },
    {
      q: "One gene producing two or more different phenotypic traits is called:",
      a: [
        "Codominance",
        "Expressivity",
        "Penetrance",
        "Pleiotropy",
        "Anticipation",
      ],
      correct: 3,
    },
    {
      q: "Marfan syndrome is inherited in which pattern?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 3,
    },
    {
      q: "The presence of a Barr body in the somatic cells of a male suggests which disorder?",
      a: [
        "Klinefelter syndrome",
        "Huntington disease",
        "Edwards syndrome",
        "Down syndrome",
        "Turner syndrome",
      ],
      correct: 0,
    },
    {
      q: "Which aortic arch regresses in humans?",
      a: ["Fifth", "First", "Third", "Sixth", "Fourth"],
      correct: 0,
    },
    {
      q: "A 28-year-old pregnant woman undergoes screening at 17 weeks of gestation. Her maternal serum alpha-fetoprotein (AFP) level is significantly elevated. Her pregnancy has otherwise been uncomplicated. This laboratory finding is most consistent with which congenital anomaly?",
      a: [
        "Down syndrome",
        "Volvulus",
        "Spina bifida",
        "Duodenal atresia",
        "Congenital heart defect",
      ],
      correct: 2,
    },
    {
      q: "Which anomaly is NOT part of the VATER association?",
      a: [
        "Vertebral defects",
        "Renal anomalies",
        "Volvulus",
        "Tracheoesophageal fistula",
        "Anal atresia",
      ],
      correct: 2,
    },
    {
      q: "A 17-year-old boy with newly diagnosed type 1 diabetes mellitus is found unconscious at home. His family reports that he felt ill the previous evening, skipped dinner, but took his usual dose of insulin. Emergency medical personnel find a finger-stick blood glucose level of 32 mg/dL and administer intramuscular glucagon. Glucagon binds to a transmembrane receptor on hepatocytes and promotes GTP binding to a receptor-associated protein, leading to rapid glycogen breakdown and glucose release. Which of the following is the primary mediator of these effects?",
      a: [
        "cGMP-dependent protein kinase",
        "Janus tyrosine kinase",
        "Phosphodiesterase",
        "Protein kinase A",
        "Tyrosine-specific protein kinase",
      ],
      correct: 3,
    },
    {
      q: "Geneticists are studying a defective protein that disrupts endothelial cell migration and angiogenesis. They determine that the protein is shorter than normal due to a nonsense mutation near the 3' end of the coding region. The abnormal mRNA sequence is: 5'-ACG-CUA-CCA-UUG-UAA-CAA-GUU-AGC-UAG-3'. Which tRNA anticodon is responsible for adding the final amino acid during synthesis of the truncated polypeptide?",
      a: ["5'-AAC-3'", "5'-AUC-3'", "5'-CAA-3'", "5'-GCU-3'", "5'-UCG-3'"],
      correct: 2,
    },
    {
      q: "Through which region does a direct inguinal hernia protrude?",
      a: [
        "Hesselbach's triangle",
        "Deep inguinal ring",
        "Rectus abdominis muscle",
        "Femoral ring",
        "Linea alba",
      ],
      correct: 0,
    },
    {
      q: "The foramen cecum is the site of origin of which gland?",
      a: [
        "Adrenal gland",
        "Parotid gland",
        "Pituitary gland",
        "Thyroid gland",
        "Parathyroid gland",
      ],
      correct: 3,
    },
    {
      q: "Identify the remnant of the obliterated umbilical artery.",
      a: [
        "Median umbilical ligament",
        "Medial umbilical ligament",
        "Lateral umbilical ligament",
        "Falciform ligament",
        "Round ligament of the liver",
      ],
      correct: 1,
    },
    {
      q: "The esophageal veins form a portocaval anastomosis with which vein?",
      a: [
        "Proper hepatic vein",
        "Common hepatic vein",
        "Right gastric vein",
        "Splenic vein",
        "Left gastric vein",
      ],
      correct: 4,
    },
    {
      q: "Which type of arthritis results from elevated uric acid levels in the blood?",
      a: [
        "Osteoarthritis",
        "Gout",
        "Rheumatoid arthritis",
        "Seronegative arthritis",
        "Septic arthritis",
      ],
      correct: 1,
    },
    {
      q: "The phrenic nerve arises from which spinal cord segments?",
      a: ["C1-C2", "C3-C5", "C5-C7", "C7-C8", "T1-T2"],
      correct: 1,
    },
    {
      q: "Which disease is characterized by gluten sensitivity and intolerance?",
      a: [
        "Hirschsprung disease",
        "Lactase deficiency",
        "Cystic fibrosis",
        "Celiac disease",
        "Achalasia",
      ],
      correct: 3,
    },
  ],
  eblock3: [
    {
      q: "Which nerve innervates the deltoid muscle?",
      a: [
        "Ulnar nerve",
        "Radial nerve",
        "Axillary nerve",
        "Median nerve",
        "Musculocutaneous nerve",
      ],
      correct: 2,
    },
    {
      q: "The SGLT2 transporter is an example of which type of transport?",
      a: [
        "Pinocytosis",
        "Phagocytosis",
        "Secondary active transport",
        "Primary active transport",
        "Facilitated diffusion",
      ],
      correct: 2,
    },
    {
      q: "In Turner syndrome, aneuploidy occurs in which chromosome pair?",
      a: ["8", "23", "21", "22", "14"],
      correct: 1,
    },
    {
      q: "Which histone subunit is NOT part of the nucleosome core octamer?",
      a: ["H2A", "H1", "H2B", "H3", "H4"],
      correct: 1,
    },
    {
      q: "Which process must pre-mRNA undergo to become mature mRNA?",
      a: [
        "Methylation",
        "Capping",
        "Acetylation",
        "Hydroxylation",
        "Glycosylation",
      ],
      correct: 1,
    },
    {
      q: "Hemophilia A is inherited in which pattern?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 1,
    },
    {
      q: "Which disease is caused by a trinucleotide repeat expansion?",
      a: [
        "Huntington disease",
        "Prader-Willi syndrome",
        "Parkinson disease",
        "Marfan syndrome",
        "Angelman syndrome",
      ],
      correct: 0,
    },
    {
      q: "In Down syndrome, Robertsonian translocation most commonly occurs between which chromosomes?",
      a: ["11 and 22", "14 and 21", "8 and 21", "13 and 21", "15 and 23"],
      correct: 1,
    },
    {
      q: "Which type of RNA contains both exons and introns?",
      a: ["hnRNA", "tRNA", "mRNA", "rRNA", "pre-rRNA"],
      correct: 0,
    },
    {
      q: "What is the condition called in which abdominal organs protrude outside the abdominal cavity without being covered by the peritoneum?",
      a: [
        "Gastroschisis",
        "Omphalocele",
        "Umbilical hernia",
        "Inguinal hernia",
        "Linea alba hernia",
      ],
      correct: 0,
    },
    {
      q: "Which of the following substances is a glycoprotein produced by the syncytiotrophoblast, which affects the corpus luteum of the ovary and stimulates the production of progesterone?",
      a: [
        "Human chorionic gonadotropin",
        "Estrogen",
        "Serotonin",
        "Testosterone",
        "Insulin",
      ],
      correct: 0,
    },
    {
      q: "Which type of cells in the nervous system proliferate following neuronal injury and serve as scavengers for cellular debris?",
      a: [
        "Microglial cells",
        "Astrocytes",
        "Oligodendrocytes",
        "Myocytes",
        "Hepatocytes",
      ],
      correct: 0,
    },
    {
      q: "Molecular biologists studying signal transduction apply an agent to human cells that activates G-protein-dependent phospholipase C. Which of the following intracellular substances is most likely to increase immediately after exposure to this agent?",
      a: ["Ca²⁺", "cAMP", "cGMP", "Cl⁻", "mRNA"],
      correct: 0,
    },
    {
      q: "Nutrition researchers investigating the relationship between fructose consumption and cardiovascular disease conduct a prospective cohort study on a population of randomly selected young adults. Study participants undergo semiannual measurement of waist circumference, blood pressure, and serum cholesterol and triglyceride concentrations. Dietary fructose consumption is assessed through the use of questionnaires and by measuring urinary fructose excretion. A 23-year-old man enrolled in the study is found to excrete large amounts of fructose in his urine compared to other study participants despite maintaining a moderate fructose intake. Further evaluation shows a hereditary defect in fructose metabolism, but he is asymptomatic and has no other medical problems. This patient most likely remains able to metabolize fructose due to the compensatory activity of which of the following enzymes?",
      a: [
        "Aldolase B",
        "Aldose reductase",
        "Fructokinase",
        "Hexokinase",
        "UDP-galactose-4-epimerase",
      ],
      correct: 3,
    },
    {
      q: "Which kidney cells produce erythropoietin (EPO)?",
      a: [
        "Juxtaglomerular cells",
        "Proximal tubule cells",
        "Podocytes",
        "Distal tubule cells",
        "Interstitial cells",
      ],
      correct: 4,
    },
    {
      q: "Which substance increases GFR by dilating the afferent arteriole?",
      a: [
        "Vasopressin",
        "Renin",
        "Angiotensin II",
        "Prostaglandins",
        "Aldosterone",
      ],
      correct: 3,
    },
    {
      q: "A 4-year-old child is brought to the physician because of fatigue and bone pain. Physical examination reveals generalized lymphadenopathy and a rash. Laboratory studies show anemia, thrombocytopenia, and lymphoblasts on the peripheral blood smear. The child is diagnosed with acute lymphoblastic leukemia (ALL) and started on doxorubicin therapy. This drug intercalates between DNA base pairs and inhibits DNA replication. During DNA replication, replication forks generate two daughter DNA strands. Which of the following is a characteristic feature of the daughter DNA strand synthesized opposite to the direction of fork movement?",
      a: [
        "DNA polymerase 3'→5' exonuclease activity",
        "DNA polymerase 3'→5' polymerase activity",
        "DNA polymerase 5'→3' exonuclease activity",
        "RNA primer synthesis before DNA synthesis",
        "Synthesis of multiple short DNA fragments",
      ],
      correct: 4,
    },
    {
      q: "Which vitamin should be taken before pregnancy to prevent neural tube defects?",
      a: [
        "Vitamin B1 (Thiamine)",
        "Vitamin B6 (Pyridoxine)",
        "Vitamin B9 (Folate)",
        "Vitamin C (Ascorbic acid)",
        "Vitamin E (Tocopherol)",
      ],
      correct: 2,
    },
    {
      q: "Failure of adequate dilation of the rectum results in which disease?",
      a: [
        "Intussusception",
        "Volvulus",
        "Hirschsprung disease",
        "Gastroschisis",
        "Omphalocele",
      ],
      correct: 2,
    },
    {
      q: "Which pathology causes urine to discharge from the umbilicus?",
      a: [
        "Vesicourachal diverticulum",
        "Urachal cyst",
        "Patent urachus",
        "Meckel diverticulum",
        "Omphalocele",
      ],
      correct: 2,
    },
    {
      q: "The malleus and incus develop from which pharyngeal arch?",
      a: ["Third", "Second", "First", "Fifth", "Fourth"],
      correct: 2,
    },
  ],
  eblock4: [
    {
      q: "Which of the following is NOT a feature of DiGeorge syndrome?",
      a: [
        "Caused by failure of development of the third pharyngeal pouch",
        "Caused by failure of development of the third pharyngeal pouch",
        "Associated with hypocalcemia",
        "Associated with thymic agenesis",
        "Increased parathyroid hormone (PTH) level",
      ],
      correct: 4,
    },
    {
      q: "Which substance stimulates gastric acid secretion?",
      a: ["Gastrin", "Somatostatin", "Secretin", "VIP", "Ghrelin"],
      correct: 0,
    },
    {
      q: "Which ligament is the remnant of the gubernaculum in females?",
      a: [
        "Pubocervical ligament",
        "Round ligament of the uterus",
        "Pubovesical ligament",
        "Sacrocervical ligament",
        "Rectouterine ligament",
      ],
      correct: 1,
    },
    {
      q: "Which is an effect of sympathetic nerve stimulation?",
      a: [
        "Pupillary constriction",
        "Decreased salivary secretion",
        "Vasodilation",
        "Bronchoconstriction",
        "Increased intestinal peristalsis",
      ],
      correct: 1,
    },
    {
      q: "Closure of which valves produces the first heart sound?",
      a: [
        "Aortic and pulmonary",
        "Aortic and mitral",
        "Pulmonary and mitral",
        "Aortic and tricuspid",
        "Mitral and tricuspid",
      ],
      correct: 4,
    },
    {
      q: "The head of which bone is surrounded by the annular ligament?",
      a: ["Radius", "Ulna", "Humerus", "Femur", "Tibia"],
      correct: 0,
    },
    {
      q: "Which nerve provides sensation to the palmar surface of the fifth finger?",
      a: [
        "Ulnar nerve",
        "Radial nerve",
        "Medial antebrachial cutaneous nerve",
        "Median nerve",
        "Lateral antebrachial cutaneous nerve",
      ],
      correct: 0,
    },
    {
      q: "Which organelle is surrounded by a double membrane?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Mitochondrion",
        "Lysosome",
        "Vacuole",
      ],
      correct: 2,
    },
    {
      q: "Interphase does NOT include which stage?",
      a: ["G1", "G2", "S", "Mitosis", "DNA synthesis"],
      correct: 3,
    },
    {
      q: "Bloom syndrome is caused by deficiency of which enzyme?",
      a: [
        "Primase",
        "DNA polymerase",
        "Topoisomerase II",
        "Helicase",
        "Topoisomerase I",
      ],
      correct: 3,
    },
    {
      q: "Which is a stop codon?",
      a: ["GAA", "AAA", "UAG", "GAG", "CGA"],
      correct: 2,
    },
    {
      q: "Cystic fibrosis is inherited in which pattern?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 4,
    },
    {
      q: "Which trinucleotide repeat is expanded in Friedreich ataxia?",
      a: ["GAA", "AAA", "UAG", "GAG", "CGA"],
      correct: 0,
    },
    {
      q: "Which condition has an increased incidence in Down syndrome?",
      a: [
        "Duodenal atresia",
        "Spina bifida",
        "Gastritis",
        "Pancreatitis",
        "Intussusception",
      ],
      correct: 0,
    },
    {
      q: "A 22-year-old man presents to the emergency department with a painful erection that began spontaneously 6 hours ago. The erection has persisted despite ice packs and analgesics. There is no history of trauma. The patient has sickle cell disease and is not taking any medications. Aspiration of the corpus cavernosum yields dark blood, and blood gas analysis shows: pH 7.21, PO₂ 26 mmHg, PCO₂ 68 mmHg. Which of the following is the most likely cause of this condition?",
      a: [
        "Fibrosis of the tunica albuginea",
        "Impaired venous drainage of the penis",
        "Impaired parasympathetic activity of the penis",
        "Increased arterial blood flow to the penis",
        "Increased sympathetic activity of the penis",
      ],
      correct: 1,
    },
    {
      q: "Which reaction does succinate dehydrogenase catalyze?",
      a: ["Oxidation of succinate to fumarate"],
      correct: 0,
    },
    {
      q: "The coronary arteries arise from which blood vessel?",
      a: [
        "Aorta",
        "Internal iliac artery",
        "Right subclavian artery",
        "Right common carotid artery",
        "Brachial artery",
      ],
      correct: 0,
    },
    {
      q: "Which artery is formed from the distal part of the first aortic arch?",
      a: [
        "Maxillary artery",
        "Internal carotid artery",
        "Stapedial artery",
        "The proximal part of the right pulmonary artery",
        "The proximal part of the right spinal artery",
      ],
      correct: 0,
    },
    {
      q: "Which enzyme can convert phospholipids of cell membranes to arachidonic acid?",
      a: [
        "Phospholipase A2",
        "ATPase",
        "Protein kinase",
        "Uricase",
        "Catalase",
      ],
      correct: 0,
    },
    {
      q: "A 69-year-old woman with Alzheimer disease is brought to the emergency department after getting lost while taking a walk in her neighborhood. Her son has been unable to contact her for the last 2 days, and today the police found her wandering in a park. She drank water from a park fountain but has not eaten for over 24 hours. Physical examination shows mild confusion and dry mucous membranes. Her blood glucose level is 92 mg/dL. Which hormone binds to an intracellular receptor to help maintain this normal blood glucose level?",
      a: ["Cortisol", "Epinephrine", "Glucagon", "Growth hormone", "Insulin"],
      correct: 0,
    },
    {
      q: "Which structure develops from the truncus arteriosus?",
      a: [
        "Ascending aorta",
        "Common carotid artery",
        "Left ventricle",
        "Inferior vena cava",
        "Coronary sinus",
      ],
      correct: 0,
    },
    {
      q: "Meckel diverticulum develops in which part of the gastrointestinal tract?",
      a: ["Duodenum", "Stomach", "Jejunum", "Colon", "Ileum"],
      correct: 4,
    },
    {
      q: "Experiments are performed to determine the structure and function of different types of bacterial RNA. Staphylococcus aureus cells are lysed, and RNA molecules are isolated. A 90-nucleotide RNA containing abundant dihydrouridine, pseudouridine, and ribothymidine is identified. Its secondary structure is formed by intramolecular base pairing. Which of the following represents the 3' end of this molecule?",
      a: ["AUG", "CCA", "Methylguanosine triphosphate", "Poly-A", "TATA"],
      correct: 1,
    },
  ],
  eblock5: [
    {
      q: "In Nutcracker syndrome, the renal vein is compressed beneath which structure?",
      a: [
        "Liver",
        "Inferior mesenteric artery",
        "Superior mesenteric artery",
        "Celiac artery",
        "Umbilical artery",
      ],
      correct: 2,
    },
    {
      q: "The glans penis develops from which structure?",
      a: [
        "Genital tubercle",
        "Urogenital fold",
        "Urogenital sinus",
        "Labioscrotal swelling",
        "Genital cleft",
      ],
      correct: 0,
    },
    {
      q: "Schwannoma most commonly occurs in which cranial nerve?",
      a: ["CN VIII", "CN IX", "CN X", "CN VII", "CN V"],
      correct: 0,
    },
    {
      q: "The short gastric arteries arise from which artery?",
      a: [
        "Proper hepatic artery",
        "Common hepatic artery",
        "Right gastric artery",
        "Left gastric artery",
        "Splenic artery",
      ],
      correct: 4,
    },
    {
      q: "At which vertebral level is the aortic hiatus of the diaphragm located?",
      a: ["T12", "L1", "T10", "L3", "T8"],
      correct: 0,
    },
    {
      q: "What is the condition called in which impaired bone resorption results in abnormally dense bones?",
      a: [
        "Osteoporosis",
        "Osteopenia",
        "Osteopetrosis",
        "Osteomalacia",
        "Osteoarthritis",
      ],
      correct: 2,
    },
    {
      q: "Which cells produce antibodies?",
      a: [
        "Plasma cells",
        "T lymphocytes",
        "Macrophages",
        "Neutrophils",
        "Eosinophils",
      ],
      correct: 0,
    },
    {
      q: "The olecranon is part of which bone?",
      a: ["Radius", "Ulna", "Humerus", "Femur", "Tibia"],
      correct: 1,
    },
    {
      q: "Which nerve passes through the carpal tunnel?",
      a: [
        "Ulnar nerve",
        "Radial nerve",
        "Axillary nerve",
        "Suprascapular nerve",
        "Median nerve",
      ],
      correct: 4,
    },
    {
      q: "What gives the rough endoplasmic reticulum its granular appearance?",
      a: [
        "Mitochondria",
        "Golgi apparatus",
        "Ribosomes",
        "Lysosomes",
        "Vacuoles",
      ],
      correct: 2,
    },
    {
      q: "Which vitamin is required for collagen synthesis?",
      a: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B6", "Vitamin B1"],
      correct: 2,
    },
    {
      q: "Which enzyme relieves DNA supercoiling before hydrogen bonds are broken during DNA replication?",
      a: [
        "Primase",
        "DNA polymerase",
        "DNA ligase",
        "Helicase",
        "Topoisomerase",
      ],
      correct: 4,
    },
    {
      q: "The acceptor stem of tRNA ends with which triplet?",
      a: ["GAA", "AAA", "UAG", "GAG", "CCA"],
      correct: 4,
    },
    {
      q: "In Huntington disease, which process causes the disease to appear at an earlier age in successive generations?",
      a: [
        "Codominance",
        "Expressivity",
        "Penetrance",
        "Pleiotropy",
        "Anticipation",
      ],
      correct: 4,
    },
    {
      q: "Duchenne muscular dystrophy is inherited in which pattern?",
      a: [
        "Mitochondrial",
        "X-linked recessive",
        "X-linked dominant",
        "Autosomal dominant",
        "Autosomal recessive",
      ],
      correct: 1,
    },
    {
      q: "The CAG triplet codes for which amino acid?",
      a: ["Valine", "Glutamine", "Alanine", "Lysine", "Histidine"],
      correct: 1,
    },
    {
      q: "Which hormone is produced by the zona glomerulosa of the adrenal cortex?",
      a: [
        "Aldosterone",
        "Androstenedione",
        "Cortisol",
        "Epinephrine",
        "Norepinephrine",
      ],
      correct: 0,
    },
    {
      q: "Which disease is characterized by a congenital malformation in which the cerebellum and medulla protrude through the foramen magnum into the spinal canal?",
      a: [
        "Arnold-Chiari malformation",
        "Lou Gehrig disease",
        "Bronchial asthma",
        "Pulmonary emphysema",
        "Horner syndrome",
      ],
      correct: 0,
    },
    {
      q: "What is the term used when the placenta attaches in the lower part of the uterus, covering the internal os?",
      a: [
        "Placenta previa",
        "Vasa previa",
        "Placenta accreta",
        "Placenta percreta",
        "Placenta increta",
      ],
      correct: 0,
    },
    {
      q: "A 45-year-old woman with chronic kidney disease undergoes a renal biopsy. Thickening of the glomerular basement membrane is observed. Which type of collagen is the major component of this membrane?",
      a: [
        "Type IV collagen",
        "Type I collagen",
        "Type II collagen",
        "Type III collagen",
        "Type V collagen",
      ],
      correct: 0,
    },
    {
      q: "Which structure develops from the ureteric bud?",
      a: [
        "Loop of Henle",
        "Renal pelvis",
        "Bowman's capsule",
        "Proximal tubule",
        "Distal tubule",
      ],
      correct: 1,
    },
    {
      q: "Which pathology causes oligohydramnios?",
      a: [
        "Pulmonary hypoplasia",
        "Posterior urethral valve",
        "Tracheoesophageal fistula",
        "Duodenal atresia",
        "Pyloric stenosis",
      ],
      correct: 1,
    },
    {
      q: "The stylopharyngeus muscle develops from which pharyngeal arch?",
      a: ["Third", "Second", "First", "Fifth", "Fourth"],
      correct: 0,
    },
    {
      q: "Which ligament is NOT a component of the greater omentum?",
      a: [
        "Hepatogastric ligament",
        "Gastrosplenic ligament",
        "Gastrorenal ligament",
        "Gastrocolic ligament",
        "Gastrophrenic ligament",
      ],
      correct: 0,
    },
    {
      q: "The epigastric veins form a portocaval anastomosis with which vein?",
      a: [
        "Paraumbilical veins",
        "Common hepatic vein",
        "Right gastric vein",
        "Splenic vein",
        "Left gastric vein",
      ],
      correct: 0,
    },
    {
      q: "Which is an effect of parasympathetic nerve stimulation?",
      a: [
        "Pupillary dilation",
        "Increased salivary secretion",
        "Vasoconstriction",
        "Bronchodilation",
        "Decreased intestinal peristalsis",
      ],
      correct: 1,
    },
    {
      q: "What is the accumulation of pus in the pleural cavity called?",
      a: [
        "Pneumothorax",
        "Chylothorax",
        "Hydrothorax",
        "Hemothorax",
        "Pyothorax",
      ],
      correct: 4,
    },
    {
      q: "The trochlea is part of which bone?",
      a: ["Radius", "Ulna", "Humerus", "Femur", "Tibia"],
      correct: 2,
    },
    {
      q: "Which type of transport occurs without energy expenditure?",
      a: [
        "Pinocytosis",
        "Phagocytosis",
        "Secondary active transport",
        "Primary active transport",
        "Simple diffusion",
      ],
      correct: 4,
    },
  ],
  eblock6: [
    {
      q: "Which organelle lacks a membrane?",
      a: [
        "Endoplasmic reticulum",
        "Golgi apparatus",
        "Ribosome",
        "Lysosome",
        "Vacuole",
      ],
      correct: 2,
    },
    {
      q: "In which type of mutation does the amino acid sequence of the synthesized protein remain unchanged?",
      a: ["Deletion", "Frameshift", "Silent", "Nonsense", "Missense"],
      correct: 2,
    },
    {
      q: "Which of the following is a stop codon?",
      a: ["GAA", "AAA", "UAA", "GAG", "CGA"],
      correct: 2,
    },
    {
      q: "Which process must pre-mRNA undergo to become mature mRNA?",
      a: [
        "Methylation",
        "Polyadenylation",
        "Acetylation",
        "Hydroxylation",
        "Glycosylation",
      ],
      correct: 1,
    },
    {
      q: "Which disease is associated with genomic imprinting?",
      a: [
        "Huntington disease",
        "Prader-Willi syndrome",
        "Parkinson disease",
        "Myotonic dystrophy",
        "Fragile X syndrome",
      ],
      correct: 1,
    },
    {
      q: "Which trinucleotide repeat is expanded in Huntington disease?",
      a: ["GAA", "AAA", "UAG", "CAG", "CGA"],
      correct: 3,
    },
    {
      q: "Which part of tRNA is responsible for recognition by aminoacyl-tRNA synthetase?",
      a: ["T arm", "D arm", "Acceptor stem", "Anticodon", "Variable loop"],
      correct: 1,
    },
    {
      q: "Which enzyme digests proteins?",
      a: ["Trypsin"],
      correct: 0,
    },
    {
      q: "A 28-year-old man has had muscle weakness and headaches for the past 2 months. He denies palpitations, tremor, or excessive sweating. Blood pressure is 190/120 mmHg. Serum potassium is 2.8 mEq/L. Plasma renin activity and aldosterone levels are elevated. A 24-hour urine collection shows increased potassium excretion. Which of the following is the most likely cause of this patient's symptoms?",
      a: [
        "Adrenal cortical tumor",
        "Adrenal medullary tumor",
        "Juxtaglomerular cell tumor",
        "Pituitary tumor",
        "Primary hypertension",
      ],
      correct: 2,
    },
    {
      q: "Which part of the adrenal gland produces glucocorticoids?",
      a: [
        "Zona fasciculata",
        "Zona reticularis",
        "Adrenal medulla",
        "Zona glomerulosa",
        "Zona basalis",
      ],
      correct: 0,
    },
    {
      q: "Vagotomy is performed to treat which disease?",
      a: [
        "Peptic ulcer disease",
        "Tetralogy of Fallot",
        "Aortic aneurysm",
        "Emphysema",
        "Klippel-Feil syndrome",
      ],
      correct: 0,
    },
    {
      q: "Which disease is caused by substitution of GAG with GTG, resulting in valine replacing glutamate?",
      a: [
        "Sickle cell anemia",
        "Xeroderma pigmentosum",
        "Bloom syndrome",
        "Cockayne syndrome",
        "Alport syndrome",
      ],
      correct: 0,
    },
    {
      q: "A 34-year-old woman came to the hospital complaining of abnormal uterine bleeding and severe abdominal pain radiating to the left groin. Her blood hCG level is moderately elevated. What is the most likely diagnosis?",
      a: [
        "Ectopic pregnancy",
        "Pelvic inflammatory disease",
        "Polycystic ovary syndrome",
        "Endometriosis",
        "Kallmann syndrome",
      ],
      correct: 0,
    },
    {
      q: "Identify the excitatory neurotransmitters among the following.",
      a: [
        "Dopamine, serotonin",
        "Serotonin, glycine",
        "GABA, adrenaline",
        "Glycine, glutamate",
        "GABA, dopamine",
      ],
      correct: 0,
    },
    {
      q: "Biologists investigating reversible cellular injury find that prolonged ischemia causes ribosomes to detach from the rough endoplasmic reticulum. This structural change most directly impairs which cellular function?",
      a: [
        "ATP production",
        "Drug detoxification",
        "Synthesis of cell membrane proteins",
        "Synthesis of cytosolic proteins",
        "Synthesis of steroid hormones",
      ],
      correct: 2,
    },
    {
      q: "Which ion enters the cell during depolarization of the action potential, making the membrane potential more positive?",
      a: ["Na⁺", "K⁺", "Cl⁻", "Ca²⁺", "Mg²⁺"],
      correct: 0,
    },
    {
      q: "Cortisol causes which metabolic change?",
      a: [
        "Increases gluconeogenesis",
        "Increases lipogenesis",
        "Increases protein synthesis",
        "Decreases blood pressure",
        "Increases glucose uptake",
      ],
      correct: 0,
    },
    {
      q: "Which kidney cells produce erythropoietin (EPO)?",
      a: [
        "Juxtaglomerular cells",
        "Proximal tubule cells",
        "Podocytes",
        "Distal tubule cells",
        "Interstitial cells",
      ],
      correct: 4,
    },
    {
      q: "In a healthy standing person, which region of the lung has the highest ventilation/perfusion (V/Q) ratio?",
      a: [
        "Apex of the lung",
        "Middle region of the lung",
        "Lower lobe of the left lung",
        "Hilum of the lung",
        "Lower lobe of the right lung",
      ],
      correct: 0,
    },
    {
      q: "A decrease in the level of which substance is required for closure of the patent ductus arteriosus?",
      a: [
        "Prostaglandin E",
        "Thromboxane A₂",
        "Histamine",
        "Serotonin",
        "Ferritin",
      ],
      correct: 0,
    },
    {
      q: "A 23-year-old woman sustains a linear skull fracture at the junction of the frontal, parietal, temporal, and sphenoid bones. A branch of which artery is most likely severed?",
      a: [
        "Facial artery",
        "Maxillary artery",
        "Middle cerebral artery",
        "Occipital artery",
        "Ophthalmic artery",
      ],
      correct: 1,
    },
    {
      q: "A physician inserts a needle along the upper border of the 10th rib at the right midaxillary line. Which structure is most likely to be punctured?",
      a: [
        "Right lower lobe of the lung",
        "Liver",
        "Intercostal artery",
        "Intercostal nerve",
        "Hepatic veins",
      ],
      correct: 1,
    },
    {
      q: "Which signaling pathway increases intracellular calcium and stimulates muscle contraction?",
      a: ["Gs", "Gi", "Gq", "Tyrosine kinase", "JAK-STAT"],
      correct: 2,
    },
  ],
  eblock7: [
    {
      q: "A 28-year-old woman at 35 weeks of pregnancy presents with abdominal pain and headache. She has felt weak and nauseated for several days. She has no history of hypertension or liver disease. Blood pressure is 160/100 mmHg, pulse is 88/min. Laboratory results: Hemoglobin 9.2 g/dL, Platelets 80,000/mm³, AST 165 IU/L, ALT 150 IU/L, LDH 600 IU/L, and peripheral smear shows hemolytic anemia. Which of the following is the most likely diagnosis?",
      a: [
        "Acute fatty liver of pregnancy",
        "Thrombotic thrombocytopenic purpura",
        "HELLP syndrome",
        "Disseminated intravascular coagulation (DIC)",
        "Autoimmune hepatitis",
      ],
      correct: 2,
    },
    {
      q: "A 56-year-old woman with systemic sclerosis undergoes right heart catheterization. A balloon-tipped catheter is advanced into the pulmonary artery, and a branch is occluded to measure pressure beyond the occlusion. This pressure most closely corresponds to which of the following?",
      a: [
        "Intrapleural pressure",
        "Left atrial pressure",
        "Mean airway pressure",
        "Mean arterial pressure",
        "Pulse pressure",
      ],
      correct: 1,
    },
    {
      q: "A 66-year-old man with loculated left pleural effusion undergoes chest tube placement through the 5th intercostal space at the midaxillary line. Which muscle is most likely to be dissected during the procedure?",
      a: [
        "External oblique",
        "Infraspinatus",
        "Latissimus dorsi",
        "Pectoralis major",
        "Serratus anterior",
      ],
      correct: 4,
    },
    {
      q: "Which structure develops from the third aortic arch?",
      a: [
        "Subclavian artery",
        "Superior vena cava",
        "Common carotid artery",
        "Truncus arteriosus",
        "Descending aorta",
      ],
      correct: 2,
    },
    {
      q: "A 28-year-old pregnant woman undergoes screening at 17 weeks of gestation. Maternal serum alpha-fetoprotein (AFP) is significantly elevated. Which congenital anomaly is most consistent with this finding?",
      a: [
        "Down syndrome",
        "Volvulus",
        "Spina bifida",
        "Duodenal atresia",
        "Congenital heart defect",
      ],
      correct: 2,
    },
    {
      q: "Which nerve is affected in carpal tunnel syndrome?",
      a: [
        "Median nerve",
        "Ulnar nerve",
        "Radial nerve",
        "Musculocutaneous nerve",
        "Axillary nerve",
      ],
      correct: 0,
    },
    {
      q: "A 58-year-old man with hepatocellular carcinoma is scheduled for arterial embolization. Contrast should be injected into which structure to visualize the artery supplying the tumor?",
      a: [
        "Celiac trunk",
        "Gastroduodenal artery",
        "Inferior mesenteric artery",
        "Inferior vena cava",
        "Splenic artery",
      ],
      correct: 0,
    },
    {
      q: "A 22-year-old man sustains a stab wound just above the clavicle between the midclavicular and lateral sternal lines. Which structure is most likely injured?",
      a: [
        "Accessory nerve",
        "Ansa cervicalis",
        "Carotid body",
        "Inferior thyroid artery",
        "Pleura of the lung",
      ],
      correct: 4,
    },
    {
      q: "Vitamin C deficiency primarily affects the synthesis of which protein?",
      a: ["Keratin", "Collagen", "Elastin", "Fibrillin", "Actin"],
      correct: 1,
    },
    {
      q: "A 2-year-old child has recurrent fractures, blue sclerae, and hearing loss. This disease is caused by a defect in the synthesis of which type of collagen?",
      a: [
        "Type I collagen",
        "Type II collagen",
        "Type III collagen",
        "Type IV collagen",
        "Type VII collagen",
      ],
      correct: 0,
    },
    {
      q: "A 30-year-old woman presents 8 weeks postpartum with prolonged vaginal bleeding, lower abdominal pain, fatigue, and dyspnea. Beta-hCG is markedly elevated, hemoglobin is 9.5 g/dL, and chest x-ray shows multiple pulmonary infiltrates. What is the most likely diagnosis?",
      a: [
        "Endometrial carcinoma",
        "Gestational trophoblastic disease",
        "Choriocarcinoma",
        "Ovarian cancer",
        "Uterine leiomyoma",
      ],
      correct: 2,
    },
    {
      q: "Which cells play a key role in regeneration of peripheral nerves?",
      a: [
        "Schwann cells",
        "Oligodendrocytes",
        "Microglial cells",
        "Astrocytes",
        "Endothelial cells",
      ],
      correct: 0,
    },
    {
      q: "In a patient with liver cirrhosis, increased collagen production is observed. Which cells play the primary role in collagen synthesis?",
      a: [
        "Fibroblasts",
        "Macrophages",
        "Hepatocytes",
        "Kupffer cells",
        "Ito cells",
      ],
      correct: 0,
    },
    {
      q: "A 30-year-old patient has short stature and a short, broad neck. Karyotype analysis reveals 45,XO. Which syndrome does this indicate?",
      a: [
        "Klinefelter syndrome",
        "Turner syndrome",
        "Fragile X syndrome",
        "Patau syndrome",
        "Edwards syndrome",
      ],
      correct: 1,
    },
    {
      q: "A 63-year-old woman undergoes right oophorectomy for an ovarian mass. To avoid excessive bleeding, which structure should be ligated during the procedure?",
      a: [
        "Mesosalpinx",
        "Ovarian ligament",
        "Round ligament of the uterus",
        "Suspensory ligament of the ovary",
        "Transverse cervical ligament",
      ],
      correct: 3,
    },
  ],
};
