window.TEST_QUESTIONS = {
  m1: [
    {
      q: "Oqsilning qaysi shakl(lar)ida S-S (‘disulfid’) bog’lanish uchraydi?",
      a: [
        "Birlamchi",
        "Ikkilamchi",
        "Polisaxarid",
        "Uchlamchi va To’rtlamchi",
        "Faqat uchlamchi",
      ],
      correct: 3,
    },
    {
      q: "Quyida berilgan moddalardan disaxaridni toping ?",
      a: ["Selluloza", "Laktoza", "Fruktoza", "Galaktoza", "Glikogen"],
      correct: 1,
    },
    {
      q: "Purin asoslarini toping ?",
      a: [
        "Guanin, Adenin",
        "Guanin, Sitozin",
        "Adenin, Timin",
        "Uratsil, Adenin",
        "Uridin, Timidin",
      ],
      correct: 0,
    },
    {
      q: "DNK ni tashkil etuvchi purin va pirimidinlar to’g’ri moslashgan javobni toping.",
      a: [
        "Adenin va Timin",
        "Guanin va Uratsil",
        "Guanin va Adenin",
        "Uratsil va Adenin",
        "Uratsil va Uratsil",
      ],
      correct: 0,
    },
    {
      q: "Quyidagilar orasidan to‘g‘ri fikrni toping?",
      a: [
        "Guanin qo’shbog’ bilan Sitozinga birikkan",
        "Adenin uchbog‘ bilan Timinga birikkan",
        "Guanin qo‘sh bog‘ bilan Timinga birikkan",
        "Adenin qo‘sh bog‘ bilan Sitozinga birikkan",
        "Guanin uchbog‘ bilan Sitozinga birikkan",
      ],
      correct: 4,
    },
    {
      q: "Lipoproteinlar zichligining yuqori yoki pastligi tarkibidagi qaysi moddaga ko’proq bog‘liq?",
      a: [
        "Polisaxaridlar",
        "Fosfolipid",
        "Apoproteinlar",
        "Triglitseridlar",
        "Xolesterin",
      ],
      correct: 2,
    },
    {
      q: "Eritrotsitlarning o’zaro yopishib qolmasligida muhim ro’l o’ynovchi kislotani belgilang.",
      a: [
        "Sut kislota",
        "Sial kislota",
        "Xlorid kislota",
        "Geparin",
        "Sulfat kislota",
      ],
      correct: 1,
    },
    {
      q: "Hujayra yadrosidagi DNK strukturasining zichlashishida muhim ro’l tutuvchi oqsillar qaysi?",
      a: [
        "Apoproteinlar",
        "DNK strukturasi doimo yoyilgan, zichlashmagan holda turadi",
        "Giston oqsillari",
        "Insulin",
        "Miozin",
      ],
      correct: 2,
    },
  ],
  m2: [
    {
      q: "Membrana fosfolipidlarining bosh qismi nimadan tashkil topgan ?",
      a: [
        "Gidrofilik : Fosfat va Glitserol",
        "Gidrofobik : Fosfat va Glitserol",
        "Yog’ kislota polimerlari",
        "To’yinmagan yog’ kislota va Glitserol",
        "Gidrofilik to’yingan yog’ kislota va Fosfat",
      ],
      correct: 0,
    },
    {
      q: "Hujayra membranasidagi Xolesterinning o’rni qanday?",
      a: [
        "Xlor ionlarining hujayra ichiga o’tishini ta’minlaydi",
        "Membrananing suyuqlilik xususiyatini ta’minlaydi",
        "Membranaga manfiy zaryadni beradi",
        "Retseptor vazifasini bajaradi",
        "Qon-tomir devoriga yopishishini ta’minlaydi",
      ],
      correct: 1,
    },
    {
      q: "Ekstrasellular yuzada uchrovchi fosfolipidni belgilang.",
      a: [
        "Fosfatidilserin",
        "Fosfatidilinozitol",
        "Diatsilglitserol",
        "Xolesterin",
        "Sfingomiyelin",
      ],
      correct: 4,
    },
    {
      q: "Quyidagilardan qaysi biri integral membrana oqsillariga tegishli?",
      a: [
        "Har doim boshqa membrana oqsillari bilan nokovalent bog‘langan",
        "Membrananing faqat tashqi qismiga biriktirilgan",
        "Membrananing faqat ichki qismiga biriktirilgan",
        "Faqatgina hujayraning sitoskelet strukturasini ta’minlaydi",
        "Membrana qo’shqavatini kesib o’tadi va Transmembrana domeniga ega",
      ],
      correct: 4,
    },
  ],
  m3: [
    {
      q: "Diffuziyani oshiruvchi faktorni tanlang.",
      a: [
        "Zaryadlanishning ortishi",
        "Konsentratsiya gradientining kamayishi",
        "Membrananing qalinlashishi",
        "Yuzaning ortishi",
        "Intrasellular anionlar miqdorining ortishi",
      ],
      correct: 3,
    },
    {
      q: "Yengillashgan diffuziyaning oddiy diffuziyadan farqi nima?",
      a: [
        "Kichik molekulali moddalar harakatlanadi",
        "Kanallar va transport oqsillari qatnashadi",
        "Asosan Steroid gormonlar tashiladi",
        "Retseptor funksiyasiga ega",
        "Yadro bilan bog’liq holda ishlaydi",
      ],
      correct: 1,
    },
    {
      q: "Natriy-Glukoza kotransporterlarining 2-tipi (SGLT-2) qayerda uchraydi?",
      a: [
        "Enterositlarda",
        "Yurak muskulida",
        "Nefron kanallarida",
        "Skelet muskulida",
        "Ko’z gavharida",
      ],
      correct: 2,
    },
    {
      q: "Insulin tegishli to’qimalardagi Glukozaning qaysi transporteri ekspressiyasini oshiradi ?",
      a: ["SGLT-1", "SGLT-2", "GLUT-3", "GLUT-4", "GLUT-1"],
      correct: 3,
    },
    {
      q: "Endotsitoz va Transsitoz membrana transport tizimining qaysi turiga misol bo’ladi?",
      a: [
        "Vezikulyar",
        "Ikkilamchi aktiv",
        "Birlamchi aktiv",
        "Passiv",
        "Yengillashgan diffuziya",
      ],
      correct: 0,
    },
    {
      q: "Qaysi transporter ishining bloklanishi Qandli Diabet terapiyasida foydali bo’lishi mumkin?",
      a: [
        "Na-kanallari",
        "K-kanallari",
        "Na-K-ATFaza",
        "Xlor kanallari",
        "SGLT-2",
      ],
      correct: 4,
    },
    {
      q: "Makrofaglarning patogen organizmlarni Fagotsitoz qilishi qaysi transport turiga misol bo’ladi?",
      a: [
        "Yengillashgan diffuziya",
        "Ikkilamchi aktiv",
        "Vezikulyar",
        "Birlamchi aktiv",
        "Passiv",
      ],
      correct: 2,
    },
    {
      q: "0.7% li NaCl eritmasi qonga quyilganda qizil qon hujayralarining shishib, gemolizga uchrashi qaysi transport hodisasiga misol bo’ladi?",
      a: ["Transsitoz", "Osmos", "Endotsitoz", "Pinotsitoz", "Ekzotsitoz"],
      correct: 1,
    },
    {
      q: "Lipoproteinlarning Gepatotsitlar tomonidan o’zlashtirilishi qaysi transport turiga misol bo’ladi?",
      a: [
        "Retseptorli-endotsitoz",
        "Yengillashgan diffuziya",
        "Passiv diffuziya",
        "Transsitoz",
        "Ekzotsitoz",
      ],
      correct: 0,
    },
    {
      q: "Qaysi oqsillar yordamida sitotoksik dorilarning o’smalarga qarshi effekti kamayadi?",
      a: [
        "Albumin oqsili",
        "MDR (Multi-Drug-Resistant proteins) oqsillari",
        "Gemoglobin oqsili",
        "RNK-polimeraza",
        "DNK-polimeraza",
      ],
      correct: 1,
    },
  ],
  m4: [
    {
      q: "Ikki qavatli membrana bilan o’ralgan organoidlarni belgilang.",
      a: [
        "Mitoxondriya, Yadro",
        "Golji, Silliq Endoplazmatik To’r",
        "Lizosoma, Golji",
        "Peroksisoma, Donador Endoplazmatik To’r",
        "Sentriola, Mikrotubula",
      ],
      correct: 0,
    },
    {
      q: "Steroid moddalar sintezida qaysi organoid qatnashadi?",
      a: [
        "Nissl tanachalarida",
        "Donador endoplazmatik to’r",
        "Silliq endoplazmatik to’r",
        "Golji apparati",
        "Erkin Ribosomalar",
      ],
      correct: 2,
    },
    {
      q: "Urug’don va Tuxumdonda ko’p uchrovchi organoid qaysi?",
      a: [
        "Peroksisomalar",
        "Donador endoplazmatik to’r",
        "Lizosomalar",
        "Silliq endoplazmatik to’r",
        "Nissl tanachalarida",
      ],
      correct: 3,
    },
    {
      q: "Silliq endoplazmatik to’r asosan qaysi enzimni o’zida tutishi bilan ajralib turadi?",
      a: [
        "Na-K-ATFaza",
        "Glukoza-6-Fosfataza",
        "Geksokinaza",
        "Glukokinaza",
        "Lipaza",
      ],
      correct: 1,
    },
    {
      q: "Nerv hujayrasi shikastlanganligini baholashda qaysi markerdan foydalanish mumkin?",
      a: [
        "Aktin filamentlarining qisqarib qolishi",
        "Lizosomalar rangining o’zgarishi",
        "Nissl tanachalarining tarqoq joylashishi",
        "Triglitseridlarning ko’p hosil bo’lishi",
        "Peroksisomaning erishi",
      ],
      correct: 2,
    },
    {
      q: "Nissl tanachalari nima?",
      a: [
        "Neyronlardagi donador endoplazmatik retikulum",
        "Neyronlardagi silliq endoplazmatik retikulum",
        "Erkin ribosomalar",
        "Nefrondagi donador endoplazmatik retikulum",
        "Neyronga to’plangan peroksisomalar",
      ],
      correct: 0,
    },
  ],
  m5: [
    {
      q: "Yadro va Mitoxondriya uchun umumiy bo’lgan xususiyatni toping.",
      a: [
        "Elektronlar transporti orqali ATF hosil qilishi",
        "O’z genetik materialiga ega",
        "Glukoneogenezni amalga oshirish",
        "Glukoza-6-Fosfataza miqdorini ko’p miqdorda yig’ish",
        "O’xshashlik umuman yo’q",
      ],
      correct: 1,
    },
    {
      q: "To’g’ri fikrni toping.",
      a: [
        "Hujayraning barcha ATF molekulalari Silliq Endoplazmatik To’rda zahiralanadi",
        "Golji apparati Ribosomadan ajralgan vezikulalarni Trans-yuza orqali qabul qiladi",
        "Mitoxondriyaning genetik materiali qo’sh zanjirli RNK dan iborat",
        "Golji apparati Endoplazmatik to’rdan ajralgan vezikulalarni Sis-yuza orqali qabul qiladi",
        "Yetilgan qizil qon hujayralarining mitoxondriyalar miqdori Neytrofillardagi mitoxondriyalar soniga teng",
      ],
      correct: 3,
    },
    {
      q: "Farzandlariga faqat onadan o’tadigan kasalliklar qaysi organoidga xos?",
      a: [
        "Peroksisoma",
        "Mitoxondriya",
        "Lizosoma",
        "Golji apparati",
        "Ribosoma",
      ],
      correct: 1,
    },
    {
      q: "Mitoxondriya genetik materialiga xos bo’lgan xususiyatni tanlang.",
      a: [
        "Qo’sh zanjirli DNK, halqasimon",
        "Bir zanjirli RNK, spiralsimon",
        "Qo’sh zanjirli RNK, halqasimon",
        "10 ga yaqin Plazmiddan iborat",
        "Mitoxondriya mustaqil irsiy materialga ega emas",
      ],
      correct: 0,
    },
    {
      q: "Quyidagi hujayralarning qaysi birida nisbatan ko’p miqdorda mitoxondriya bo’ladi?",
      a: [
        "Gepatotsit",
        "Teri hujayrasi",
        "Eritrotsit",
        "Soch follikulalari",
        "Muskul hujayrasi",
      ],
      correct: 4,
    },
    {
      q: "Nima uchun Mitoxondrial DNK ning mutatsiyaga moyilligi yuqori?",
      a: [
        "Ribosomalarga birikkanligi uchun",
        "Sitozolda erkin yurganligi uchun",
        "Gistonlarga birikmaganligi uchun",
        "Lipid membranaga ega bo’lmaganligi uchun",
        "Kislorod atomlari kamligi uchun",
      ],
      correct: 2,
    },
    {
      q: "Aerob Glikolizni amalga oshishi qaysi organoidga bog’liq?",
      a: [
        "Sarkoplazmatik To’r",
        "Mitoxondriya",
        "Endoplazmatik To’r",
        "Ribosoma",
        "Yadro",
      ],
      correct: 1,
    },
    {
      q: "Bemorning es-hushi buzilgan, muskullarda og’riq, qonda sut kislota miqdori ortgan. Qaysi organoidda katta ehtimol bilan patologiya mavjud?",
      a: [
        "Ribosoma",
        "Yadrocha",
        "Golji Apparati",
        "Sitoplazmatik membrana",
        "Mitoxondriya",
      ],
      correct: 4,
    },
  ],
  m6: [
    {
      q: "Hujayraning hazm sistemasi deb ataladigan organoidga tegishli to’g’ri fikrni toping?",
      a: [
        "Silindrsimon shakldagi, tarkibida kam miqdorda fermentlar saqlovchi organella",
        "Membranasiz organoid",
        "2 qavat membranaga ega",
        "Vodorod peroksidni suvga aylanishida asosiy ro’lni o’ynaydi",
        "1 qavat membranaga ega",
      ],
      correct: 4,
    },
    {
      q: "Lizosomalarning diametri va shakli qanday?",
      a: [
        "15-20 nm, spiral shaklda",
        "0,8-10 mkm, slindrsimon",
        "0,2-0,8 mkm, sharsimon yoki pufaksimon",
        "7 nm, bochkasimon",
        "12-15 nm, uzun ipsimon",
      ],
      correct: 2,
    },
    {
      q: "Ikkilamchi lizosomalarga tegishli fikrni toping?",
      a: [
        "Hujayrada pH pasayganda fermentlari faolligi ortadi",
        "Tarkibidagi fermentlar nofaol holatda bo’ladi",
        "Hujayrada pH ortganda fermentlari faollashadi",
        "Hujayraning asosiy energiya manbai",
        "pH ko’rsatkichi fermentlar faolligiga ta’sir qilmaydi",
      ],
      correct: 0,
    },
    {
      q: "Membranasi va matriksida 50 dan ortiq gidrolitik fermentlar (fosfataza, nukleazalar, katepsin, kollagenaza, glyukuronidaza, glyukozidaza va boshqalar) tutadigan, bir membranali organella qaysi?",
      a: [
        "Peroksisoma",
        "Lizosoma",
        "Golji apparati",
        "Silliq endoplazmatik to’r",
        "Erkin Ribosomalar",
      ],
      correct: 1,
    },
    {
      q: "Tarkibida Katalaza saqlovchi organoid?",
      a: [
        "Lizosoma",
        "Proteasoma",
        "Peroksisoma",
        "Ribosoma",
        "Donador endoplazmatik to’r",
      ],
      correct: 2,
    },
    {
      q: "Peroksisomalarga tegishli to’g’ri fikrni toping?",
      a: [
        "Faqat prokariotik hujayralarda mavjud",
        "Mikroperoksisomalar yoki peroksisomal retikulum deb nomlanuvchi o'zaro bog'langan kanalchalar tarmog’idan iborat",
        "Ham prokariot va ham eukariot hujayralarda mavjud",
        "2 qavat membrana bilan o’ralgan, sharsimon organoid",
        "Hujayraning hazm sistemasi deb ham nomlanadi",
      ],
      correct: 1,
    },
    {
      q: "Peroksisomadagi fermentlar ta’sirida….?",
      a: [
        "Glukozaning parchalanishi sodir bo’ladi",
        "Elektron transport zanjiri yo’lidagi suv hosil bo’ladi",
        "Alfa oksidlanish amalga oshadi",
        "Apoptoz jarayoni aktivlashadi",
        "Katta miqdorda ATF hosil bo’ladi",
      ],
      correct: 2,
    },
    {
      q: "Zellveger sindromiga oid to’g’ri fikrni toping?",
      a: [
        "Lizosoma zahirasi kasalliklariga misol bo’ladi",
        "X-xromosomaga birikkan holda irsiylanadi",
        "Dermatit, Giperpigmentatsiya, Diareya kuzatiladi",
        "Peroksisomal kasalliklarga misol bo’ladi",
        "Katalaza fermentining aktivligi oshib ketadi",
      ],
      correct: 3,
    },
  ],
  m7: [
    {
      q: "Qaysi zarralar birlashib fermentativ faol 26S proteasomani hosil qiladi?",
      a: [
        "Proteolitik yadro va boshqaruvchi zarralar",
        "Katalitik fermentlar va ingibirlovchi zarralar",
        "Faqat proteolitik yadro",
        "Birlamchi va ikkilamchi Peroksisoma",
        "Katalitik fermentlar va mikrofilamentlar",
      ],
      correct: 0,
    },
    {
      q: "Proteasomaning asosiy vazifasi nima?",
      a: [
        "Organizmni erkin Vodorod Peroksiddan himoyalash",
        "Muhim oqsillar sintezini amalga oshirish",
        "Shikastlangan va noto'g'ri sintezlangan oqsillarni parchalash",
        "Glukoneogenezni stimullash",
        "Oqsillar, nuklein kislotalar, uglevodlar va lipidlarni sintez qilish",
      ],
      correct: 2,
    },
    {
      q: "Proteasoma ortiqcha faollanishi natijasida...?",
      a: [
        "Dasturlashtirilgan hujayra o’limi yuzaga keladi",
        "Apoptoz jarayoni aktivlanadi",
        "Noto’g’ri sintezlangan oqsillar parchalanmay qoladi",
        "Hujayralarning to'xtovsiz ko'payishiga va keyinchalik saraton yuzaga kelishiga sabab bo’ladi",
        "Hujayrada DNK 2 hissa ortadi",
      ],
      correct: 3,
    },
    {
      q: "Bortezomib va Karfilzomib hujayra siklining qaysi fazasiga ta’sir qiladi?",
      a: [
        "Sintez fazasini aktivlaydi",
        "G2 dan M ga o’tishini bloklaydi",
        "G1 fazani aktivlaydi",
        "G2 dan M ga o’tishini stimullaydi",
        "Mitozni aktivlaydi",
      ],
      correct: 1,
    },
    {
      q: "Eukariotik hujayralar sitoskeleti tarkibidagi oqsil tolalarining necha xil turi mavjud?",
      a: [
        "4 xil",
        "Faqat mikronaychalardan iborat",
        "2 xil",
        "Mikrofilament va mikronaychalar",
        "3 xil",
      ],
      correct: 4,
    },
    {
      q: "Sitoskelet tarkibidagi 3 xil oqsil tolalarining eng ingichkasi qaysi?",
      a: [
        "Mikrofilamentlar",
        "Mikronaychalar",
        "Oraliq filamentlar",
        "Miozin",
        "Tropomiozin",
      ],
      correct: 0,
    },
    {
      q: "Aktin filamentlarining vazifasi keltirilgan qatorni toping?",
      a: [
        "Hujayraga shakl va rigidlik berish",
        "Intrasellular moddalar transportida qatnashish",
        "Embriogenezda epiteliy hujayralarini embrional naylarga yig’ish",
        "Mitoz jarayonida mitotik ip hosil qilish",
        "Umumiy mexanik tayanch vazifani bajaradi",
      ],
      correct: 2,
    },
    {
      q: "Oraliq filamentlarni hosil qiluvchi oqsillardan eng keng tarqalgan sochlarda, tirnoqda va terida bo'ladigan tolali oqsil qaysi?",
      a: ["Kollagen", "Keratin", "Albumin", "Gammaglobulin", "Tubulin"],
      correct: 1,
    },
    {
      q: "Mikronaycha nay shaklida bo'lib, nay devori qanday oqsillaridan tashkil topgan?",
      a: ["Tubulin", "Aktin", "Keratin", "Troponin", "Miozin"],
      correct: 0,
    },
    {
      q: "Mikronaychalar vazifasi keltirilgan qatorni toping?",
      a: [
        "Membranada joylashgan proteinlarni mustahkam tutib turish",
        "Sitokinezda qisqaruvchi halqa hosil qilish",
        "Mitoz jarayonida mitotik ip hosil qilib, xromosomalarni ikki qutbga tortilishini ta’minlash",
        "Ekstrasellular matriks va hujayra o'rtasida aloqani ta'minlash",
        "Muskul bo’lmagan hujayralar kontrakturasi uchun zarur bo'lgan stress tolalarini hosil qilish",
      ],
      correct: 2,
    },
  ],
  m8: [
    {
      q: "O’z tarkibida ribonuklein kislotalarni saqlovchi, oqsil sintezini amalga oshiruvchi, sitoplazmaning doimiy, membranasiz organoidi?",
      a: [
        "Peroksisoma",
        "Proteasoma",
        "Lizosoma",
        "Ribosoma",
        "Silliq endoplazmatik to’r",
      ],
      correct: 3,
    },
    {
      q: "Ribosomaning tRNKlar uchun qanday nuqtalari bor?",
      a: [
        "Faqat A sayt va P sayt",
        "A sayt, P sayt, E sayt",
        "Faqat E sayt va P sayt",
        "tRNKlar uchun nuqtalar mavjud emas",
        "iRNKlar uchun A sayt va E sayt",
      ],
      correct: 1,
    },
    {
      q: "Ribosomani taxminan uchdan ikki qismini nima tashkil qiladi?",
      a: ["Oqsillar", "rRNK", "tRNK", "iRNK", "Oqsillar va rRNK"],
      correct: 1,
    },
    {
      q: 'Hujayraning "miyasi" deb ta’riflangan organoidga tegishli fikrni toping?',
      a: [
        "Genetik kod saqlaydi, 1 qavat membranaga ega",
        "Prokariotlarning hujayrasida mavjud",
        "Faqat eukariotik hujayralarda bo’ladigan, membranasiz organoid",
        "Genetik kod saqlaydi, prokariotlarda ham uchraydi",
        "Ikki qavat membranaga ega",
      ],
      correct: 4,
    },
    {
      q: "Xromatin yadrocha bilan birgalikda qanday tuzilma ichida saqlanadi?",
      a: [
        "Yadro membranalarida",
        "Sitozolda",
        "Nukleoplazmada",
        "Yadroning ichki membranasida",
        "Yadroning tashqi membranasida",
      ],
      correct: 2,
    },
    {
      q: "To’g’ri fikrni toping?",
      a: [
        "Yadro membranasidagi fosfolipidlarning gidrofil dumchalari ichkariga, Nukleoplazmaga yo'nalgan holatda joylashadi",
        "Yadro membranalarining har biri ikki qavatli fosfolipiddan tashkil topgan",
        "DNK tarkibida A, G, S, T, U mavjud",
        "Ma’lum yog’ kislotalari sinteziga javobgar bo’lgan nukleotidlar qatori - genom deyiladi",
        "Yadro qobig’i orasida bo'shliq mavjud bo'lib, u to'g'ridan-to'g'ri Golji bilan tutashgan",
      ],
      correct: 1,
    },
    {
      q: "Xromatinni nima xosil qiladi?",
      a: [
        "DNK va Giston",
        "Nukleosoma va DNK",
        "Xromosoma",
        "Nukleosoma va Giston",
        "Bir necha Gistonlar",
      ],
      correct: 0,
    },
    {
      q: "Aneuploidiya quyidagi qaysi kasalliklarga sabab bo’lishi mumkin?",
      a: [
        "Qandli diabet",
        "Kasallikka sabab bo’lmaydi",
        "Klaynfelter sindromi",
        "Zellveger sindromi",
        "Daun sindromi va qandli diabet",
      ],
      correct: 2,
    },
  ],
  m9: [
    {
      q: "Signal molekulalari umumiy nom bilan qanday nomlanadi?",
      a: [
        "Retseptor",
        "Fermentlar",
        "Ikkilamchi messenjer",
        "Gen",
        "Ligandlar",
      ],
      correct: 4,
    },
    {
      q: "Hujayrada o’zaro signal almashinuvi asosan necha xil turda bo’ladi?",
      a: ["2 xil", "4 xil", "5 xil", "3 xil", "Faqat endokrin"],
      correct: 3,
    },
    {
      q: "Hujayra o'zi ishlab chigargan ligand orqali o'zidagi retseptorga ta'sir ko'rsatishi bu...?",
      a: [
        "Endokrin signal",
        "Parakrin va Autokrin signal",
        "Autokrin signal",
        "Parakrin signal",
        "Autokrin va endokrin signal",
      ],
      correct: 2,
    },
    {
      q: "Parakrin signalga oid to’g’ri fikrni toping?",
      a: [
        "Embrional paytda hujayralarga to'g'ri yo'nalishda ixtisoslashishga yordam beradi",
        "Hujayralarning uzoq masofalarga signal yuborishida muhim",
        "Hujayralarning nisbatan qisqa masofalar orqali o'zaro signal uzatilishini ta’minlaydi",
        "Parakrin signal uzatilishi transport tarmoq sifatida qon aylanish tizimidan foydalanadi",
        "Hujayra o’ziga o’zi signal jo’natadi",
      ],
      correct: 2,
    },
    {
      q: "Endokrin signalga oid to’g’ri fikrni toping?",
      a: [
        "Signal uzatilishi transport tarmoq sifatida qon aylanish tizimidan foydalanadi",
        "IL-1, IL-6 endokrin ligandlarga misol bo’ladi",
        "Asosan yallig’lanish vaqtida aktivlanadi",
        "Embrional rivojlanishda juda muhim ahamiyatga ega",
        "Hujayralar uzoq masofaga va o’ziga signal beradi",
      ],
      correct: 0,
    },
  ],
  m10: [
    {
      q: "Ma'lum bir ionning hujayra membranasi orqali harakatini ta'minlovchi integral membrana proteinlari bu...?",
      a: [
        "Retseptorlar",
        "Nishon",
        "Ligand darvozali ion kanallar",
        "Signal transduktorlar",
        "Ikkilamchi messenjerlar",
      ],
      correct: 2,
    },
    {
      q: "Metabotrop retseptorlarni G proteinli deyilishiga sabab nima?",
      a: [
        "sAMF ni aktivlaydi",
        "sGMF ni aktivlaydi",
        "G-guanin nukleotidini bog'lovchi proteinlardan tuzilgan",
        "Fosfatidilinozitol bilan ishlaydi",
        "ATF va GTF energiyasidan foydalanadi",
      ],
      correct: 2,
    },
    {
      q: "Ko’p xollarda ilon zahari qaysi retseptorlarni bloklaydi?",
      a: [
        "Adrenergik retseptorlar",
        "Asetilxolin retseptorlari",
        "Enzimatik retseptorlar",
        "Barcha ekstrasellular retseptorlar",
        "Intrasellular retseptorlar",
      ],
      correct: 1,
    },
    {
      q: "Gs retseptorlarini zararlovchi toksin?",
      a: [
        "Botulotoksin",
        "Ilon zahari",
        "Xolera ekzotoksini",
        "Tetanus toksini",
        "Shiga toksini",
      ],
      correct: 2,
    },
    {
      q: "Gs retseptordagi alfa subbirlik aktivlanishi natijasida...?",
      a: [
        "Fosfatidilinozitol aktivlanadi",
        "Adenilat siklaza bloklanadi",
        "Siklik GMF miqdori kamayadi",
        "Siklik AMF miqdori ortadi",
        "PLC faollashadi",
      ],
      correct: 3,
    },
    {
      q: "PIP2 parchalanishi natijasida qanday tuzilmalar xosil bo’ladi?",
      a: [
        "IP3 va sAMF",
        "DAG va PLC",
        "PKC va DAG",
        "sGMP va Adenilat siklaza",
        "IP3 va DAG",
      ],
      correct: 4,
    },
    {
      q: "Fosfolipaza C aktivlanishi natijasida hujayrada qanday o’zgarish kuzatiladi?",
      a: [
        "Miotsitlarda qisqarish jarayoni",
        "Sitozolda kalsiy ionining kamayishi",
        "Sarkoplazmatik retikulumda kalsiy miqdori ortishi",
        "Protein Kinaza C bloklanishi",
        "DAG miqdori kamayishi",
      ],
      correct: 0,
    },
    {
      q: "Tirozinkinazali retseptorlar qanday retseptor turiga kiradi?",
      a: [
        "Metabotrop Gs",
        "Instrasellular retseptorlar",
        "Metabotrop Gq",
        "Enzimatik retseptorlar",
        "Metabotrop Gi",
      ],
      correct: 3,
    },
  ],
  m11: [
    {
      q: "Hujayra sitoplazmasida va yadrosida joylashgan retseptorlar turi?",
      a: [
        "Metabotrop Gq",
        "Intrasellular retseptorlar",
        "Enzimatik retseptorlar",
        "Metabotrop Gi",
        "Barcha ekstrasellular retseptorlar",
      ],
      correct: 1,
    },
    {
      q: "Intrasellular retseptorlarga ta’sir qiluvchi moddalar keltirilgan javob qaysi?",
      a: [
        "D vitamini",
        "Asetilxolin",
        "Adrenalin",
        "B guruh vitaminlar",
        "Norepinefrin",
      ],
      correct: 0,
    },
    {
      q: "Intrasellular retseptorlarga oid to’g’ri fikrni toping?",
      a: [
        "Lipofil va gidrofil tabiatli moddalar ta’sirida qo’zg’aladi",
        "Yadro va hujayra membranasida joylashadi",
        "Aldesteron retseptori misol bo’ladi",
        "Alfa va beta-gamma subbirlikdan iborat",
        "sGMF va sAMF bilan ishlaydi",
      ],
      correct: 2,
    },
    {
      q: "Yadro retseptorlari asosan nechta qismdan iborat?",
      a: [
        "2 ta: Ligand biriktiruvchi va ingibirlovchi qism",
        "1 ta: DNK biriktiruvchi qism",
        "3 ta: Ligand biriktiruvchi, DNK bloklovchi, transkripsiya regulyatsiya qiluvchi",
        "3 ta: Ligand biriktiruvchi, DNK biriktiruvchi, transkripsiya regulyatsiya qiluvchi",
        "2 ta: Ligand va DNK biriktiruvchi qism",
      ],
      correct: 3,
    },
    {
      q: "Kortizol retseptorlariga oid to’g’ri fikrni toping?",
      a: [
        "Hujayra membranasida joylashgan",
        "Ligand biriktiruvchi, DNK biriktiruvchi, transkripsiya regulyatsiya qiluvchi, ingibirlovchi qismlardan iborat",
        "Gq tipda ishlaydi",
        "Enzimatik retseptorlarga misol bo’ladi",
        "Gidrofil tabiatli moddalar ta’sirida aktivlanadi",
      ],
      correct: 1,
    },
  ],
  m12: [
    {
      q: "Eukariotik hujayralarda hujayra sikli qanday bosqichlardan iborat?",
      a: [
        "Interfaza va G2",
        "Sintez fazasi va Mitoz",
        "Interfaza va Mitoz",
        "Bo’linishgacha tayyorgarlik va Interfaza",
        "Interfaza va Sintez",
      ],
      correct: 2,
    },
    {
      q: "Interfaza oid to’g’ri fikrni toping?",
      a: [
        "Asosan 2 ta fazadan iborat",
        "Telofaza-interfazaning bir qismi",
        "Sitokinez jarayonini o’z ichiga oladi",
        "DNK dan nusxa ko’paytiriladi",
        "Interfazadan so’ng mitozning metafaza davri boshlanadi",
      ],
      correct: 3,
    },
    {
      q: "G2 fazada qanday jarayon amalga oshiriladi?",
      a: [
        "Hujayra ko’proq o'sib kattalashadi",
        "DNK ning to'liq nusxasini sintez qilinadi",
        "Organellalarining nusxalarini hosil qilinadi, birinchi bosqich hisoblanadi",
        "Bu fazadan so’ng Sintez davri boshlanadi",
        "Sitokinez jarayoni tarkibiga kiradi",
      ],
      correct: 0,
    },
    {
      q: "Sentrosomaning ikki hissa ko’payishi qaysi fazada bo’ladi?",
      a: ["Metafaza", "Profaza", "Sintez", "G1 faza", "Mitotik faza"],
      correct: 2,
    },
    {
      q: "Mitotik fazada qanday jarayonlar amalga oshadi?",
      a: [
        "Mitoz va Sitokinez",
        "Mitoz va Sintez",
        "Interfaza va Mitoz",
        "G1, S, G2 faza",
        "Interfaza, Mitoz, Sitokinez",
      ],
      correct: 0,
    },
    {
      q: "Telofaza davrida qanday jarayon amalga oshadi?",
      a: [
        "Hujayra tarkibidagi eski organoidlar parchalanadi",
        "Xromosomalar spirallasha boshlaydi",
        "Yadro qobig'i parchalanadi",
        "Bo’linish urchuqlari parchaladi",
        "Juft xromosomalarning har biri qarama-qarshi hujayra qutblariga tortiladi",
      ],
      correct: 3,
    },
    {
      q: "Profaza davrida qanday jarayon amalga oshadi?",
      a: [
        "Bo’linish urchug’i barcha xromosomalarni o'ziga biriktirib, hujayra markaziga to'playdi",
        "Hujayra sitoplazmasi ikkiga bo'linadi",
        "Yadro qobig'i qayta shakllanadi",
        "Xromosomalar ikki qutbga tarqaladi",
        "Yadrochalar parchalanadi",
      ],
      correct: 4,
    },
    {
      q: "Anafaza davrida qanday o’zgarishlar bo’ladi?",
      a: [
        "Xromosomaning ikki qiz xromatidalari bir-biridan ajraladi",
        "Hujayra tarkibidagi eski organoidlar parchalanadi",
        "Xromosomadagi kinetoxor oqsil urchuqning qarama-qarshi ikkala qutbidagi mikronaychalarga to'liq birikadi",
        "Yadro qobig’i parchalanadi",
        "Yadrochalar yo’qolib, hujayra bo’linishga tayyor xolga o’tadi",
      ],
      correct: 0,
    },
  ],
  m13: [
    {
      q: "Tekshirish nuqtalari (checkpointlar) ning asosiylari...?",
      a: [
        "G1 /S o'tish qismida G2 nazorat",
        "G2 /M o'tish qismida G1 nazorati",
        "Metafazadan anafazaga o'tishda urchuq nazorati",
        "S /M o’tish qismida G1 nazorati",
        "Profazadan anafazaga o’tishda urchuq nazorati",
      ],
      correct: 2,
    },
    {
      q: "G2 nazorat nuqtasiga tegishli javobni tanlang?",
      a: [
        "DNK ning replikatsiya bo'lishidan avvalgi soni va bir butunligi tekshiriladi",
        "DNK replikatsiyasini nazorat qilinadi",
        "Qiz xromatidalarning urchuq mikronaychalariga birikkanligini tekshiradi",
        "Bu fazada tekshirilgan hujayra S fazaga kiradi",
        "Metofazani nazorat qiladi",
      ],
      correct: 1,
    },
    {
      q: "Hujayradagi E6 proteini qaysi jarayonni bloklab turadi?",
      a: ["Spermatogenez", "Mitoz", "Meyoz", "Apoptoz", "Interfaza"],
      correct: 3,
    },
    {
      q: "Mitoz fazalari qaysi javobda to’g’ri keltirilgan?",
      a: [
        "Sintez, Profaza, Metafaza",
        "G1, Sintez, G2",
        "G1, Profaza, Anafaza",
        "Profaza, Anafaza, Telofaza",
        "Sintez, Anafaza, Telofaza",
      ],
      correct: 3,
    },
    {
      q: "Agar nazorat DNK dagi qandaydir muammo aniqlansa va shikastlangan qismni to'g'rilashning iloji bo’lmasa qanday jarayon amalga oshadi?",
      a: ["Apoptoz", "O’sma jarayoni", "Mitoz", "Meyoz", "Interfaza-sintez"],
      correct: 0,
    },
  ],
  m14_15: [
    {
      q: "Eukariotik organizm hujayralari membranasida elektrik potensial mavjud bo'lib, odatda hujayra ichki tarafi, tashqi tarafiga nisbatan...?",
      a: [
        "Musbat zaryadlanadi",
        "Zaryadlari bir xil bo’ladi",
        "Manfiy zaryadlanadi",
        "Hujayrada ichida musbat ionlar ko’p bo’ladi",
        "Hujayra tashqarisida manfiy ionlar ko’p bo’ladi",
      ],
      correct: 2,
    },
    {
      q: "Hujayra ichidagi eng ko’p kation qaysi?",
      a: ["Natriy", "Xlor", "Fosfor", "Kaliy", "Kalsiy"],
      correct: 3,
    },
    {
      q: "Tiazid diuretiklarni qo’llash natijasida qaysi ion kamayishi, qo’zg’aluvchan to’qimalarda bo’sag’a kuchini kamaytirib, harakat potensiali hosil bo’lishini osonlashtiradi?",
      a: ["Kalsiy", "Kaliy", "Xlor", "Magniy", "Fosfor"],
      correct: 1,
    },
    {
      q: "Hujayra membranasini lipofil tabiatli bo’lishini qaysi moddalar ta’minlaydi?",
      a: [
        "Aktin oqsillari",
        "Tubulin oqsili",
        "Hujayra membaranasi lipofob bo’ladi",
        "Fosfolipidlarning yog’ kislotalari",
        "Polisaxarid qavat",
      ],
      correct: 3,
    },
    {
      q: "Hujayra tashqarisidagi eng ko’p anion qaysi?",
      a: ["Natriy", "Kaliy", "Xlor", "Magniy", "Kalsiy"],
      correct: 2,
    },
  ],
  m16: [
    {
      q: "Nerv sistemasi anatomik va funksional jihatdan qanday turlarga bo’linadi?",
      a: [
        "Simpatik, Parasimpatik",
        "Markaziy, Somatik",
        "Markaziy, Periferik",
        "Avtonom, Somatik",
        "Avtonom va Simpatik",
      ],
      correct: 2,
    },
    {
      q: "Neyronlarni himoya qilish, oziqlantirish funksiyasini qaysi hujayralar bajaradi?",
      a: [
        "Epiteliy hujayralar",
        "Glial hujayralar",
        "Miyelin",
        "Miyelinsiz nerv tolalari",
        "Muskul hujayralari",
      ],
      correct: 1,
    },
    {
      q: "Sinapslar orqali boshqa neyronlardan signallarni qabul qilib oluvchi, hujayra tanasidan o'sib chiqqan kalta o'simtaga o'xshash tola nima deyiladi?",
      a: [
        "Multipolyar neyron",
        "Akson",
        "Pseudounipolyar neyron",
        "Dendrit",
        "Anaksonik neyron",
      ],
      correct: 3,
    },
    {
      q: "Neyronda yagona akson tolasi va 2 tadan kam bo'lmagan dendritlar o'sib chiqgan bo'lsa, qanday neyron deyiladi?",
      a: [
        "Multipolyar neyron",
        "Unipolyar neyron",
        "Bipolyar neyron",
        "Psevdounipolyar neyron",
        "Anaksonik neyron",
      ],
      correct: 0,
    },
    {
      q: "Neyron zararlanishiga nisbatan neyron somasining javob reaksiyasi nima?",
      a: [
        "Aksonal retraksiya",
        "Xromatolizis",
        "Vallerian degeneratsiyasi",
        "Membrana potensiali",
        "Giperpolyarizatsiya",
      ],
      correct: 1,
    },
    {
      q: "Qanday neyronlarda hujayra tanasidan yagona o'simta o'sib chiqadi, lekin o'sib chiqishi bilanoq, bu o'simta bifurkatsiya hosil qilib ikki o'simtaga tarmoqlanadi?",
      a: [
        "Dendrit",
        "Multipolyar neyron",
        "Bipolyar neyron",
        "Psevdounipolyar neyron",
        "Anaksonik neyron",
      ],
      correct: 3,
    },
    {
      q: "Aksonning zararlangan joyidan sinapsgacha bo'lgan qismi parchalanib, so’rilib ketishi nima deyiladi?",
      a: [
        "Vallerian degeneratsiyasi",
        "Aksonal retraksiya",
        "Apoptoz",
        "Xromatolizis",
        "Neyronal regeneratsiya",
      ],
      correct: 0,
    },
    {
      q: "PNS da uchrovchi glial hujayra qaysi?",
      a: [
        "Oligodendrotsitlar",
        "Mikroglial hujayralar",
        "Shvann hujayralari",
        "Astrotsitlar",
        "Dendritlar",
      ],
      correct: 2,
    },
    {
      q: "Miyelinli nerv tolalariga xos xususiyat?",
      a: [
        "Neyronlarni himoya qilish, oziqlantirish",
        "Nerv tolasi o’q silindr, uning ustida aksolemmasi bor",
        "Gomeostazni ta’minlaydi",
        "O’q slindr tuzilishli, qalin",
        "Uzun ipsimon tuzilgan, miyelin tolasi 2 qismdan iborat",
      ],
      correct: 4,
    },
    {
      q: "MNS da uchrovchi glial hujayralar?",
      a: [
        "Yo’ldosh hujayralari",
        "Ependimal hujayralar",
        "Shvann hujayralari",
        "Anaksonik neyron",
        "Unipolyar neyron",
      ],
      correct: 1,
    },
  ],

  m17: [
    {
      q: "Sinapslar orqali nerv impulslarini postsinaptik neyronga o’tkazib beruvchi moddalar nima deyiladi?",
      a: [
        "Vitaminlar",
        "Gormonlar",
        "Neyrotransmitterlar",
        "Minerallar",
        "Ikkilamchi messenjerlar",
      ],
      correct: 2,
    },
    {
      q: "Neyronlar orasida asosan necha xil turdagi sinapslar uchraydi?",
      a: ["5 xil", "2 xil", "4 xil", "3 xil", "7 xil"],
      correct: 3,
    },
    {
      q: "Akso-dendritik sinaps qanday bo’ladi?",
      a: [
        "Bir neyronning aksoni bilan ikkinchi neyronning dendriti o'rtasida bo’ladi",
        "Ikkita akson orasida bo’ladi",
        "Bir neyronning aksoni bilan ikkinchi neyronning tanasi o'rtasida bo’ladi",
        "Ikkita dendrit o’rtasida bo’ladi",
        "Presinaptik neyron va retseptor orasida bo’ladi",
      ],
      correct: 0,
    },
    {
      q: "Sinaps anatomik jihatdan qanday qismlardan iborat?",
      a: [
        "Sinaps bo’shlig’i, retseptor qism",
        "Presinaptik akson terminali, postsinaptik membrana, sinaps bo’shlig’i",
        "Retseptor qism, postsinaptik membrana, sinaps bo’shlig’i",
        "Presinaptik akson terminal, presinaptik neyron",
        "Presinaptik membrana, sinaps bo’shlig’i",
      ],
      correct: 1,
    },
    {
      q: "Qaysi toksin Asetilxolin mediatorini sinaps bo’shlig’iga o’tishini bloklaydi?",
      a: [
        "Ilon zahari",
        "Tetanus toksini",
        "Botulotoksin",
        "Shiga toksini",
        "Xolera toksini",
      ],
      correct: 2,
    },
  ],
  m18: [
    {
      q: "Skelet muskuliga xos xususiyatni belgilang?",
      a: [
        "Hujayralari bir-biri bilan maxsus disksimon tuzilmalar orqali shoxlanib tutashgan",
        "Ko'ndalang chiziqlardan iborat uzun hujayrali",
        "Nisbatan kuchsiz qisqarish xususiyatiga ega",
        "Qisqarish odam ixtiyoriga bog’liq emas",
        "Duksimon hujayralardan iborat",
      ],
      correct: 1,
    },
    {
      q: "Barcha muskullar qisqarishini ta’minlovchi oqsillar qaysi?",
      a: [
        "Tubulin, Miozin",
        "Keratin, Tubulin",
        "Aktin, Miozin",
        "Tubulin, Aktin",
        "Albumin, Aktin",
      ],
      correct: 2,
    },
    {
      q: "Muskul to’qimasini qanday parda o’rab turadi?",
      a: [
        "3 qavat Biriktiruvchi to’qima",
        "3 qavat zich Epiteliy",
        "Miyelin parda",
        "2 qavat zich Biriktiruvchi to’qima",
        "To’r xosil qilib joylashgan biriktiruvchi to’qima",
      ],
      correct: 0,
    },
    {
      q: "Perimiziyning vazifasi nima?",
      a: [
        "Butun muskulni o’rab turish",
        "Har bir muskul tolalari tutamini va alohida-alohida joylashgan individual muskul tolalarini o’rash",
        "Muskulni kislorod bilan ta’minlashda qatnashadigan kapilyarlar uchun himoya",
        "Muskul innervatsiyasida qatnashuvchi retseptorlarni saqlash",
        "Bir tutam muskul tolalarini o’rash",
      ],
      correct: 4,
    },
    {
      q: "Miofibrillalarning filamentlari, miofilamentlar deb nomlanib, ularning necha xil shakli tafovutlanadi?",
      a: ["4 xil", "2 xil", "3 xil", "5 xil", "1 xil"],
      correct: 2,
    },
    {
      q: "Miozin filamentlari uchun xos xususiyatni belgilang?",
      a: [
        "Aktin va boshqa bog'langan oqsillardan (troponin, tropomiozin) iborat bo'ladi",
        "Miozin nomli proteinlardan tashkil topgan",
        "Ingichka shaklda bo’ladi",
        "Elastik filamentlar hisoblanadi",
        "Tarkibida ko’p miqdorda Troponin oqsili bo’ladi",
      ],
      correct: 1,
    },
    {
      q: "Elastik filamentlar qanday nomlanadigan katta hajmli proteinlardan tuzilgan?",
      a: ["Aktin", "Miozin", "Troponin", "Titin", "Tropomiozin"],
      correct: 4,
    },
    {
      q: "Qaysi oqsil muskul tolasi ichidagi aktin iplarini sarkolemmadagi oqsil komplekslari bilan bog’laydi?",
      a: ["Titin", "Tropomiozin", "Tubulin", "Distrofin", "Aktin"],
      correct: 3,
    },
  ],
  m19: [
    {
      q: "Muskul qisqarish vaqtida hujayraga qaysi ion kirishi, aktin filamentidagi troponin oqsilining shakli o'zgarishiga sabab bo'ladi?",
      a: ["Natriy", "Kaliy", "Kalsiy", "Xlor", "Magniy"],
      correct: 2,
    },
    {
      q: "Muskul tolasi bo'shashgan holatda bo'lganida, miozin boshchasida qaysi moddalar mavjud bo’ladi?",
      a: [
        "ATF va kalsiy",
        "ATF va fosfat guruh",
        "Kalsiy va fosfat guruh",
        "ADF va unga bog'langan fosfat qoldig’i",
        "ADF va kalsiy",
      ],
      correct: 3,
    },
    {
      q: "Rabdomioliz xolatida siydikda qanday o’zgarish bo’ladi?",
      a: [
        "Ishqoriyligi kuchayadi",
        "Kislotalilik ortadi",
        "Siydik rangsizlanadi",
        "Urat kristallari miqdori ortadi",
        "Siydik rangi qizaradi",
      ],
      correct: 4,
    },
    {
      q: "H zona qayerda joylashgan?",
      a: [
        "2 ta Z disk orasida",
        "M chiziqning yonida",
        "Z diskni atrofida",
        "Miozinni yo’g’on boshchasida",
        "Troponin C qismida",
      ],
      correct: 0,
    },
    {
      q: "Z chiziqda qaysi oqsil uchraydi?",
      a: ["Tubulin", "Keratin", "Desmin", "Distrofin", "Albumin"],
      correct: 2,
    },
  ],
  m20: [
    {
      q: "Silliq muskulga xos xususiyatni belgilang?",
      a: [
        "Odam ixtiyoriga bog’liq xolda ishlaydi",
        "Hujayralari bir-biri bilan maxsus disksimon tuzilmalar orqali shoxlanib tutashgan",
        "Duksimon hujayralar bo'lib, qisqarishi odam ixtiyorga bog’liq emas",
        "Uzun va ko’ndalang chiziqlarga ega",
        "Ko’ndalang targ’il muskul deb ham yuritiladi",
      ],
      correct: 2,
    },
    {
      q: "Silliq muskul hujayra yuzasidagi qaysi tuzilma kalsiy ionlarining ajralishini boshqaruvchi ko'p sonli ion kanallarini saqlaydi?",
      a: [
        "Plazmolemma",
        "Kaveola",
        "Sarkolemma",
        "Sarkoplazmatik retikulum",
        "Zich tanachalar",
      ],
      correct: 1,
    },
    {
      q: "Odam organizmida necha xil silliq muskul tiplari uchraydi?",
      a: ["3 xil", "4 xil", "2 xil", "5 xil", "Faqat bir turi mavjud"],
      correct: 2,
    },
    {
      q: "Ko’p motoneyronli silliq muskulga tegishli fikrni toping?",
      a: [
        "Yagona neyrondan iborat",
        "Bir hujayradagi qo’zg’alish atrofga neksuslar orqali tarqaladi",
        "Bitta motoneyron tolasi orqali innervatsiya qiladi",
        "Hujayralari bir-biri bilan neksuslar orqali bog’lanmagan bo’ladi",
        "Hujayralari birgalikda qisqaradi",
      ],
      correct: 3,
    },
    {
      q: "Single unit (bir motoneyronli) muskullarga misol?",
      a: [
        "Siliar muskul",
        "Tukni ko’taruvchi muskul",
        "Son mushaklari",
        "Vas deferens",
        "Siydik pufagidagi muskul",
      ],
      correct: 4,
    },
    {
      q: "Kalsiy-kalmodulin kompleksida Kalmodulin va Kalsiy qanday nisbatda bo’ladi?",
      a: ["4:1", "1:3", "1:4", "2:2", "1:1"],
      correct: 2,
    },
    {
      q: "NO diffuz yo'l bilan silliq muskul hujayrasi ichiga o’tganda, qanday o’zgarish yuzaga kelishi mumkin?",
      a: [
        "Kontraktura",
        "Adenilat siklaza aktivlanishi",
        "sGMF miqdori kamayishi",
        "Guanilat siklaza aktivlanishi",
        "Protein kinaza G bloklanishi",
      ],
      correct: 3,
    },
    {
      q: "Qaysi sindromda butun tanadagi silliq muskullar disfunksiyasi bo’lib, tug’ma qo’zg’almas kengaygan ko’z qorachig’i kabi belgilar kuzatilishi mumkin?",
      a: [
        "Multisystem smooth muscle dysfunction",
        "Daun sindromi",
        "Turner sindromi",
        "Zellveger",
        "Klaynfelter",
      ],
      correct: 0,
    },
  ],
  m21: [
    {
      q: "Ekstrasellular matriks tarkibida uchraydigan protein tolalarining asosiy necha turi mavjud?",
      a: ["2 xil", "3 xil", "Faqat Retikular tola", "Faqat Kollagen", "5 xil"],
      correct: 1,
    },
    {
      q: "Kollagen proteinlari qaysi hujayralar tomonidan hosil qilinadi?",
      a: ["Epiteliy", "Muskul", "Nerv", "Fibroblast", "Osteoblast"],
      correct: 3,
    },
    {
      q: "I tip kollagenga oid to’g’ri fikrni toping?",
      a: [
        "Eozinofilga o'xshash to’plamlar hosil qilib joylashadi",
        "Tolalar tarmog'ini hosil qilib, bazal membranada joylashadi",
        "Ko'z gavharida, nefron koptokchasida bo’ladi",
        "Gialin tog'ay matriksida ko'p miqdorda topiladi",
        "Kollagen turlarini eng kam miqdorini tashkil qiladi",
      ],
      correct: 0,
    },
    {
      q: "I tip kollagen asosan qayerlarda ko’proq bo’ladi?",
      a: [
        "Ko'z gavharida, nefron koptokchasida",
        "Gematopoetik organlarda",
        "Ko'zning muguz pardasida va sklerada",
        "Taloq, limfa tuguni",
        "Gialin tog’ay matriksida",
      ],
      correct: 2,
    },
    {
      q: "II tip kollagenni eng ko’p uchrash joylari?",
      a: [
        "Ko'zning muguz pardasida va sklerada",
        "Umurtqalararo disklarda va ko'zning shishasimon tanasida",
        "Suyak ko’migi, taloq",
        "Ko'z gavharida, nefron koptokchasida",
        "Terida va qon tomir devorida",
      ],
      correct: 1,
    },
    {
      q: "Kollagen, birlamchi struktura holatida aynan qaysi hujayra ichida hosil qilinadi?",
      a: ["Fibroblast", "Epiteliy", "Osteoblast", "Osteoklast", "Muskul"],
      correct: 0,
    },
    {
      q: "Prolin va Lizinni gidroksillanish reaksiyasida kofaktor sifatida ishtirok etuvchi element?",
      a: ["Zn", "Cu", "Fe", "Mg", "Ca"],
      correct: 2,
    },
    {
      q: "Prolin va Lizinni gidroksillanish reaksiyasida kofaktor sifatida ishtirok etuvchi vitamin?",
      a: [
        "Piridoksal fosfat",
        "Foliy kislota",
        "Vitamin B3",
        "Vitamin C",
        "Vitamin D",
      ],
      correct: 3,
    },
    {
      q: "Kollagen sintezidagi Lizil oksidazaga kofaktorlik qiluvchi element?",
      a: ["Fe", "Cu", "Zn", "Cl", "Mg"],
      correct: 1,
    },
  ],
  m22: [
    {
      q: "COL1A1 va COL1A2 genlaridagi mutatsiya hisobiga yuzaga keladigan kasallik?",
      a: [
        "Elers-Danlos sindrom",
        "Daun sindrom",
        "Osteogenesis Imperfecta (nomukammal suyak shakllanishi)",
        "Vaskulyar Elers-Danlos sindrom",
        "Singa",
      ],
      correct: 2,
    },
    {
      q: "Osteogenesis imperfecta kasalligida nuqson asosan nimada bo’ladi?",
      a: [
        "IV tip kollagen sintezida",
        "II tip kollagen sintezida",
        "Prokollagen oqsilining uchtalik spiral (tripple helix) holatga o'tishida",
        "III tip kollagen sintezida",
        "IV va II tip kollagen sintezida",
      ],
      correct: 2,
    },
    {
      q: "V tipdagi kollagen yetishmovchiligi terining anomal cho’ziluvchanligiga sabab bo’luvchi kasallik?",
      a: [
        "Klassik Elers-Danlos sindromi",
        "Vaskulyar Elers-Danlos sindromi",
        "Singa",
        "Daun sindromi",
        "Zellveger sindromi",
      ],
      correct: 0,
    },
    {
      q: "Vaskulyar Elers-Danlos sindromi asosan qaysi tipdagi kollagen sintezi nuqsoni hisobiga yuzaga keladi?",
      a: ["I tip", "II tip", "III tip", "IV tip", "V tip"],
      correct: 2,
    },
    {
      q: "ATP7A proteini sinteziga javobgar bo’lgan gen mutatsiyasiyasi hisobiga qaysi kasallik yuzaga keladi?",
      a: [
        "Menkes sindromi",
        "Klassik Elers-Danlos sindromi",
        "Vaskulyar Elers-Danlos sindromi",
        "Singa",
        "Osteogenesis mperfecta",
      ],
      correct: 0,
    },
    {
      q: "Qaysi element yetishmovchiligi kollagen tolasining yaxlit chambarchas bog’langan (cross-linked) holatiga kelmasligiga sabab bo'ladi?",
      a: ["Fe", "Cu", "Zn", "Mg", "Ca"],
      correct: 1,
    },
    {
      q: "Singa kasalligida qaysi fermentlarning faolligi kamayib ketadi?",
      a: [
        "Lizil oksidaza",
        "Lizin Gidroksilaza",
        "Prokollagen peptidaza",
        "Prolil oksidaza",
        "Prokollagen gidroksilaza",
      ],
      correct: 1,
    },
    {
      q: ",,Floppy baby’’ simptomi qaysi kasallikka xos?",
      a: ["Singa", "Daun", "Menkes", "Elers-Danlos", "Osteogenesis imperfecta"],
      correct: 2,
    },
  ],
  m23: [
    {
      q: "Hujayrada sintezlangan tropoelastin ekstrasellular matriksda nima bilan zanjir hosil qilib birikadi?",
      a: ["Kollagen", "Prokollagen", "Fibrillin", "Bir-biri bilan", "Prolin"],
      correct: 2,
    },
    {
      q: "Tropoelastin ekstrasellular matriksda fibrillin bilan zanjir hosil qilib birikishini qaysi ferment ta’minlaydi?",
      a: [
        "Lizil oksidaza",
        "Lizin gidroksilaza",
        "Prolin gidroksilaza",
        "Prokollagen peptidaza",
        "Elastaza",
      ],
      correct: 0,
    },
    {
      q: "Qaysi oqsil Elastaza fermenti regulyatsiyasida qatnashadi?",
      a: ["Prolin", "Tubulin", "Tropomiozin", "Alfa1-Antitripsin", "Tubulin"],
      correct: 3,
    },
    {
      q: "Elastaza fermentining vazifasi nima?",
      a: [
        "IV tip kollagen sintezida qatnashadi",
        "Me'yoridan ortiq birikkan tropoelastin va fibrillinlarni ajratadi",
        "Tropoelastinlarni xosil qiladi",
        "Tropoelastin va fibrillinni o’zaro bog’laydi",
        "Elastinni gidroksillanishini ta’minlaydi",
      ],
      correct: 1,
    },
    {
      q: "Qaysi modda yetishmovchiligi natijasida Elastaza aktivligi ortishi bilan bog’liq kasallik yuzaga keladi?",
      a: ["Alfa1-Antitripsin", "FBN1", "Lizil oksidaza", "TGF-beta", "Prolin"],
      correct: 0,
    },
    {
      q: "Marfan kasalligida qaysi modda aktivligi oshib ketadi?",
      a: [
        "Lizil gidroksilaza",
        "Alfa1-Antitripsin",
        "FBN1",
        "Fibrillin-1",
        "TGF-beta",
      ],
      correct: 4,
    },
    {
      q: 'Quyidagi qaysi kasallikda miyadagi Villiziy halqasida "Berri" anevrizmasi hosil bolishi mumkin?',
      a: [
        "Menkes",
        "Elers-Danlos",
        "Marfan",
        "Osteogenesis imperfecta",
        "Daun",
      ],
      correct: 2,
    },
  ],
  m24: [
    {
      q: "Har bir nukleotid qanday qismlardan iborat?",
      a: [
        "Azot asosi, glukoza halqasi",
        "Fosfat guruh, saxaroza halqasi",
        "Azot asosi, fosfat guruh, riboza",
        "Azot asosi, saxaroza halqasi",
        "Fosfat guruh, glukoza halqasi",
      ],
      correct: 2,
    },
    {
      q: "DNK tarkibidagi pirimidin asoslari qaysi?",
      a: [
        "Adenin, Guanin",
        "Sitozin, Timin",
        "Timin, Uratsil",
        "Guanin, Sitozin",
        "Adenin, Timin",
      ],
      correct: 1,
    },
    {
      q: "Xromatin nimalardan iborat?",
      a: [
        "Faqat DNK dan",
        "Bir necha xromosomalardan",
        "DNK va Gistondan",
        "Faqat 4 juft gistondan",
        "DNK va Antitripsin oqsilidan",
      ],
      correct: 2,
    },
    {
      q: "Euxromatinga xos xususiyatni belgilang?",
      a: [
        "DNK kuchli kondensatsiyalangan",
        "Transkripsion jihatdan inaktiv",
        "Yorug’lik mikroskopida aniq ko’rinadi",
        "Metillanish yuqori",
        "Asetillanish yuqori",
      ],
      correct: 4,
    },
    {
      q: "Asetillanish reaksiyasida giston tarkibidagi qaysi aminokislotaning asetil guruhlari qo’shiladi?",
      a: ["Lizin", "Metionin", "Fenilalanin", "Tirozin", "Triptofan"],
      correct: 0,
    },
  ],
  m25: [
    {
      q: "DNK replikatsiyasi nima?",
      a: [
        "Bitta asl DNK molekulasidan o'ziga o'xshash ikkita bir xil DNK replikasining hosil bo’lishi",
        "DNK molekulasini ikkiga bo’linishi",
        "iRNK orqali axborot olish",
        "Transkripsiya jarayoni",
        "iRNK dan rRNK xosil bo’lishi",
      ],
      correct: 0,
    },
    {
      q: "DNK o'rtasidagi vodorod bog’larining uzilib, dupleksning ochilishi, qaysi ferment yordamida amalga oshadi?",
      a: ["Lidaza", "Ligaza", "Helikaza", "Reduktaza", "Polimeraza"],
      correct: 2,
    },
    {
      q: "Helikaza fermenti birinchi ochib bergan DNK dagi joy nima deyiladi?",
      a: [
        "Replikatsiya vilkasi",
        "Replikatsiyaning boshlanish nuqtasi",
        "Replikatsiyaning tugallanish nuqtasi",
        "Helikaza DNK ga ta’sir ko’rsatmaydi",
        "Okazaki fragmentlari",
      ],
      correct: 1,
    },
    {
      q: "Helikaza defitsiti natijasida qaysi sindrom kelib chiqadi?",
      a: ["Menkes", "Elers-Danlos", "Bloom sindromi", "Turner", "Zellveger"],
      correct: 2,
    },
    {
      q: "Qaysi ferment DNK dagi vodorod bog'lari uzilishidan avval (Helikaza fermenti yordamida) DNK chigalini yechib beradi?",
      a: ["Lidaza", "Polimeraza", "DNK ligaza", "Topoizomeraza", "Sintetaza"],
      correct: 3,
    },
  ],
  m26: [
    {
      q: "DNK ning shikastlanish va mutatsiyalarga, shu jumladan, DNK dagi nukleotidlar ketma-ketligi o'zgarishi va strukturaviy o'zgarishlarga moyilligining oshishi bu...?",
      a: [
        "Gen mutatsiyasi",
        "Genom nostabilligi",
        "DNK reparatsiyasi",
        "DNK mutatsiyasi",
        "DNK shikastlanishi",
      ],
      correct: 1,
    },
    {
      q: "Mutagenlar nima?",
      a: [
        "DNK ni shikastlangan qismini tiklovchi agentlar",
        "Ma'lum bir turdagi azot asosida yuzaga kelgan xatolikni aniqlab, uni tuzatishni ta’minlovchi faktorlar",
        "DNK ni shikastlovchi faktorlar",
        "Rekombinatsiyalovchi agentlar",
        "Transkripsiyada qatnashuvchi faktorlar",
      ],
      correct: 2,
    },
    {
      q: "Germline mutatsiyalar…?",
      a: [
        "Jinsiy hujayralarda sodir bo'ladi",
        "Nasldan-naslga o’tmaydi",
        "Somatik to'qimalarida sodir bo’ladi",
        "Otada uchrasa albatta barcha farzandlarda kuzatiladi",
        "Onada uchrasa, barcha farzandlarda kuzatiladi",
      ],
      correct: 0,
    },
    {
      q: "Frameshift mutatsiyaga oid fikrni toping?",
      a: [
        "Silence turi mavjud",
        "DNK zanjiridagi birgina nukleotidning mutatsiyasi hisoblanadi",
        "Ikki va undan ortiq nukleotidlarda sodir bo'ladi",
        "Nonsense turi mavjud",
        "Jami 3 xil turi bor",
      ],
      correct: 2,
    },
    {
      q: "Nuqtali mutatsiyani qanday turlari bor?",
      a: [
        "Somatik, germline",
        "Somatik, nuqtali, noto’g’ri",
        "Germline, silence, nonsense",
        "Silence, missense, nonsense",
        "Point, missense, nonsense",
      ],
      correct: 3,
    },
    {
      q: "Silence (tinch) mutatsiya bu…?",
      a: [
        "Mutatsiya sodir bo’lgandan so’ng, mutatsiyaga uchragan kodon ham mutatsiyaga uchrashdan oldin kodlagan aynan o'sha aminokislotani kodlashi",
        "Mutatsiyaga uchragan kodon, oldingi sog’lom kodondan boshqa aminokislotalarni kodlashi",
        "Ikki va undan ortiq nukleotidlarda mutatsiya sodir bo'lishi",
        "Hosil bo'luvchi oqsil funksiyasiga eng katta salbiy ta'sir ko'rsatadigan mutatsiya",
        "Frameshift mutatsiya tarkibiga kiradi",
      ],
      correct: 0,
    },
    {
      q: "Uzluksiz mutatsiya nima?",
      a: [
        "DNK zanjiridagi birgina nukleotidning mutatsiyasi hisoblanadi",
        "Jinsiy hujayralarda uchraydigan mutatsiya",
        "Stop kodonlar mutatsiyasi",
        "Somatik hujayralar mutatsiya",
        "Germline mutatsiya",
      ],
      correct: 2,
    },
    {
      q: "Genning kodlovchi regionidagi bir yoki bir necha nukleotlarga qo’shimcha nukleotid qo’shilishi nima deyiladi?",
      a: [
        "Deletsiya",
        "Rekombinatsiya",
        "Transkripsiya",
        "Insersiya",
        "Reparatsiya",
      ],
      correct: 3,
    },
  ],
  m27: [
    {
      q: "DNK Reparatsiyasi nima?",
      a: [
        "DNK ni shikastlangan qismini tiklovchi agentlar",
        "Ma'lum bir turdagi DNK da yuzaga kelgan xatolikni aniqlab, uni tuzatishni ta’minlash",
        "DNK ni shikastlovchi faktorlar",
        "Rekombinatsiyalovchi agentlar",
        "Transkripsiyada qatnashuvchi faktorlar",
      ],
      correct: 1,
    },
    {
      q: "Direct repair (bevosita tuzatish) ga oid to’g’ri fikrni toping?",
      a: [
        "DNK shikastlanishiga olib keladigan ayrim kimyoviy reaksiyalar maxsus fermentlar ta'sirida to'xtatish",
        "Ekssizion turi mavjud",
        "Ma'lum bir turdagi azot asosida yuzaga kelgan xatolikni aniqlab, uni tuzatishdan iborat mexanizm hisoblanadi",
        "Nogomologik oxirlarni biriktirishda xromosomaning uzilgan oxirlari shunchaki biriktirib qo'yiladi",
        "Yangi sintez qilingan zanjirdagi mos kelmaydigan nukleotidlar olib tashlanadi",
      ],
      correct: 0,
    },
    {
      q: "Yagona zanjirli reparatsiyani qanday turlari bor?",
      a: [
        "Direct repair (bevosita tuzatish), Ekssizion (kesuvchi)",
        "Ekssizion (kesuvchi), Mismatch repair",
        "Qo’sh zanjirli, Direct repair",
        "Mismatch repair, Direct reapir",
        "Gomologik rekombinatsiya, Mismatch repair",
      ],
      correct: 1,
    },
    {
      q: "Mismatch reparatsiya nima?",
      a: [
        "Ma'lum bir turdagi azot asosida yuzaga kelgan xatolikni aniqlab, uni tuzatishdan iborat mexanizm hisoblanadi",
        "DNK shikastlanishiga olib keladigan ayrim kimyoviy reaksiyalar maxsus fermentlar ta'sirida to'xtatish",
        "Yangi sintez qilingan zanjirdagi mos kelmaydigan nukleotidlar olib tashlab, o'riga mos nukleotidlar hosil qilish",
        "Nogomologik xromosoma oxirlarini biriktirish",
        "Gomologik xromosomalardan shikastlangan DNK ni tiklash uchun foydalanish",
      ],
      correct: 2,
    },
    {
      q: "Qo’sh zanjirli reparatsiya turlari?",
      a: [
        "Gomologik rekombinatsiya, Mismatch repair",
        "Bevosita reparatsiya, ekssizion repair",
        "Ekssizion (kesuvchi), Mismatch repair",
        "Nogomologik oxirlarni biriktirish, Gomologik rekombinatsiya",
        "Bevosita reparatsiya, Yagona zanjirli reparatsiya",
      ],
      correct: 3,
    },
  ],
  m28: [
    {
      q: "Gen nima?",
      a: [
        "Faqat eukariot organizmda mavjud bo’lgan tuzilma",
        "Bir molekula oqsil sinteziga javobgar bo'lgan DNK ning bir bo'lagi",
        "DNK va giston birlashmasi",
        "9 ta Giston yig’indisi",
        "Purin nukleotidlari birligi",
      ],
      correct: 1,
    },
    {
      q: "Genlar tarkibidagi, aminokislotalarni kodlamaydigan qism nima deyiladi?",
      a: ["Enhancer", "Ekzon", "Promoter", "Intron", "Silencer"],
      correct: 3,
    },
    {
      q: "Har bir gen qanday qismlardan iborat bo’ladi?",
      a: [
        "Faqat Ekzon va Intron",
        "Enhancer/Silencer, Promoter, Genning ekzon yoki intron qismi",
        "Faqat Ekzon va Promoter",
        "Markaziy dogma, Promoter",
        "Enhancer/Silencer, Markaziy dogma",
      ],
      correct: 1,
    },
    {
      q: "Genlar tarkibidagi, aminokislotalarni kodlaydigan qism nima deyiladi?",
      a: ["Promoter", "Silencer", "Ekzon", "Intron", "Markaziy dogma"],
      correct: 2,
    },
  ],
  m29: [
    {
      q: "Gen ekspressiyasini regulyatsiya qilishda qaysi faktorlar qatnashadi?",
      a: [
        "Translyatsion, Transkripsion faktorlar",
        "Mediatorlar kompleksi, Translyatsion faktor",
        "Transkripsion faktor, Mediatorlar kompleksi",
        "Mutagen faktorlar",
        "Translyatsion, Transkripsion, Mutagen faktorlar",
      ],
      correct: 2,
    },
    {
      q: "Gen ekspressiyasini kuchaytirishda aktivator regulyator oqsillar genning qaysi qismiga birikadi?",
      a: ["Enhancer", "Ekzon", "Promotor", "Intron", "Silencer"],
      correct: 0,
    },
    {
      q: "RNK polimeraza II va aktivator transkripsion faktorlar genning qaysi qismiga birikadi?",
      a: ["Promoter", "Silencer", "Ekzon", "Intron", "Markaziy dogma"],
      correct: 0,
    },
    {
      q: "Daktinomitsin ta’sirida quyidagilardan qaysi biri bloklanadi?",
      a: [
        "Topoizomeraza",
        "DNK ligaza",
        "RNK polimeraza",
        "Helikaza",
        "Reduktaza",
      ],
      correct: 2,
    },
    {
      q: "Gen ekspressiyasi regulyatsiyasini ingibirlash uchun repressor regulyator oqsillar genning qaysi qismiga birikadi?",
      a: ["Intron", "Promoter", "Ekzon", "Silencer", "Markaziy dogma"],
      correct: 3,
    },
    {
      q: "Genetik kod nima?",
      a: [
        "20 xil aminokislotaning 64 xil nukleotidlar kombinatsiyasi orqali kodlanishi",
        "20 xil aminokislotaning 18 xil nukleotidlar kombinatsiyasi orqali kodlanishi",
        "20 xil aminokislotaning 20 xil nukleotidlar kombinatsiyasi orqali kodlanishi",
        "20 xil aminokislotaning 14 xil nukleotidlar kombinatsiyasi orqali kodlanishi",
        "20 xil aminokislotaning 34 xil nukleotidlar kombinatsiyasi orqali kodlanishi",
      ],
      correct: 0,
    },
    {
      q: "Konservativ mutatsiya nima?",
      a: [
        "Xromosomalar sonini kamayishi",
        "Nukleotidlar soni ortishi",
        "Bir xil funksional aminokislota kodonlarining almashinishi",
        "Xromosomalar sonini ortishi",
        "Xromosomalar tarkibidagi nukleotidlarning o’rin almashinishi",
      ],
      correct: 2,
    },
  ],
  m30: [
    {
      q: "RNK ni DNK ga o’xshashligi keltirilgan javobni tanlang?",
      a: [
        "Tarkibida Riboza mavjudligi",
        "Doimo 1 zanjirli bo’lishi",
        "Pirimidin asoslarining bir xilligi",
        "Purin asoslarining o’xshashligi",
        "Tarkibida Uratsil mavjudligi",
      ],
      correct: 3,
    },
    {
      q: "iRNK ga oid fikrni toping?",
      a: [
        "Translatsiyada ishtirok etadi",
        "Yadrodagi DNKdan sitoplazmadagi ribosomalarga axborot yetkazadi",
        "Ribosomalarning struktur komponenti",
        "Aminokislotalar zanjirini hosil qilishda ishtirok etadi",
        "Ribosomaga aminokislotalarni tashishda ishtirok etadi",
      ],
      correct: 1,
    },
    {
      q: "Splice site mutatsiya nima?",
      a: [
        "Bir xil funksional aminokislota kodonlarining o’rin almashishi",
        "Xromosoma tarkibidagi nukleotidlar o’rnini almashinishi",
        "Splicing jarayonida intron va ekzonlar birikkan joydagi mutatsiya",
        "Xromosomalardagi nukleotidlar soni ortishi",
        "Xromosomani ma’lum qismini 180 gradusga o’zgarishi",
      ],
      correct: 2,
    },
    {
      q: "snRNA ga tegishli fikrni toping?",
      a: [
        "Yadrochadagi kodlamaydigan RNK",
        "Yadrodagi kodlamaydigan RNK",
        "Aminokislotalar zanjirini hosil qilishda ishtirok etadi",
        "Translatsiyada ishtirok etadi",
        "Yadrodagi DNKdan sitoplazmadagi ribosomalarga axborot yetkazadi",
      ],
      correct: 1,
    },
    {
      q: "snoRNA ga tegishli fikrni toping?",
      a: [
        "Spliceosome’ni komponenti",
        "pre-mRNA ning splicing bo’lishiga majburlaydi",
        "RNK ni o’zgarishida ishtirok etadi",
        "Yadrodagi kodlamaydigan RNK",
        "Ikki spiralli segmentlarga ega",
      ],
      correct: 2,
    },
  ],
  m31: [
    {
      q: "Transkripsiya nima?",
      a: [
        "Nukleotidlarni aminokislotalarga muvofiqlashtirish jarayoni",
        "DNK dagi axborotni iRNK ga ko’chirilishi",
        "Birlamchi oqsillar hosil bo’lishi",
        "rRNK va tRNK ishtirok etadigan jarayon",
        "iRNK dagi irsiy axborotni polipeptid ketma-ketligiga o’tkizish",
      ],
      correct: 1,
    },
    {
      q: "Gen transkripsiyasi nechta bosqichdan iborat?",
      a: ["3 ta", "5 ta", "2 ta", "4 ta", "Bir bosqichli jarayon"],
      correct: 0,
    },
    {
      q: "Transkripsiyaning elongatsiya bosqichiga tegishli fikrni toping?",
      a: [
        "Bu bosqichda dastlab, transkripsion faktorlar genning promotor nuqtasiga kelib o'rnashadi",
        "RNK polimeraza fermenti DNK qo'sh zanjiri orasidagi vodorod bog’larni uzadi",
        "DNK ning ikkinchi kodlanmaydigan zanjirini \"o'qish\" davomida polimeraza komplimentar nukleotidlardan 5'-3' yo'nalishida RNK molekulasini sintezlaydi",
        "DNK zanjiridagi terminator deb nomlangan nukleotidlar ketma-ketligi i-RNK sintezi tugaganini bildiradi",
        "RNK polimeraza fermenti DNK spiralidan ajralib chiqadi",
      ],
      correct: 2,
    },
    {
      q: "snRNPs larga nisbatan antitanalar sintezlanib qolishi qaysi holatda kuzatiladi?",
      a: [
        "Zellveger sindromi",
        "Elers-Danlos sindromi",
        "SLE (Sistemali Qizil Yuguruk)",
        "Marfan",
        "Daun sindromi",
      ],
      correct: 2,
    },
    {
      q: "Transkripsiyaning terminatsiya bosqichiga tegishli fikrni toping?",
      a: [
        "DNK zanjiridagi terminator deb nomlangan nukleotidlar ketma-ketligi i-RNK sintezi tugaganini bildiradi",
        "Bu bosqichda dastlab, transkripsion faktorlar genning promotor nuqtasiga kelib o'rnashadi",
        "RNK polimeraza fermenti DNK qo'sh zanjiri orasidagi vodorod bog’larni uzadi",
        "DNK ning ikkinchi kodlanmaydigan zanjirini \"o'qish\" davomida polimeraza komplimentar nukleotidlardan 5'-3' yo'nalishida RNK molekulasini sintezlaydi",
        "Genning promotor qismiga polimeraza fermenti kelib joylashgandan so'ng preinitsiatsiya kompleksi hosil bo'ladi",
      ],
      correct: 0,
    },
    {
      q: "Eukariot organizm hujayralarida kechuvchi transkripsiyaning yakuniy mahsuloti nima deyiladi?",
      a: ["snRNPs", "rRNK", "tRNK", "hnRNA", "DNK"],
      correct: 3,
    },
    {
      q: "Post transkripsion modifikatsiya qanday jarayonlardan iborat?",
      a: [
        "Capping, Initsiatsiya",
        "Elongatsiya, Initsiatsiya, Capping",
        "Capping, Poliadenilatsiya, Splicing",
        "Terminatsiya, Initsiatsiya, Capping",
        "Capping, Poliadenilatsiya, Elongatsiya",
      ],
      correct: 2,
    },
    {
      q: "Post transkripsion modifikatsiyaning Capping jarayoniga tegishli fikrni toping?",
      a: [
        "hnRNK ning ikkala uchi ham kimvoviv guruhlar biriktirish yo’li bilan modifikatsiyalanadi",
        "hnRNK ning 3' oxiriga 50 tadan 200 tagacha bo'lgan AMF molekulalari saqlagan nukleozidlar qo'shiladi",
        "A-polimeraza fermenti ishtirok etadi",
        "hnRNK ning intron deb ataluvchi maxsus qismi splaysosoma deb ataluvchi oqsil-RNK kompleksi tomonidan taniladi va olib tashlanadi",
        "i-RNKning 5' tarafidagi uchinchi fosfat guruh A-polimeraza orqali chiqarib tashlanadi",
      ],
      correct: 0,
    },
  ],
  m32: [
    {
      q: "Translyatsiya nima?",
      a: [
        "Yadroda kechadigan jarayon",
        "DNK dagi axborotni iRNK ga ko’chirilishi",
        "Genetik ma'lumotni polipeptidning o'sib borayotgan zanjiridagi aminokislotalarning ma'lum bir ketma-ketligiga aylantirish",
        "Transkripsiyaning bir bosqichi",
        "Transkripsiyadan oldin yuzaga keladigan jarayon",
      ],
      correct: 2,
    },
    {
      q: "Translyatsiya qandan fazalardan iborat?",
      a: [
        "Capping, Initsiatsiya",
        "Elongatsiya, Initsiatsiya, Terminatsiya",
        "Capping, Poliadenilatsiya, Splaysing",
        "Terminatsiya, Initsiatsiya, Capping",
        "Capping, Poliadenilatsiya, Elongatsiya",
      ],
      correct: 1,
    },
    {
      q: "Translyatsiyaning Initsiatsiya fazasiga tegishli fikrni toping?",
      a: [
        "Ribosomaning kichik subbirligiga eukariotik initsiator faktorlar (elF) kelib bog'lanashi",
        "Bitta aminokislotani boshqasi bilan bog'laydigan peptid bog’i paydo bo'lishi",
        "Translyatsiyaning o'rta bosqichi",
        "Polipeptid zanjir xosil bo’lishi",
        "Translyatsiyaning yakuniy bosqichi",
      ],
      correct: 0,
    },
    {
      q: "Terminatsiya bosqichiga tegishli fikrni toping?",
      a: [
        "iRNK zanjirining 5' tarafidagi \"cap\" qismiga ribosoma va undagi initsiator tRNK kelib o'rnashishi",
        "Pre-initsiatsion kompleks hosil bo’lishi",
        "Ribosomaning kichik subbirligiga eukariotik initsiator faktorlar (elF) kelib bog’lanadi",
        "Oxirgi bosqichda yig'ilgan polipeptid zanjiri translyatsiya kompleksidan ajralib chiqishi",
        "Bitta aminokislotani boshqasi bilan bog'laydigan peptid bog'i paydo bo’ladi",
      ],
      correct: 3,
    },
    {
      q: "Glikozillanish, fosforillanish, atsetillanish, ubiquitinatsiya, ADF-ribozillanish, biotinillanish, karboksillanish reaksiyalari quyidagi qaysi bosqichda sodir bo’ladi?",
      a: [
        "Initsiatsiya",
        "Elongatsiya",
        "Terminatsiya",
        "Post-translyatsion modifikatsiya",
        "Transkripsiya bosqichida",
      ],
      correct: 3,
    },
  ],
  m33_34: [
    {
      q: "Genetik lokus nima?",
      a: [
        "Bir molekula oqsil sinteziga javobgar bo'lgan nukleotidlar qatori",
        "Gen yoki genetik marker joylashgan xromosomadagi ma'lum pozitsiya",
        "Bir-biriga o'xshash ikki xil xromosoma",
        "DNK va giston birlashmasi",
        "Ikki xromosomada joylashgan, bir xil funksiya bajaruvchi oqsil sinteziga javobgar bo'lgan genlar yig'indisi",
      ],
      correct: 1,
    },
    {
      q: "Kodominantlik nima?",
      a: [
        "Geterozigota holatida har ikkala gen biri-biridan mustaqil ravishda o'z ta'sirini yuzaga chiqarish holati hisoblanadi",
        "Alleli kelganida o'zidagi effektni to'liqligicha keltirib chiqara olmaydigan effekt tushuniladi",
        "Organizmning barcha tashqi belgi va xossalari yig'indisi",
        "Hujayra yadrosidagi barcha xromosomalaring sifat va miqdor jihatdan yig'indisi",
        "Bir genni boshqa gomologik xromosomada joylashgan alleli ustidan hukmronlik qilishi",
      ],
      correct: 0,
    },
    {
      q: "Penetrantlikning qanday turlari mavjud?",
      a: [
        "Keng va tor",
        "To'liq va noto'liq",
        "Keng va to'liq",
        "Faqat ekspressiv turi mavjud",
        "Metasentrik va akrosentrik",
      ],
      correct: 1,
    },
    {
      q: "Penetrantlik nima?",
      a: [
        "Hujayra yadrosidagi barcha xromosomalarning sifat va miqdor jihatdan yig'indisi",
        "Har xil individlarda ma'lum gen allelining fenotipik namoyon bo’lish darajasi",
        "Organizm guruhlarining har xil individlarida muhit sharoitlariga bog'liq holda ma'lum gen alleli faoliyatining namoyon bo'lish chastotasi",
        "Geterozigota holatida har ikkala gen biri-biridan mustaqil ravishda o'z ta'sirini yuzaga chiqarish holati hisoblanadi",
        "Alleli kelganida o'zidagi effektni to'liqligicha keltirib chiqara olmaydigan effekt tushuniladi",
      ],
      correct: 2,
    },
    {
      q: "Ekspressivlikling qanday turlari mavjud?",
      a: [
        "Keng va tor",
        "To'liq va noto'liq",
        "Keng va to'liq",
        "Faqat ekspressiv turi mavjud",
        "Metasentrik va akrosentrik",
      ],
      correct: 0,
    },
    {
      q: "Organizmning barcha tashqi belgilari yig'indisi nima?",
      a: ["Genotip", "Kariotip", "Ekspressivlik", "Fenotip", "Penetrantlik"],
      correct: 3,
    },
    {
      q: "Har xil individlarda ma'lum gen allelining fenotipik namoyon bo'lish darajasi nima?",
      a: [
        "Panetrantlik",
        "Kodominantlik",
        "Chala dominantlik",
        "Pleotropiya",
        "Ekspressivlik",
      ],
      correct: 4,
    },
    {
      q: "Bir genning ikkita yoki undan ko'p alohida fenotipik xususiyatlarini yuzaga chiqarish xususiyati nima?",
      a: [
        "Ekspressivlik",
        "Chala dominantlik",
        "Anticipation",
        "Pleotropiya",
        "Geteroplaziya",
      ],
      correct: 3,
    },
    {
      q: "Organizmning ma'lum sohasida genetik jihatdan noodatiy turdagi hujayralar mavjud bo’lish holati nima?",
      a: [
        "Anticipation",
        "Pleotropiya",
        "Uniparental disomiya",
        "Gomodisomiya",
        "Mozaitsizm",
      ],
      correct: 4,
    },
    {
      q: "Mitoxondrial DNK (mtDNK) turli ko'rinishlarining bir hujayrada mavjud bo'lish hodisasi nima deyiladi?",
      a: [
        "Allel geterogenlik",
        "Geteroplazmiya",
        "Uniparental disomiya",
        "Genetik geterogenlik",
        "Geterodisomiya",
      ],
      correct: 1,
    },
  ],
  m35: [
    {
      q: "Hujayraning bir bo’linishdan keyingi bo'linishga tayyorgarlik ko'radigan oraliq davri nima deyiladi?",
      a: ["Mitoz", "Meyoz", "Interfaza", "Metafaza", "Sitokinez"],
      correct: 2,
    },
    {
      q: "Interfazaning G2 davriga xos fikrni toping?",
      a: [
        "8 soat davom etadi",
        "Mismatch tuzatish sodir bo'ladi",
        "Ekssizion reparatsiya amalga oshadi",
        "2-5 soat davom etadi",
        "Bu fazadan keyin sintez faza boshlanadi",
      ],
      correct: 3,
    },
    {
      q: "Mitozni anafaza davriga tegishli fikrni toping?",
      a: [
        "Xromosomalar zichlashishi",
        "Mitotik ip shakllanadi",
        "Separaza ta'sirida sentromera erishi",
        "Zichlashgan xromosomalarning yoyilishi",
        "Yadro membranasi shakllanadi",
      ],
      correct: 2,
    },
    {
      q: "Meyozni qaysi fazasi Leptoten, Zigoten, Patixen, Diploten va Diakinez bosqichlaridan iborat?",
      a: ["Profaza I", "Metafaza I", "Anafaza II", "Telofaza I", "Telofaza II"],
      correct: 0,
    },
    {
      q: "Mitoz va Meyoz jarayoning o’xshash hususiyatlari?",
      a: [
        "Krossingover jarayoni bo’lishi",
        "Mitozning anafaza va Meyozning anafaza I bosqichi",
        "Konyugatsiya jarayoni bo’lishi",
        "Gaploid to’plamli hujayralar hosil bo’lishi",
        "Dastlabki bo’linadigan hujayralar diploid to’plamli bo’lishi",
      ],
      correct: 4,
    },
  ],
  m36: [
    {
      q: "Populatsiyadagi genlar to’plami nima deyiladi?",
      a: ["Fenotip", "Kariotip", "Genofond", "Ekspressivlik", "Penetrantlik"],
      correct: 2,
    },
    {
      q: "Populyatsiyadagi genotiplar va allel genlarning uchrash chastotasini aniqlashda qaysi qonundan foydalaniladi?",
      a: [
        "Chala dominantlik",
        "Dominantlik",
        "Kodominantlik",
        "Xardi-Vaynberg qonuni",
        "Mendel qonuni",
      ],
      correct: 3,
    },
    {
      q: "Populyatsiyadagi allel genlarning uchrash tezligi avloddan avlodga o'tganda tasodifiy hodisalar tufayli o’zgarishi nima deyiladi?",
      a: [
        "Genetik geterogenlik",
        "Genlar dreyfi",
        "Geterodisomiya",
        "Allel geterogenlik",
        "Anticipation",
      ],
      correct: 1,
    },
    {
      q: "Quyidagilardan qaysi biri populyatsiya hajmi keskin kichrayganda kuzatiladigan genlar dreyfining yorqin misoli hisoblanadi?",
      a: [
        "Pleotropiya",
        "Mozaitsizm",
        "Bottleneck effekti",
        "Ekspressivlik",
        "Geteroplaziya",
      ],
      correct: 2,
    },
    {
      q: "Quyidagilardan qaysi biri kattaroq populyatsiyaning bir qismi koloniya hosil qilish uchun ajralib chiqqanda kuzatiladi?",
      a: [
        "Mozaitsizm",
        "Founder (asoschi effekti)",
        "Penetrantlik",
        "Kodominantlik",
        "Pleotropiya",
      ],
      correct: 1,
    },
    {
      q: "Xardi-Vaynberg tenglamasi keltirilgan javobni belgilang.",
      a: [
        "p2+2pq+q2=0.1",
        "p2+pq+q2=1",
        "2p+2pq+2q=1",
        "p2+2pq+q2=1",
        "p+2pq+2q=0.5",
      ],
      correct: 3,
    },
    {
      q: "Xardi-Vaynberg qonuni aniq ishlashi uchun qanday talablar mavjud?",
      a: [
        "Juftlanish tasodifiy bo’lmasligi, kichikroq populyatsiyada o’tkazilishi",
        "Allellarda yuqori darajada mutatsiya chastotasi bo’lishi",
        "Immigratsiya bo’lmasligi, populyatsiya yirik bo’lishi",
        "Aholining genetik mutatsiyalarga moyilligi yuqori qismida o’tkazilishi",
        "Yuqori immigratsion ko’rsatkichga ega bo’lishi",
      ],
      correct: 2,
    },
    {
      q: "Xardi-Vaynberg formulasidagi 2pq ning qiymati nimaga teng?",
      a: [
        "Geterozigotalar chastotasi",
        "Gomozigotalar chastotasi",
        "Retsessiv Gomozigotalar chastotasi",
        "Gomozigotalar va Geterozigotalar yig’indisi chastotasi",
        "Dominant Gomozigotalar chastotasi",
      ],
      correct: 0,
    },
  ],
  m37: [
    {
      q: "Angelman sindromi qanday kasalliklar turiga misol bo’ladi?",
      a: [
        "Autosomal dominant",
        "Autosomal retsessiv",
        "Imprinting kasalliklar",
        "Aminokislotalar metabolizmi buzilishi hisobiga yuzaga keladigan kasalliklar",
        "Jinsiy X xromosomaga birikkan kasalliklar",
      ],
      correct: 2,
    },
    {
      q: "15-xromosomada joylashgan U biquitin protein ligaza E3A (UBE3A) geni bilan bog’liq muammolar hisobiga kelib chiqadigan kasallik?",
      a: [
        "Prader Villi sindromi",
        "Zellveger sindromi",
        "Erlers-Danlos sindromi",
        "Angelman sindromi",
        "Marfan sindromi",
      ],
      correct: 3,
    },
    {
      q: "Prader Villi sindromiga tegishli javob keltirilgan qatorni toping?",
      a: [
        "Autosomal dominant kasallik",
        "Onaning UBE3A genidagi mutatsiya sabab bo’ladi",
        "80% bemorlarda epileptik holatlar aniqlanadi",
        "X xromosomaga bog’liq kasallik, ishtaha sust",
        "Kriptorxidizm, gipogonadizm, giperfagiya",
      ],
      correct: 4,
    },
    {
      q: "Qanday kasalliklar natijasida ota va onadan o'tkazilgan ikki allel genning fagatgina birini ekspressiyalanishi boshqa birini esa supressiyalanishi holati kuzatiladi?",
      a: [
        "Jinsiy xromosomalarga bog’liq kasallik",
        "Mitoxondrial kasalliklar",
        "Genomik imprinting kasalliklar",
        "Trinukleotid kasalliklar",
        "Autosomal trisomiyalar",
      ],
      correct: 2,
    },
  ],
  m38: [
    {
      q: "Odamdagi autosomal xromosomalar soni nechta?",
      a: ["46 ta", "2 ta", "44 ta", "44 juft", "2 juft"],
      correct: 2,
    },
    {
      q: "Sistik fibroz kasalligi qanday xolda irsiylanadi?",
      a: [
        "Genomik imprinting kasallik",
        "Jinsiy X xromosomaga birikkan xolda",
        "Autosomal dominant kasallik",
        "Autosomal retsessiv kasallik",
        "Kollagen sinteziga aloqador dominant tipda irsiylanuvchi kasallik",
      ],
      correct: 3,
    },
    {
      q: "Autosomal dominant tipda irsiylanuvchi kasallikka misol?",
      a: [
        "Marfan sindromi",
        "Vilson neoplaziyasi",
        "Tay-Saks kasalligi",
        "Fenilketonuriya",
        "O’roqsimon anemiya",
      ],
      correct: 0,
    },
    {
      q: "Hantington xoreyasi qanday xolda irsiylanadi?",
      a: [
        "Autosomal dominant",
        "Autosomal retsessiv",
        "Jinsiy xromosomalarga birikkan retsessiv",
        "Jinsiy xromosomalarga birikkan dominant",
        "Genomik imprinting kasallik",
      ],
      correct: 0,
    },
    {
      q: "Autosomal retsessiv tipda irsiylanuvchi kasallikka misol?",
      a: [
        "Buyrak polikistozi",
        "Angelman sindromi",
        "Axondroplaziya",
        "Hantington xoreyasi",
        "Vilson neoplaziyasi",
      ],
      correct: 4,
    },
  ],
  m39: [
    {
      q: "Agar ona Gemofiliya bilan kasallangan bo’lsa, o’g’il farzandlarda ushbu kasallikni uchrash ehtimoli qanday?",
      a: [
        "Hammasi gemofiliya bilan kasallangan bo’ladi",
        "Barcha o’g’illar sog’lom bo’ladi",
        "Yarmi kasal, yarmi sog’lom bo’ladi",
        "Barchasi tashuvchi bo’ladi",
        "Ushbu kasallik nasldan-naslga o’tmaydi",
      ],
      correct: 0,
    },
    {
      q: "Fabri kasalligi qanday xolda irsiylanadi?",
      a: [
        "Autosomal retsessiv",
        "X xromosomaga birikkan retsessiv",
        "X xromosomaga birikkan dominant",
        "Autosomal dominant",
        "Imprinting kasallikka misol bo’ladi",
      ],
      correct: 1,
    },
    {
      q: "X xromosomaga birikkan holda irsiylanuvchi dominant kasallikka misol?",
      a: [
        "Dyushen muskul distrofiyasi",
        "Angelman sindromi",
        "Alport sindromi",
        "Hantington xoreyasi",
        "Gemofiliya",
      ],
      correct: 2,
    },
    {
      q: "X xromosomaga birikkan retsessiv tarzda irsiylanuvchi kasalliklarga misollar?",
      a: [
        "Fragile X sindromi, Marfan sindromi",
        "Okular albinizm, Alport sindromi",
        "Vilson neoplaziyasi, Angelman sindromi",
        "Bruton agammaglobulinemiyasi",
        "Tay-Saks kasalligi, Fabri kasalligi",
      ],
      correct: 3,
    },
    {
      q: "X-xromosomadagi FMRI genining o'zgarishi hisobiga kelib chiqadigan kasallik qaysi?",
      a: [
        "Fabri kasalligi",
        "Tay-Saks kasalligi",
        "Bruton agammaglobulinemiyasi",
        "Dyushen kasalligi",
        "Fragile X sindromi",
      ],
      correct: 4,
    },
  ],
  m40: [
    {
      q: "Mitoxondriya o'z DNK siga (mtDNK) ega bo’lib, ba'zan ya’na boshqa nom bilan qanday nomlanishi mumkin?",
      a: [
        "23-Xromosoma",
        "17-Xromosoma",
        "47-Xromosoma",
        "45-Xromosoma",
        "22-Xromosoma",
      ],
      correct: 2,
    },
    {
      q: "Mitoxondrial DNK ni, yadrodagi DNK dan farqi?",
      a: [
        "DNK bir zanjirli bo’ladi",
        "Ma’lum qobiqqa o’ralgan bo’ladi",
        "Genetik axborot saqlamaydi",
        "Tarkibida giston oqsillari bo’lmaydi",
        "Tarkibida giston oqsillari miqdori ko’proq bo’ladi",
      ],
      correct: 3,
    },
    {
      q: "Mitoxondrial kasallikka misol?",
      a: [
        "Prader Villi sindromi",
        "Leber irsiy optik neyropatiyasi",
        "Talassemiya",
        "Fragile X sindromi",
        "Beker muskul distrofiyasi",
      ],
      correct: 1,
    },
    {
      q: "Parkinson kasalligi va Alzgeymer kabi kasalliklarning rivojlanishiga sabab nima?",
      a: [
        "Yadrodagi DNK ga bog’liq retsessiv kasalliklar",
        "X xromosomaga bog’liq dominant kasalliklar",
        "X xromosomaga bog’liq retsessiv kasalliklar",
        "mtDNK dagi mutatsiyalar",
        "Imprinting kasalliklar",
      ],
      correct: 3,
    },
    {
      q: "Leber irsiy optik neyropatiyasiga oid tog’ri fikrni toping?",
      a: [
        "Jinsiy X xromosomaga birikkan holda irsiylanadi, asosan erkaklar kasallanadi",
        "Ikkala ko’zning to'satdan, og'riqsiz ko'r bo'lib qolishi bilan kechadi",
        "Mushak biopsiyasida (qizil-yirtiq mushak tolalari) bo'ladi",
        "FMR1 genining o'zgarishi hisobiga kelib chiqadi",
        "Gemofiliya kasalligi kabi irsiylanadi",
      ],
      correct: 1,
    },
  ],
  m41: [
    {
      q: "Genlarda takrorlanadigan uchta nukleotidli ketma-ketliklarning odatdan ko'ra ko'proq bo’lishi natijasida yuzaga keladigan irsiy kasalliklar qanday nomlanadi?",
      a: [
        "Autosomal retsessiv kasalliklar",
        "Autosomal dominant kasalliklar",
        "Imprinting kasalliklar",
        "Trinukleotid kasalliklar",
        "Jinsiy xromosomalar orqali tashiluvchi kasalliklar",
      ],
      correct: 3,
    },
    {
      q: "HTT genining ekzon qismidagi CAG triplet kengayishi tufayli yuzaga keladigan kasallik?",
      a: [
        "Angelman sindromi",
        "Fragile X sindromi",
        "Marfan sindromi",
        "Vilson neoplaziyasi",
        "Hantington kasalligi",
      ],
      correct: 4,
    },
    {
      q: "Hantington kasalligiga oid to’g’ri fikrni toping?",
      a: [
        "Bosh miyaning bazal gangliyalariga zarar yetkazadi va neyronlarning atrofiyaga uchrashiga sabab bo’ladi",
        "Muskullar kuchsizligi, chuqur pay reflekslarining yo'qolishi va vibratsion sezgining yo'qolishiga olib keladi",
        "i-RNK hosil bo'lish jarayonida DNK segmentining keraksiz sohasida sodir bo’ladi",
        "CTG trinukleotidining takroriy uzayishi DMPK genining 3'UTR hududida sodir bo’ladi",
        "Makro-orxidizmni (katta moyaklar), katta pastki jag' va katta quloqlar yuzaga keladi",
      ],
      correct: 0,
    },
    {
      q: "X xromosomasida FMRI genining 5' taraf promotorida CGG triplet takroriy qaytarilishi tufayli rivojlanadigan kasallik?",
      a: [
        "Marfan sindromi",
        "Dushen",
        "Fragile X sindromi",
        "Fridrix ataksiyasi",
        "Hantington xoreyasi",
      ],
      correct: 2,
    },
    {
      q: "Miotonik distrofiya patogenezinining Hantington kasalligidan farqi?",
      a: [
        "Trinukleotid kasalliklarga misol bo’ladi",
        "Nasldan naslga o’tadi",
        "Imprinting kasalliklarga kiradi",
        "Mushak hujayralari zararlanadi va mutatsiya genning kodlanmagan hududi (dum qismi) da sodir bo’ladi",
        "Autosomal retsessiv kasallik hisoblanadi",
      ],
      correct: 3,
    },
    {
      q: "Trinukleotid takrorlanishi oqsil sinteziga javobgar genning intron qismida, ya'ni i-RNK hosil bo'lish jarayonida DNK segmentining keraksiz sohasida sodir bo’ladigan kasallik?",
      a: [
        "Fridrix ataksiyasi",
        "Angelman sindromi",
        "Miotonik distrofiya 1-tur",
        "Hantington kasalligi",
        "Fragile X sindromi",
      ],
      correct: 0,
    },
  ],
  m42: [
    {
      q: "Hujayrada xromosomalar soni bittaga kamayishi qanday nomlanadi?",
      a: ["Euploid", "Monosomiya", "Diploid", "Gaploid", "Trisomiya"],
      correct: 1,
    },
    {
      q: "18-xromosoma trisomiyasi qaysi kasallikda kuzatiladi?",
      a: [
        "Daun sindromi",
        "Angelman sindromi",
        "Edvards sindromi",
        "Patau sindromi",
        "Turner sindromi",
      ],
      correct: 2,
    },
    {
      q: "Xromosoma bir qismining ajralib, boshga xromosomaga qo'shilishi nima deyiladi?",
      a: [
        "Duplikatsiya",
        "Inversiya",
        "Deletsiya",
        "Transkripsiya",
        "Translokatsiya",
      ],
      correct: 4,
    },
    {
      q: "13-xromosoma trisomiyasi qaysi kasallikda kuzatiladi?",
      a: [
        "Edvars sindromi",
        "Elers-Danlos sindromi",
        "Patau sindromi",
        "Daun sindromi",
        "Turner sindromi",
      ],
      correct: 2,
    },
    {
      q: "Robertson translokatsiyasiga oid to’g’ri fikrni toping?",
      a: [
        "Xomosoma bir qismining yo'qolishi kuzatiladi",
        "Xromosoma qismining 180° gradusga aylanib, qarama-qarshi holatda joylashuvi xolati",
        "Ikkita metasentrik xromosoma o’rtasida kuzatiladi",
        "Xromosomaning bir uzun yelkasi boshqa xromosomaga o'tib, bitta qo'shma xromosomaga aylanadi",
        "Xromosoma bir qismining ortishi kuzatiladi",
      ],
      correct: 3,
    },
    {
      q: "Daun sindromida qaysi xromosomada trisomiya kuzatiladi?",
      a: [
        "18-xromosoma",
        "46-xromosoma",
        "21-xromosoma",
        "13-xromosoma",
        "23-xromosoma",
      ],
      correct: 2,
    },
  ],
  m43: [
    {
      q: "Quyidagi qaysi kasallik ayollarda jinsiy xromosomalardan faqat bitta X xromosomasi borligi yoki ikkinchisida nuqson borligi sababli yuzaga chiqadi?",
      a: [
        "Klaynfelter sindromi",
        "Patau sindromi",
        "Turner sindromi",
        "Triple X sindromi",
        "XYY sindromi",
      ],
      correct: 2,
    },
    {
      q: "Turner sindromiga tegishli fikrni toping?",
      a: [
        "Faqat erkaklarda kuzatiladi",
        "Y xromosomalar soni 2 ta ko’p bo’ladi",
        "Xromosomalar soni 47 ta bo’ladi",
        "Kariotip uchun belgi 45-XO",
        "Ortiqcha X xromosoma bo’ladi",
      ],
      correct: 3,
    },
    {
      q: "Erkaklarda ortiqcha Y xromosomasi borligi hisobiga yuzaga chiquvchi sindrom qaysi?",
      a: [
        "XYY sindromi",
        "Klaynfelter sindromi",
        "Edvards sindromi",
        "Turner sindrom",
        "Triple X sindromi",
      ],
      correct: 0,
    },
    {
      q: "XXY ushbu genotip quyidagi qaysi kasallikda uchraydi?",
      a: [
        "Turner sindromi",
        "Triple X sindromi",
        "Klaynfelter sindromi",
        "Angelman sindromi",
        "Fragile X sindromi",
      ],
      correct: 2,
    },
    {
      q: "Klaynfelter sindromiga tegishli fikrni toping?",
      a: [
        "Faqat ayolarda uchraydi",
        "Erkaklarda ortiqcha Y xromosoma bo’ladi",
        "Nuqsonli tuxumdonlar, estrogenlar miqdorining kamayishi kuzatiladi",
        "Ayollarda ortiqcha X xromosoma bo’ladi",
        "Testosteron darajasi past, moyak atrofiyasi va ginekomastiya holati kuzatiladi",
      ],
      correct: 4,
    },
  ],
};
