window.TEST_QUESTIONS = {
  cellb1: [
    {
      q: "Glucose, galactose, and fructose are:",
      a: [
        "Disaccharides",
        "Polysaccharides",
        "Monosaccharides",
        "Oligosaccharides",
        "Glycoproteins",
      ],
      correct: 2,
    },
    {
      q: "Which of the following consists only of disaccharides?",
      a: [
        "Glucose, fructose, galactose",
        "Maltose, lactose, sucrose",
        "Starch, glycogen, chitin",
        "Ribose, deoxyribose, sucrose",
        "Cellulose, glycogen, starch",
      ],
      correct: 1,
    },
    {
      q: "Which of the following are polysaccharides?",
      a: [
        "Maltose, lactose, sucrose",
        "Glucose, fructose, galactose",
        "Starch, cellulose, glycogen, chitin",
        "Ribose, deoxyribose, glucose",
        "Cholesterol, triglycerides, waxes",
      ],
      correct: 2,
    },
    {
      q: "Amino acids are connected to each other through:",
      a: [
        "Hydrogen bonds",
        "Ionic bonds",
        "Peptide bonds",
        "Glycosidic bonds",
        "Ester bonds",
      ],
      correct: 2,
    },
    {
      q: "The primary structure of a protein contains only:",
      a: [
        "Hydrogen bonds",
        "Peptide bonds",
        "Disulfide bonds",
        "Ionic bonds",
        "Hydrophobic interactions",
      ],
      correct: 1,
    },
    {
      q: "The protein structure that contains peptide bonds, disulfide (S–S) bonds, and ionic bonds is the:",
      a: [
        "Primary structure",
        "Secondary structure",
        "Tertiary structure",
        "Quaternary structure",
        "Fibrous structure",
      ],
      correct: 2,
    },
    {
      q: "The secondary structure of proteins is stabilized mainly by:",
      a: [
        "Peptide and hydrogen bonds",
        "Peptide and ionic bonds",
        "Ionic and disulfide bonds",
        "Peptide and ester bonds",
        "Hydrogen and glycosidic bonds",
      ],
      correct: 0,
    },
    {
      q: "Protein renaturation is assisted by:",
      a: ["Histones", "Elastin", "Chaperone proteins", "Keratin", "Tubulin"],
      correct: 2,
    },
    {
      q: "O-linked glycosylation occurs on which amino acids?",
      a: [
        "Lysine and arginine",
        "Glycine and alanine",
        "Serine and threonine",
        "Asparagine and glutamine",
        "Cysteine and methionine",
      ],
      correct: 2,
    },
    {
      q: "N-linked glycosylation occurs on:",
      a: ["Serine", "Threonine", "Tyrosine", "Asparagine", "Histidine"],
      correct: 3,
    },
    {
      q: "Which acid gives cells a negative charge and prevents them from sticking together?",
      a: [
        "Uric acid",
        "Phosphoric acid",
        "Sialic acid",
        "Lactic acid",
        "Hyaluronic acid",
      ],
      correct: 2,
    },
    {
      q: "Metastatic tumor cells synthesize large amounts of which acid to facilitate cancer spread?",
      a: [
        "Citric acid",
        "Sialic acid",
        "Acetic acid",
        "Carbonic acid",
        "Sulfuric acid",
      ],
      correct: 1,
    },
    {
      q: "The negative surface charge of erythrocytes is mainly due to:",
      a: [
        "Citric acid",
        "Glycolic acid",
        "Sialic acid",
        "Lactic acid",
        "Folic acid",
      ],
      correct: 2,
    },
    {
      q: "GAG stands for:",
      a: [
        "Glycoaminoglycan",
        "Glycosaminoglycan",
        "Glycoprotein Aggregate",
        "General Aminoglycan Group",
        "Glycolipid Associated Glycan",
      ],
      correct: 1,
    },
    {
      q: "Which of the following are simple lipids?",
      a: [
        "Phospholipids, steroids, glycolipids",
        "Fatty acids, waxes, triglycerides",
        "Cholesterol, phospholipids, triglycerides",
        "Glycolipids, sphingolipids, steroids",
        "Lipoproteins, phospholipids, cholesterol",
      ],
      correct: 1,
    },
    {
      q: "Which of the following are complex lipids?",
      a: [
        "Fatty acids, triglycerides, waxes",
        "Monoglycerides, diglycerides, triglycerides",
        "Phospholipids, sphingolipids, steroids",
        "Cholesterol, fatty acids, waxes",
        "Glycerol, phosphates, triglycerides",
      ],
      correct: 2,
    },
    {
      q: "Lipoproteins are complex compounds formed by:",
      a: [
        "Carbohydrates and proteins",
        "Lipids and nucleic acids",
        "Fats (lipids) and proteins",
        "Proteins and vitamins",
        "Fatty acids and carbohydrates",
      ],
      correct: 2,
    },
    {
      q: "The protein component of a lipoprotein is called:",
      a: ["Glycoprotein", "Lipase", "Apoprotein", "Albumin", "Histone"],
      correct: 2,
    },
    {
      q: "Which of the following are lipid components of lipoproteins?",
      a: [
        "Glycogen, cellulose, starch",
        "Phospholipids, cholesterol, triglycerides",
        "Peptide bonds, phospholipids, cholesterol",
        "Fatty acids, amino acids, glucose",
        "Cholesterol, glycogen, proteins",
      ],
      correct: 1,
    },
    {
      q: "In atherosclerosis, which lipoprotein increases and accumulates beneath the vascular endothelium?",
      a: ["HDL", "VLDL", "LDL", "Chylomicrons", "IDL"],
      correct: 2,
    },
    {
      q: "Which lipoprotein transports excess cholesterol from tissues back to the liver?",
      a: ["LDL", "HDL", "VLDL", "Chylomicrons", "IDL"],
      correct: 1,
    },
    {
      q: "Nucleic acids are divided into two types according to their:",
      a: [
        "Nitrogenous bases",
        "Carbohydrate (sugar) component",
        "Phosphate groups",
        "Molecular weight",
        "Protein content",
      ],
      correct: 1,
    },
    {
      q: "The monomer of nucleic acids is the:",
      a: [
        "Amino acid",
        "Monosaccharide",
        "Nucleotide",
        "Fatty acid",
        "Peptide",
      ],
      correct: 2,
    },
    {
      q: "A nucleotide consists of:",
      a: [
        "Amino acid, phosphate, ribose",
        "Nitrogenous base, five-carbon sugar, phosphate group",
        "Glucose, phosphate, adenine",
        "Nitrogenous base, glycerol, phosphate",
        "Fatty acid, ribose, phosphate",
      ],
      correct: 1,
    },
    {
      q: "Nitrogenous bases are chemically classified into:",
      a: [
        "Essential and nonessential bases",
        "Acidic and basic bases",
        "Purine and pyrimidine bases",
        "DNA and RNA bases",
        "Ribose and deoxyribose bases",
      ],
      correct: 2,
    },
    {
      q: "Which of the following are purine bases?",
      a: [
        "Cytosine and thymine",
        "Adenine and guanine",
        "Guanine and uracil",
        "Adenine and cytosine",
        "Thymine and uracil",
      ],
      correct: 1,
    },
    {
      q: "Which of the following are pyrimidine bases?",
      a: [
        "Adenine and guanine",
        "Guanine and cytosine",
        "Cytosine, thymine, and uracil",
        "Adenine, thymine, and guanine",
        "Guanine, uracil, and adenine",
      ],
      correct: 2,
    },
    {
      q: "The two strands of DNA are held together by:",
      a: [
        "Peptide bonds",
        "Glycosidic bonds",
        "Hydrogen bonds",
        "Ester bonds",
        "Ionic bonds",
      ],
      correct: 2,
    },
    {
      q: "Adenine pairs with thymine through:",
      a: [
        "One hydrogen bond",
        "Two hydrogen bonds",
        "Three hydrogen bonds",
        "Four hydrogen bonds",
        "Five hydrogen bonds",
      ],
      correct: 1,
    },
    {
      q: "Guanine pairs with cytosine through:",
      a: [
        "One hydrogen bond",
        "Two hydrogen bonds",
        "Three hydrogen bonds",
        "Four hydrogen bonds",
        "Five hydrogen bonds",
      ],
      correct: 2,
    },
  ],

  cellb2: [
    {
      q: "Nucleoproteins consist of DNA and which protein?",
      a: ["Albumin", "Keratin", "Histone", "Actin", "Collagen"],
      correct: 2,
    },
    {
      q: "The main amphipathic lipids found in the cell membrane are:",
      a: [
        "Triglycerides, cholesterol, waxes",
        "Fatty acids, steroids, waxes",
        "Phospholipids, glycolipids, and steroids",
        "Glycogen, cellulose, phospholipids",
        "Cholesterol esters and triglycerides",
      ],
      correct: 2,
    },
    {
      q: "According to the fluid mosaic model, membrane proteins can move within the lipid bilayer. This means they can also:",
      a: [
        "Change their molecular weight",
        "Change their amino acid sequence",
        "Change their functions",
        "Become phospholipids",
        "Dissolve in the cytoplasm",
      ],
      correct: 2,
    },
    {
      q: "The lipid bilayer is permeable to:",
      a: [
        "Large polar molecules only",
        "Charged ions and proteins",
        "Small, nonpolar, fat-soluble molecules",
        "Polysaccharides only",
        "DNA and RNA",
      ],
      correct: 2,
    },
    {
      q: "Which of the following cannot pass directly through the lipid bilayer?",
      a: [
        "Oxygen (O₂)",
        "Carbon dioxide (CO₂)",
        "Nitrogen (N₂)",
        "Charged ions",
        "Glycerol",
      ],
      correct: 3,
    },
    {
      q: "The most abundant lipids in the lipid bilayer are:",
      a: [
        "Triglycerides",
        "Glycolipids",
        "Cholesterol esters",
        "Phospholipids",
        "Waxes",
      ],
      correct: 3,
    },
    {
      q: "Which phospholipids are primarily located in the outer layer of the cell membrane?",
      a: [
        "Phosphatidylserine and phosphatidylinositol",
        "Phosphatidylethanolamine and phosphatidylserine",
        "Phosphatidylcholine and sphingomyelin",
        "Cardiolipin and phosphatidylinositol",
        "Phosphatidylethanolamine and cardiolipin",
      ],
      correct: 2,
    },
    {
      q: "Which phospholipids are primarily located in the inner layer of the cell membrane?",
      a: [
        "Phosphatidylcholine and sphingomyelin",
        "Phosphatidylethanolamine, phosphatidylserine, and phosphatidylinositol",
        "Cholesterol and sphingomyelin",
        "Glycolipids and phosphatidylcholine",
        "Triglycerides and phosphatidylcholine",
      ],
      correct: 1,
    },
    {
      q: "Which phospholipid is an important component of the mucosa of the large intestine, creating a hydrophobic barrier against pathogenic microorganisms?",
      a: [
        "Phosphatidylserine",
        "Cardiolipin",
        "Phosphatidylcholine",
        "Phosphatidylinositol",
        "Sphingosine",
      ],
      correct: 2,
    },
    {
      q: "Some membrane proteins are attached to the membrane through",
      a: [
        "Hydrogen bonds",
        "Peptide bonds",
        "Glycosylphosphatidylinositol (GPI) anchors",
        "Disulfide bonds",
        "Ester bonds",
      ],
      correct: 2,
    },
    {
      q: "Which membrane proteins are located on the inner or outer surface of the membrane and do not cross the lipid bilayer?",
      a: [
        "Integral proteins",
        "Channel proteins",
        "Peripheral proteins",
        "Carrier proteins",
        "Transport proteins",
      ],
      correct: 2,
    },
    {
      q: "Which membrane proteins span the lipid bilayer and contain transmembrane and peripheral domains?",
      a: [
        "Peripheral proteins",
        "Fibrous proteins",
        "Integral proteins",
        "Histone proteins",
        "Globular proteins",
      ],
      correct: 2,
    },
    {
      q: "Which membrane proteins function as electron carriers, cytoskeletal anchors, and intracellular secondary messengers?",
      a: [
        "Integral proteins",
        "Peripheral proteins",
        "Glycoproteins",
        "Lipoproteins",
        "Histone proteins",
      ],
      correct: 1,
    },
    {
      q: "Which membrane proteins function as receptors, enzymatic signaling elements, and cell-recognition molecules?",
      a: [
        "Peripheral proteins",
        "Cytoskeletal proteins",
        "Integral proteins",
        "Structural proteins",
        "Histone proteins",
      ],
      correct: 2,
    },
    {
      q: "Which type of membrane transport moves substances from a region of higher concentration to lower concentration without requiring energy?",
      a: [
        "Active transport",
        "Endocytosis",
        "Passive transport",
        "Exocytosis",
        "Vesicular transport",
      ],
      correct: 2,
    },
    {
      q: "Which transport mechanism results in the equal distribution of molecules without requiring additional cellular processes?",
      a: [
        "Active transport",
        "Osmosis",
        "Diffusion",
        "Endocytosis",
        "Facilitated transport",
      ],
      correct: 2,
    },
    {
      q: "Oxygen, nitrogen, carbon dioxide, water, and glycerol primarily cross the cell membrane by:",
      a: [
        "Facilitated diffusion",
        "Active transport",
        "Endocytosis",
        "Simple diffusion",
        "Pinocytosis",
      ],
      correct: 3,
    },
    {
      q: "Which type of transport requires no energy but uses protein channels or carrier proteins to move substances from a higher to a lower concentration?",
      a: [
        "Active transport",
        "Simple diffusion",
        "Facilitated diffusion",
        "Osmosis",
        "Endocytosis",
      ],
      correct: 2,
    },
    {
      q: "Facilitated diffusion depends on the presence of:",
      a: [
        "ATP molecules",
        "Transport proteins",
        "Mitochondria",
        "Lysosomes",
        "Ribosomes",
      ],
      correct: 1,
    },
    {
      q: "Active transport moves substances:",
      a: [
        "From higher to lower concentration",
        "Along the concentration gradient",
        "Against the concentration gradient",
        "Without transport proteins",
        "By simple diffusion",
      ],
      correct: 2,
    },
    {
      q: "Primary active transport directly uses which source of energy?",
      a: ["GTP", "ATP", "NADH", "FADH₂", "Glucose"],
      correct: 1,
    },
    {
      q: "Which type of transport requires energy obtained from a pre-existing electrochemical gradient?",
      a: [
        "Passive transport",
        "Primary active transport",
        "Secondary active transport",
        "Simple diffusion",
        "Osmosis",
      ],
      correct: 2,
    },
    {
      q: "Vesicular transport includes:",
      a: [
        "Diffusion and osmosis",
        "Facilitated diffusion and osmosis",
        "Endocytosis and exocytosis",
        "Active transport and diffusion",
        "Filtration and osmosis",
      ],
      correct: 2,
    },
    {
      q: "SGLT2 is an example of:",
      a: [
        "Primary active transport",
        "Facilitated diffusion",
        "Secondary active transport",
        "Simple diffusion",
        "Endocytosis",
      ],
      correct: 2,
    },
    {
      q: "Drugs that inhibit SGLT2 are mainly used in the treatment of:",
      a: [
        "Type 1 diabetes mellitus",
        "Type 2 diabetes mellitus",
        "Diabetes insipidus",
        "Hyperthyroidism",
        "Addison disease",
      ],
      correct: 1,
    },
    {
      q: "MDR (multidrug resistance) proteins are:",
      a: [
        "ATP-dependent transporters",
        "Ion channels",
        "Carrier proteins for glucose",
        "Passive transport proteins",
        "Cytoskeletal proteins",
      ],
      correct: 0,
    },
    {
      q: "Which type of endocytosis is responsible for engulfing solid particles?",
      a: [
        "Pinocytosis",
        "Exocytosis",
        "Phagocytosis",
        "Transcytosis",
        "Diffusion",
      ],
      correct: 2,
    },
    {
      q: "Which type of endocytosis is responsible for uptake of extracellular fluid?",
      a: ["Phagocytosis", "Pinocytosis", "Exocytosis", "Osmosis", "Filtration"],
      correct: 1,
    },
    {
      q: "Which type of vesicular transport allows substances to pass through a cell while both endocytosis and exocytosis occur?",
      a: [
        "Pinocytosis",
        "Phagocytosis",
        "Transcytosis",
        "Diffusion",
        "Facilitated diffusion",
      ],
      correct: 2,
    },
    {
      q: "In osmosis, water moves across a semipermeable membrane until:",
      a: [
        "ATP is depleted",
        "Glucose is absorbed",
        "Equilibrium is reached",
        "Sodium concentration becomes zero",
        "Proteins are transported",
      ],
      correct: 2,
    },
  ],

  cellb3: [
    {
      q: "Which of the following are membrane-less organelles?",
      a: [
        "Mitochondria and lysosomes",
        "Ribosomes and proteasomes",
        "Golgi apparatus and nucleus",
        "Peroxisomes and lysosomes",
        "Endoplasmic reticulum and Golgi apparatus",
      ],
      correct: 1,
    },
    {
      q: "Which of the following are double-membrane organelles?",
      a: [
        "Lysosomes, ribosomes, Golgi apparatus",
        "Nucleus, mitochondria, chloroplasts",
        "Peroxisomes, lysosomes, ribosomes",
        "Smooth ER, rough ER, Golgi apparatus",
        "Proteasomes, centrosomes, ribosomes",
      ],
      correct: 1,
    },
    {
      q: "Which organelles contain their own genetic material?",
      a: [
        "Golgi apparatus and lysosomes",
        "Nucleus and mitochondria",
        "Ribosomes and peroxisomes",
        "Smooth ER and rough ER",
        "Golgi apparatus and nucleus",
      ],
      correct: 1,
    },
    {
      q: "Synthesis of fatty acids, phospholipids, and steroids occurs mainly in the:",
      a: [
        "Rough endoplasmic reticulum",
        "Smooth endoplasmic reticulum",
        "Golgi apparatus",
        "Lysosome",
        "Ribosome",
      ],
      correct: 1,
    },
    {
      q: "Detoxification of drugs and metabolites occurs primarily in the:",
      a: [
        "Golgi apparatus",
        "Smooth endoplasmic reticulum",
        "Rough endoplasmic reticulum",
        "Lysosome",
        "Nucleus",
      ],
      correct: 1,
    },
    {
      q: "Which endoplasmic reticulum has ribosomes attached to its surface?",
      a: [
        "Smooth endoplasmic reticulum",
        "Rough endoplasmic reticulum",
        "Golgi apparatus",
        "Peroxisome",
        "Lysosome",
      ],
      correct: 1,
    },
    {
      q: "Protein synthesis occurs mainly in the:",
      a: [
        "Smooth endoplasmic reticulum",
        "Rough endoplasmic reticulum",
        "Lysosome",
        "Peroxisome",
        "Golgi apparatus",
      ],
      correct: 1,
    },
    {
      q: "The Golgi apparatus is composed of membrane-bound sacs called:",
      a: ["Cristae", "Cisternae", "Vesicles", "Lamellae", "Tubules"],
      correct: 1,
    },
    {
      q: "Which face of the Golgi apparatus receives vesicles from the endoplasmic reticulum?",
      a: [
        "Trans face",
        "Cis face",
        "Lateral face",
        "Basal face",
        "Apical face",
      ],
      correct: 1,
    },
    {
      q: "Which face of the Golgi apparatus packages and directs materials for secretion or delivery to lysosomes?",
      a: [
        "Cis face",
        "Medial face",
        "Trans face",
        "Inner face",
        "Nuclear face",
      ],
      correct: 2,
    },
    {
      q: "Which organelle is known as the powerhouse of the cell?",
      a: [
        "Nucleus",
        "Lysosome",
        "Mitochondrion",
        "Golgi apparatus",
        "Peroxisome",
      ],
      correct: 2,
    },
    {
      q: "Which double-membrane organelle is responsible for ATP production?",
      a: ["Ribosome", "Lysosome", "Mitochondrion", "Proteasome", "Peroxisome"],
      correct: 2,
    },
    {
      q: "Which organelle contains its own circular DNA?",
      a: [
        "Golgi apparatus",
        "Lysosome",
        "Mitochondrion",
        "Rough ER",
        "Ribosome",
      ],
      correct: 2,
    },
    {
      q: "MELAS syndrome is classified as a:",
      a: [
        "Lysosomal disease",
        "Peroxisomal disease",
        "Mitochondrial disease",
        "Ribosomal disease",
        "Nuclear disease",
      ],
      correct: 2,
    },
    {
      q: "Which organelles contain enzymes that digest proteins, nucleic acids, and carbohydrates?",
      a: [
        "Peroxisomes",
        "Lysosomes",
        "Ribosomes",
        "Proteasomes",
        "Golgi apparatus",
      ],
      correct: 1,
    },
    {
      q: "Which organelles are responsible for oxidation of very-long-chain fatty acids?",
      a: [
        "Lysosomes",
        "Mitochondria",
        "Peroxisomes",
        "Ribosomes",
        "Golgi apparatus",
      ],
      correct: 2,
    },
    {
      q: "Cholesterol synthesis and bile acid formation involve which organelles?",
      a: [
        "Mitochondria",
        "Lysosomes",
        "Peroxisomes",
        "Golgi apparatus",
        "Ribosomes",
      ],
      correct: 2,
    },
    {
      q: "Which organelles degrade damaged or misfolded proteins?",
      a: ["Lysosomes", "Peroxisomes", "Proteasomes", "Ribosomes", "Nuclei"],
      correct: 2,
    },
    {
      q: "Microfilaments are primarily composed of:",
      a: ["Tubulin", "Keratin", "Actin", "Collagen", "Elastin"],
      correct: 2,
    },
    {
      q: "Intermediate filaments are primarily composed of:",
      a: ["Actin", "Tubulin", "Keratin", "Collagen", "Myosin"],
      correct: 2,
    },
    {
      q: "Microtubules are primarily composed of:",
      a: ["Actin", "Keratin", "Tubulin", "Collagen", "Elastin"],
      correct: 2,
    },
    {
      q: "Which cytoskeletal component serves as tracks for intracellular transport by kinesin and dynein?",
      a: [
        "Intermediate filaments",
        "Microfilaments",
        "Microtubules",
        "Collagen fibers",
        "Actin filaments",
      ],
      correct: 2,
    },
    {
      q: "In Chédiak–Higashi syndrome, defective transport of melanin is associated with dysfunction of:",
      a: ["Dynein", "Actin", "Keratin", "Kinesin", "Tubulin"],
      correct: 3,
    },
    {
      q: "Signaling molecules that bind to receptors are called:",
      a: ["Enzymes", "Ligands", "Cofactors", "Hormones only", "Cytokines only"],
      correct: 1,
    },
    {
      q: "Which type of cell signaling acts on the same cell that secretes the signaling molecule and is important during embryonic development?",
      a: ["Endocrine", "Paracrine", "Autocrine", "Synaptic", "Juxtacrine"],
      correct: 2,
    },
    {
      q: "Which type of cell signaling acts on neighboring cells?",
      a: ["Endocrine", "Autocrine", "Paracrine", "Synaptic", "Intracrine"],
      correct: 2,
    },
    {
      q: "Which type of signaling acts over long distances, usually through the bloodstream?",
      a: ["Autocrine", "Paracrine", "Endocrine", "Juxtacrine", "Synaptic"],
      correct: 2,
    },
    {
      q: "During inflammation, macrophages release IL-1, IL-6, and TNF-α, stimulating the liver to synthesize which positive acute-phase protein?",
      a: [
        "Albumin",
        "Fibrinogen",
        "α1-Acid glycoprotein (AAG)",
        "Hemoglobin",
        "Ferritin",
      ],
      correct: 2,
    },
    {
      q: "Which G protein activates protein kinase A (PKA)?",
      a: ["Gi", "Gq", "Gs", "Gt", "Go"],
      correct: 2,
    },
    {
      q: "In which G protein is GDP exchanged for GTP during activation?",
      a: ["Gi", "Gq", "Gs", "All G proteins", "Ras"],
      correct: 3,
    },
  ],

  cellb4: [
    {
      q: "Which G protein activates adenylate cyclase, increasing cAMP production?",
      a: ["Gi", "Gq", "Gs", "G12", "Gt"],
      correct: 2,
    },
    {
      q: "Which G protein inhibits adenylate cyclase, resulting in decreased cAMP?",
      a: ["Gs", "Gq", "Gi", "Gt", "Ras"],
      correct: 2,
    },
    {
      q: "Which G protein activates phospholipase C, producing IP₃ and DAG?",
      a: ["Gi", "Gs", "Gq", "Gt", "Go"],
      correct: 2,
    },
    {
      q: "Which molecule directly activates protein kinase C (PKC)?",
      a: ["IP₃", "ATP", "cAMP", "DAG", "Calcium"],
      correct: 3,
    },
    {
      q: "Cholera toxin from Vibrio cholerae persistently activates which G protein?",
      a: ["Gi", "Gq", "Gs", "Gt", "Ras"],
      correct: 2,
    },
    {
      q: "The most important enzyme-linked receptors are:",
      a: [
        "Serotonin receptors",
        "Tyrosine kinase receptors",
        "Steroid receptors",
        "Nicotinic receptors",
        "Muscarinic receptors",
      ],
      correct: 1,
    },
    {
      q: "In acute promyelocytic (myeloid) leukemia, treatment commonly involves:",
      a: [
        "Vitamin C",
        "Vitamin D",
        "Vitamin A (all-trans retinoic acid)",
        "Vitamin K",
        "Vitamin E",
      ],
      correct: 2,
    },
    {
      q: "During which phase of the cell cycle does the cell grow and duplicate most organelles?",
      a: ["G₁ phase", "S phase", "G₂ phase", "M phase", "G₀ phase"],
      correct: 0,
    },
    {
      q: "DNA replication occurs during:",
      a: ["G₁ phase", "S phase", "G₂ phase", "Prophase", "Metaphase"],
      correct: 1,
    },
    {
      q: "Centriole duplication occurs during:",
      a: ["G₁ phase", "S phase", "G₂ phase", "Prophase", "Anaphase"],
      correct: 1,
    },
    {
      q: "Additional protein synthesis and organelle duplication mainly occur during:",
      a: ["G₁ phase", "S phase", "G₂ phase", "Metaphase", "Telophase"],
      correct: 2,
    },
    {
      q: "During which phase do chromosomes condense, the nucleolus disappears, and the mitotic spindle begins to form?",
      a: ["Prometaphase", "Prophase", "Metaphase", "Anaphase", "Telophase"],
      correct: 1,
    },
    {
      q: "During which phase do spindle fibers attach to chromosomes through kinetochores?",
      a: ["Prophase", "Prometaphase", "Metaphase", "Anaphase", "Telophase"],
      correct: 1,
    },
    {
      q: "During which phase are chromosomes aligned along the equatorial plate?",
      a: ["Prophase", "Prometaphase", "Metaphase", "Anaphase", "Telophase"],
      correct: 2,
    },
    {
      q: "Sister chromatids separate during:",
      a: ["Prophase", "Prometaphase", "Metaphase", "Anaphase", "Telophase"],
      correct: 3,
    },
    {
      q: "Which drug blocks mitotic spindle formation, arresting cells in metaphase?",
      a: [
        "Methotrexate",
        "Vincristine",
        "Colchicine",
        "Cisplatin",
        "Cyclophosphamide",
      ],
      correct: 2,
    },
    {
      q: "Colchicine reduces inflammation primarily because it:",
      a: [
        "Inhibits DNA replication",
        "Blocks mitotic spindle fibers in metaphase",
        "Stimulates protein synthesis",
        "Activates lysosomes",
        "Inhibits ATP synthesis",
      ],
      correct: 1,
    },
    {
      q: "During which phase do spindle fibers disappear and chromosomes begin to decondense?",
      a: ["Prophase", "Metaphase", "Anaphase", "Telophase", "Cytokinesis"],
      correct: 3,
    },
    {
      q: "Which checkpoint determines whether the cell is ready to begin DNA replication?",
      a: [
        "G₁ checkpoint",
        "S checkpoint",
        "G₂ checkpoint",
        "M checkpoint",
        "Spindle checkpoint",
      ],
      correct: 0,
    },
    {
      q: "Which checkpoint verifies DNA integrity and completion of DNA replication?",
      a: [
        "G₁ checkpoint",
        "S checkpoint",
        "G₂ checkpoint",
        "M checkpoint",
        "Cytokinesis checkpoint",
      ],
      correct: 2,
    },
    {
      q: "Which checkpoint ensures that all sister chromatids are correctly attached to spindle microtubules?",
      a: [
        "G₁ checkpoint",
        "G₂ checkpoint",
        "M checkpoint",
        "S checkpoint",
        "G₀ checkpoint",
      ],
      correct: 2,
    },
    {
      q: "Be-6 protein primarily functions to:",
      a: [
        "Stimulate apoptosis",
        "Repair DNA",
        "Block apoptosis",
        "Activate caspases",
        "Promote mitosis",
      ],
      correct: 2,
    },
    {
      q: "The inside of a resting cell is normally:",
      a: [
        "Positively charged",
        "Electrically neutral",
        "Negatively charged",
        "Equal to the outside",
        "Rich in sodium ions",
      ],
      correct: 2,
    },
    {
      q: "The stable membrane potential of an unstimulated cell is called the:",
      a: [
        "Threshold potential",
        "Action potential",
        "Resting membrane potential",
        "Depolarization",
        "Hyperpolarization",
      ],
      correct: 2,
    },
    {
      q: "The resting membrane potential of most cells is approximately:",
      a: [
        "+30 to +40 mV",
        "0 to +10 mV",
        "–70 to –80 mV",
        "–10 to –20 mV",
        "+70 to +80 mV",
      ],
      correct: 2,
    },
    {
      q: "An increase in positive charge inside the cell is called:",
      a: [
        "Repolarization",
        "Hyperpolarization",
        "Depolarization",
        "Polarization",
        "Facilitation",
      ],
      correct: 2,
    },
    {
      q: "A shift of the intracellular charge toward a more negative value is called:",
      a: [
        "Depolarization",
        "Repolarization",
        "Hyperpolarization",
        "Excitation",
        "Summation",
      ],
      correct: 2,
    },
    {
      q: "A rapid, short-lasting depolarization of the membrane is called:",
      a: [
        "Resting potential",
        "Hyperpolarization",
        "Action potential",
        "Equilibrium potential",
        "Threshold potential",
      ],
      correct: 2,
    },
    {
      q: "In most excitable cells, action potentials are generated mainly by opening:",
      a: [
        "Ligand-gated chloride channels",
        "ATP-dependent pumps",
        "Voltage-gated ion channels",
        "Aquaporins",
        "Gap junctions",
      ],
      correct: 2,
    },
    {
      q: "Thiazide diuretics may cause hypokalemia, increasing the risk of:",
      a: [
        "Hyperglycemia only",
        "Heart arrhythmias and muscle weakness",
        "Liver failure",
        "Hemolytic anemia",
        "Pulmonary fibrosis",
      ],
      correct: 1,
    },
  ],

  cellb5: [
    {
      q: "What is the most abundant and widely distributed type of collagen?",
      a: ["Type II", "Type III", "Type IV", "Type I", "Type V"],
      correct: 3,
    },
    {
      q: "Which type of collagen is found in the dermis, bone, tendons, blood vessel walls, cornea, and skin?",
      a: ["Type II", "Type III", "Type IV", "Type I", "Type V"],
      correct: 3,
    },
    {
      q: "Which type of collagen is found in hyaline cartilage, articular discs, and the vitreous body of the eye?",
      a: ["Type I", "Type II", "Type III", "Type IV", "Type V"],
      correct: 1,
    },
    {
      q: "Reticular fibers are primarily composed of:",
      a: [
        "Type I collagen",
        "Type II collagen",
        "Type III collagen",
        "Type IV collagen",
        "Type V collagen",
      ],
      correct: 2,
    },
    {
      q: "Which collagen type provides structural support for bone marrow, spleen, and lymph nodes?",
      a: ["Type I", "Type II", "Type III", "Type IV", "Type V"],
      correct: 2,
    },
    {
      q: "Which collagen type is commonly found surrounding type I collagen in skin and blood vessel walls?",
      a: ["Type I", "Type II", "Type III", "Type IV", "Type V"],
      correct: 2,
    },
    {
      q: "Which type of collagen forms the basement membrane?",
      a: ["Type I", "Type II", "Type III", "Type IV", "Type V"],
      correct: 3,
    },
    {
      q: "Which collagen type is mainly found in the cornea, glomerular basement membrane, and inner ear?",
      a: ["Type I", "Type II", "Type III", "Type IV", "Type V"],
      correct: 3,
    },
    {
      q: "Collagen is synthesized primarily by:",
      a: [
        "Osteoclasts",
        "Chondrocytes",
        "Fibroblasts",
        "Macrophages",
        "Keratinocytes",
      ],
      correct: 2,
    },
    {
      q: "Formation of hydroxyproline and hydroxylysine during collagen synthesis occurs by:",
      a: [
        "Glycosylation",
        "Hydroxylation",
        "Phosphorylation",
        "Acetylation",
        "Methylation",
      ],
      correct: 1,
    },
    {
      q: "Which vitamin is required for hydroxylation during collagen synthesis?",
      a: ["Vitamin A", "Vitamin D", "Vitamin C", "Vitamin E", "Vitamin K"],
      correct: 2,
    },
    {
      q: "Cross-linking of collagen fibers is catalyzed by:",
      a: [
        "Collagenase",
        "Elastase",
        "Lysyl oxidase",
        "DNA ligase",
        "Topoisomerase",
      ],
      correct: 2,
    },
    {
      q: "Lysyl oxidase requires which cofactor?",
      a: ["Iron", "Zinc", "Copper", "Calcium", "Magnesium"],
      correct: 2,
    },
    {
      q: "Osteogenesis imperfecta is also known as:",
      a: [
        "Marfan syndrome",
        "Brittle bone disease",
        "Scurvy",
        "Menkes disease",
        "Ehlers-Danlos syndrome",
      ],
      correct: 1,
    },
    {
      q: "Osteogenesis imperfecta is inherited as:",
      a: [
        "Autosomal recessive",
        "X-linked dominant",
        "X-linked recessive",
        "Autosomal dominant",
        "Mitochondrial",
      ],
      correct: 3,
    },
    {
      q: "Osteogenesis imperfecta is most commonly caused by mutations in:",
      a: ["FBN1", "ATP7A", "COL1A1 or COL1A2", "COL3A1", "BLM"],
      correct: 2,
    },
    {
      q: "Classic Ehlers-Danlos syndrome is usually inherited as:",
      a: [
        "Autosomal recessive",
        "X-linked recessive",
        "Autosomal dominant",
        "Mitochondrial",
        "X-linked dominant",
      ],
      correct: 2,
    },
    {
      q: "Classic Ehlers-Danlos syndrome is mainly associated with defects in:",
      a: [
        "Type I collagen",
        "Type II collagen",
        "Type III collagen",
        "Type V collagen",
        "Type IV collagen",
      ],
      correct: 3,
    },
    {
      q: "Hyperextensible skin and joint hypermobility are characteristic of:",
      a: [
        "Marfan syndrome",
        "Classic Ehlers-Danlos syndrome",
        "Osteogenesis imperfecta",
        "Scurvy",
        "Menkes disease",
      ],
      correct: 1,
    },
    {
      q: "Vascular Ehlers-Danlos syndrome is primarily associated with defects in:",
      a: [
        "Type I collagen",
        "Type II collagen",
        "Type III collagen",
        "Type IV collagen",
        "Type V collagen",
      ],
      correct: 2,
    },
    {
      q: "Vascular fragility and spontaneous rupture of blood vessels are characteristic of:",
      a: [
        "Marfan syndrome",
        "Classic Ehlers-Danlos syndrome",
        "Vascular Ehlers-Danlos syndrome",
        "Osteogenesis imperfecta",
        "Scurvy",
      ],
      correct: 2,
    },
    {
      q: "Menkes disease is caused by mutations in which gene?",
      a: ["FBN1", "ATP7A", "BLM", "COL1A1", "ATP7B"],
      correct: 1,
    },
    {
      q: "Menkes disease primarily affects the metabolism of:",
      a: ["Iron", "Zinc", "Copper", "Calcium", "Magnesium"],
      correct: 2,
    },
    {
      q: "Menkes disease is inherited as:",
      a: [
        "Autosomal dominant",
        "Autosomal recessive",
        "X-linked recessive",
        "X-linked dominant",
        "Mitochondrial",
      ],
      correct: 2,
    },
    {
      q: "A floppy infant with kinky hair is most suggestive of:",
      a: [
        "Marfan syndrome",
        "Menkes disease",
        "Scurvy",
        "Osteogenesis imperfecta",
        "Bloom syndrome",
      ],
      correct: 1,
    },
    {
      q: "Vitamin C deficiency causes:",
      a: ["Rickets", "Osteomalacia", "Scurvy", "Pellagra", "Beriberi"],
      correct: 2,
    },
    {
      q: "Vitamin C serves as a cofactor for:",
      a: [
        "DNA polymerase",
        "Lysyl oxidase only",
        "Proline and lysine hydroxylases",
        "RNA polymerase",
        "Topoisomerase",
      ],
      correct: 2,
    },
    {
      q: "Unlike collagen, elastin does not undergo:",
      a: [
        "Hydroxylation or glycosylation",
        "Cross-linking",
        "Polymerization",
        "Folding",
        "Secretion",
      ],
      correct: 0,
    },
    {
      q: "Which enzyme degrades elastin and is regulated by α1-antitrypsin?",
      a: ["Collagenase", "Elastase", "Topoisomerase", "Ligase", "Polymerase"],
      correct: 1,
    },
    {
      q: "α1-Antitrypsin deficiency is inherited as:",
      a: [
        "Autosomal dominant",
        "Autosomal recessive",
        "X-linked recessive",
        "Autosomal codominant",
        "Mitochondrial",
      ],
      correct: 3,
    },
  ],

  cellb6: [
    {
      q: "α1-Antitrypsin deficiency results in excessive activity of:",
      a: ["Collagenase", "Elastase", "Polymerase", "Topoisomerase", "Helicase"],
      correct: 1,
    },
    {
      q: "A major pulmonary complication of α1-Antitrypsin deficiency is:",
      a: [
        "Pulmonary fibrosis",
        "Asthma",
        "Emphysema",
        "Pneumonia",
        "Tuberculosis",
      ],
      correct: 2,
    },
    {
      q: "Marfan syndrome is inherited as:",
      a: [
        "Autosomal recessive",
        "X-linked recessive",
        "Autosomal dominant",
        "Codominant",
        "Mitochondrial",
      ],
      correct: 2,
    },
    {
      q: "Marfan syndrome is caused by mutations in:",
      a: ["COL1A1", "ATP7A", "FBN1", "BLM", "TP53"],
      correct: 2,
    },
    {
      q: "In a nucleotide, the nitrogenous base is attached to which carbon of the sugar?",
      a: [
        "First carbon (1′)",
        "Second carbon (2′)",
        "Third carbon (3′)",
        "Fourth carbon (4′)",
        "Fifth carbon (5′)",
      ],
      correct: 0,
    },
    {
      q: "In a nucleotide, the phosphate group is attached to which carbon?",
      a: [
        "First carbon (1′)",
        "Second carbon (2′)",
        "Third carbon (3′)",
        "Fourth carbon (4′)",
        "Fifth carbon (5′)",
      ],
      correct: 4,
    },
    {
      q: "Nucleotides are linked together by:",
      a: [
        "Peptide bonds",
        "Glycosidic bonds",
        "Phosphodiester bonds",
        "Hydrogen bonds",
        "Ester bonds",
      ],
      correct: 2,
    },
    {
      q: "Which histone binds linker DNA and stabilizes the nucleosome?",
      a: ["H2A", "H2B", "H3", "H4", "H1"],
      correct: 4,
    },
    {
      q: "DNA methylation generally:",
      a: [
        "Activates transcription",
        "Represses transcription",
        "Initiates translation",
        "Increases DNA replication",
        "Stimulates mitosis",
      ],
      correct: 1,
    },
    {
      q: "Histone acetylation generally:",
      a: [
        "Represses transcription",
        "Activates transcription",
        "Stops DNA replication",
        "Inhibits RNA synthesis",
        "Causes DNA mutation",
      ],
      correct: 1,
    },
    {
      q: "Which enzyme separates DNA strands by breaking hydrogen bonds?",
      a: [
        "DNA polymerase",
        "DNA ligase",
        "Helicase",
        "Topoisomerase",
        "Primase",
      ],
      correct: 2,
    },
    {
      q: "Which proteins keep separated DNA strands from reannealing?",
      a: [
        "Histones",
        "SSB proteins (single-stranded binding proteins)",
        "Topoisomerases",
        "Ligases",
        "Polymerases",
      ],
      correct: 1,
    },
    {
      q: "Bloom syndrome is inherited as:",
      a: [
        "Autosomal dominant",
        "Autosomal recessive",
        "X-linked recessive",
        "X-linked dominant",
        "Mitochondrial",
      ],
      correct: 1,
    },
    {
      q: "Bloom syndrome is caused by mutations in:",
      a: ["TP53", "FBN1", "BLM", "COL1A1", "ATP7A"],
      correct: 2,
    },
    {
      q: "The BLM gene encodes which enzyme?",
      a: ["Polymerase", "Helicase", "Ligase", "Primase", "Topoisomerase"],
      correct: 1,
    },
    {
      q: "The key enzyme responsible for DNA synthesis during replication is:",
      a: ["Helicase", "Primase", "DNA polymerase", "Ligase", "Topoisomerase"],
      correct: 2,
    },
    {
      q: "Which DNA strand is synthesized continuously in the 5′→3′ direction?",
      a: [
        "Lagging strand",
        "Template strand",
        "Leading strand",
        "Antisense strand",
        "Coding strand",
      ],
      correct: 2,
    },
    {
      q: "Which DNA strand is synthesized discontinuously opposite the replication fork?",
      a: [
        "Leading strand",
        "Coding strand",
        "Lagging strand",
        "Template strand",
        "Sense strand",
      ],
      correct: 2,
    },
    {
      q: "The short DNA fragments synthesized on the lagging strand are called:",
      a: [
        "Telomeres",
        "Okazaki fragments",
        "Replicons",
        "Nucleosomes",
        "Exons",
      ],
      correct: 1,
    },
    {
      q: "Which enzyme relieves DNA supercoiling ahead of the replication fork?",
      a: ["Ligase", "Polymerase", "Topoisomerase", "Helicase", "Primase"],
      correct: 2,
    },
    {
      q: "Which enzyme joins Okazaki fragments together?",
      a: ["Polymerase", "Helicase", "DNA ligase", "Primase", "Topoisomerase"],
      correct: 2,
    },
    {
      q: "Agents that damage DNA are collectively known as:",
      a: ["Carcinogens", "Mutagens", "Oncogenes", "Histones", "Cytokines"],
      correct: 1,
    },
    {
      q: "Ultraviolet radiation, ionizing radiation, chemicals, and biological agents are examples of:",
      a: [
        "Endogenous mutagens",
        "Exogenous mutagens",
        "Repair enzymes",
        "Antioxidants",
        "Proto-oncogenes",
      ],
      correct: 1,
    },
    {
      q: "Hydrolysis, methylation, and acetylation are examples of:",
      a: [
        "Exogenous mutagens",
        "Endogenous mutagens",
        "Repair pathways",
        "DNA replication factors",
        "Cell cycle checkpoints",
      ],
      correct: 1,
    },
    {
      q: "Adjacent thymine and cytosine bases in DNA are particularly susceptible to damage from:",
      a: [
        "Infrared radiation",
        "X-rays",
        "UV light",
        "Ultrasound",
        "Gamma globulins",
      ],
      correct: 2,
    },
    {
      q: "Which type of mutation is not inherited by offspring?",
      a: [
        "Germline mutation",
        "Frameshift mutation",
        "Somatic mutation",
        "Missense mutation",
        "Nonsense mutation",
      ],
      correct: 2,
    },
    {
      q: "Which type of mutation can be inherited by offspring?",
      a: [
        "Silent mutation",
        "Somatic mutation",
        "Germline mutation",
        "Missense mutation",
        "Nonsense mutation",
      ],
      correct: 2,
    },
    {
      q: "In which mutation does the altered codon still code for the same amino acid?",
      a: [
        "Missense mutation",
        "Nonsense mutation",
        "Silent mutation",
        "Frameshift mutation",
        "Germline mutation",
      ],
      correct: 2,
    },
    {
      q: "In which mutation does the altered codon encode a different amino acid?",
      a: [
        "Silent mutation",
        "Missense mutation",
        "Nonsense mutation",
        "Frameshift mutation",
        "Germline mutation",
      ],
      correct: 1,
    },
    {
      q: "Which mutation converts a codon into a stop codon?",
      a: [
        "Silent mutation",
        "Missense mutation",
        "Frameshift mutation",
        "Nonsense mutation",
        "Germline mutation",
      ],
      correct: 3,
    },
  ],

  cellb7: [
    {
      q: "Which mutation results from deletion or insertion of one or more nucleotides, altering the reading frame?",
      a: [
        "Silent mutation",
        "Missense mutation",
        "Frameshift mutation",
        "Nonsense mutation",
        "Point mutation",
      ],
      correct: 2,
    },
    {
      q: "A frameshift mutation does not occur if how many nucleotides are inserted or deleted?",
      a: ["One", "Two", "Three", "Four", "Five"],
      correct: 2,
    },
    {
      q: "Which DNA repair mechanism corrects mismatched nucleotides in the newly synthesized DNA strand?",
      a: [
        "Base excision repair",
        "Nucleotide excision repair",
        "Mismatch repair",
        "Direct repair",
        "Homologous recombination",
      ],
      correct: 2,
    },
    {
      q: "Which DNA repair mechanism reverses the chemical reaction that caused DNA damage?",
      a: [
        "Direct repair",
        "Mismatch repair",
        "Base excision repair",
        "Nucleotide excision repair",
        "Non-homologous end joining",
      ],
      correct: 0,
    },
    {
      q: "Which repair mechanism removes damaged bases and replaces them with the correct nucleotide?",
      a: [
        "Mismatch repair",
        "Base excision repair",
        "Nucleotide excision repair",
        "Direct repair",
        "Homologous recombination",
      ],
      correct: 1,
    },
    {
      q: "Which repair mechanism primarily repairs UV-induced DNA damage?",
      a: [
        "Base excision repair",
        "Mismatch repair",
        "Nucleotide excision repair",
        "Direct repair",
        "Homologous recombination",
      ],
      correct: 2,
    },
    {
      q: "Which DNA repair mechanism removes the damaged nucleotide together with a short surrounding DNA segment?",
      a: [
        "Direct repair",
        "Base excision repair",
        "Nucleotide excision repair",
        "Mismatch repair",
        "Homologous recombination",
      ],
      correct: 2,
    },
    {
      q: "Which enzyme removes damaged DNA during excision repair?",
      a: ["Helicase", "Ligase", "Polymerase", "Nuclease", "Primase"],
      correct: 3,
    },
    {
      q: "Which DNA double-strand break repair pathway is more prone to introducing mutations?",
      a: [
        "Homologous recombination",
        "Base excision repair",
        "Direct repair",
        "Non-homologous end joining",
        "Mismatch repair",
      ],
      correct: 3,
    },
    {
      q: "Which repair pathway uses the sister chromatid as a template and is highly accurate?",
      a: [
        "Non-homologous end joining",
        "Direct repair",
        "Homologous recombination",
        "Base excision repair",
        "Mismatch repair",
      ],
      correct: 2,
    },
    {
      q: "Xeroderma pigmentosum results from defective repair of:",
      a: [
        "Oxidative DNA damage",
        "Replication errors",
        "UV-induced DNA damage",
        "RNA damage",
        "Double-strand breaks",
      ],
      correct: 2,
    },
    {
      q: "Xeroderma pigmentosum is caused by failure of:",
      a: [
        "Base excision repair",
        "Mismatch repair",
        "Nucleotide excision repair",
        "Homologous recombination",
        "Direct repair",
      ],
      correct: 2,
    },
    {
      q: "The central dogma of molecular biology is:",
      a: [
        "DNA → Protein → RNA",
        "RNA → DNA → Protein",
        "DNA → RNA → Protein",
        "Protein → DNA → RNA",
        "RNA → Protein → DNA",
      ],
      correct: 2,
    },
    {
      q: "Which portions of genes are removed during RNA processing?",
      a: ["Exons", "Introns", "Codons", "Promoters", "Enhancers"],
      correct: 1,
    },
    {
      q: "The site where transcription begins is called the:",
      a: [
        "Operator",
        "Enhancer",
        "Promoter",
        "Terminator",
        "Origin of replication",
      ],
      correct: 2,
    },
    {
      q: "Which antibiotic inhibits DNA-dependent RNA polymerase in prokaryotes?",
      a: [
        "Penicillin",
        "Rifampicin",
        "Tetracycline",
        "Chloramphenicol",
        "Erythromycin",
      ],
      correct: 1,
    },
    {
      q: "Which toxin from Amanita phalloides inhibits RNA polymerase II?",
      a: [
        "Botulinum toxin",
        "Diphtheria toxin",
        "α-Amanitin",
        "Cholera toxin",
        "Tetanus toxin",
      ],
      correct: 2,
    },
    {
      q: "Which antibiotic inhibits RNA polymerase in both prokaryotes and eukaryotes?",
      a: [
        "Rifampicin",
        "Penicillin",
        "Actinomycin D",
        "Vancomycin",
        "Ciprofloxacin",
      ],
      correct: 2,
    },
    {
      q: "How many standard amino acids are used in protein synthesis?",
      a: ["16", "18", "20", "22", "64"],
      correct: 2,
    },
    {
      q: "How many possible codons are present in the genetic code?",
      a: ["20", "32", "61", "64", "128"],
      correct: 3,
    },
    {
      q: "How many different nucleotides are found in mRNA?",
      a: ["2", "3", "4", "5", "20"],
      correct: 2,
    },
    {
      q: "Which of the following is the universal start codon?",
      a: ["UAA", "AUG", "UAG", "UGA", "GUG"],
      correct: 1,
    },
    {
      q: "Which of the following is a stop codon?",
      a: ["AUG", "GUG", "UAA", "ACG", "CUG"],
      correct: 2,
    },
    {
      q: "Which of the following is also a stop codon?",
      a: ["UGA", "AUG", "GGG", "AAA", "ACC"],
      correct: 0,
    },
    {
      q: "Which of the following is the third stop codon?",
      a: ["AUG", "UAG", "GCG", "UGG", "AGG"],
      correct: 1,
    },
    {
      q: "The ability of different codons to code for the same amino acid is known as:",
      a: [
        "Complementarity",
        "Degeneracy (wobble)",
        "Replication",
        "Mutation",
        "Transcription",
      ],
      correct: 1,
    },
    {
      q: "Which RNA carries amino acids to the ribosome during translation?",
      a: ["mRNA", "rRNA", "tRNA", "snRNA", "miRNA"],
      correct: 2,
    },
    {
      q: "In tRNA, which loop is recognized by aminoacyl-tRNA synthetase?",
      a: [
        "T loop",
        "Anticodon loop",
        "D loop",
        "Variable loop",
        "Acceptor stem",
      ],
      correct: 2,
    },
    {
      q: "Which tRNA loop helps bind the tRNA to the ribosome?",
      a: [
        "D loop",
        "Anticodon loop",
        "T loop",
        "Variable loop",
        "Acceptor stem",
      ],
      correct: 2,
    },
    {
      q: "Which RNA carries the genetic information from DNA to the ribosome?",
      a: ["tRNA", "rRNA", "mRNA", "snRNA", "miRNA"],
      correct: 2,
    },
  ],

  cellb8: [
    {
      q: "The 5′ cap added during post-transcriptional modification contains:",
      a: ["Adenine", "Guanine", "7-Methylguanosine", "Cytosine", "Uracil"],
      correct: 2,
    },
    {
      q: "Polyadenylation of mRNA consists of adding:",
      a: [
        "5–10 adenines",
        "20–30 adenines",
        "50–200 adenines",
        "300 adenines",
        "500 adenines",
      ],
      correct: 2,
    },
    {
      q: "Translation takes place in the:",
      a: ["Nucleus", "Golgi apparatus", "Ribosomes", "Lysosomes", "Smooth ER"],
      correct: 2,
    },
    {
      q: "During translation, ribosomes ensure the correct alignment of:",
      a: [
        "DNA and RNA",
        "mRNA and tRNA",
        "DNA and tRNA",
        "mRNA and rRNA only",
        "Proteins and DNA",
      ],
      correct: 1,
    },
    {
      q: "Which ribosomal site receives the incoming aminoacyl-tRNA where codon-anticodon pairing occurs?",
      a: ["E site", "P site", "A site", "Exit site", "Catalytic site"],
      correct: 2,
    },
    {
      q: "During elongation, the growing peptide chain is primarily located in the:",
      a: ["A site", "P site", "E site", "D site", "T site"],
      correct: 1,
    },
    {
      q: "Through which ribosomal site does the empty tRNA leave the ribosome?",
      a: ["A site", "P site", "E site", "D site", "M site"],
      correct: 2,
    },
    {
      q: "Glycosylation, phosphorylation, acetylation, ubiquitination, ADP-ribosylation, methylation, and hydroxylation are all examples of:",
      a: [
        "DNA repair mechanisms",
        "Post-transcriptional modifications",
        "Post-translational modifications",
        "DNA replication steps",
        "RNA processing",
      ],
      correct: 2,
    },
    {
      q: "What is a sequence of nucleotides in DNA?",
      a: ["Chromosome", "Gene", "Allele", "Genome", "Locus"],
      correct: 1,
    },
    {
      q: "What is a locus?",
      a: [
        "A mutation in DNA",
        "A chromosome arm",
        "Physical location of a gene on a chromosome",
        "A DNA replication site",
        "A protein-coding sequence",
      ],
      correct: 2,
    },
    {
      q: "What is the complete set of chromosomes in the cell nucleus, described both qualitatively and quantitatively?",
      a: ["Genome", "Genotype", "Karyotype", "Chromatid", "Haplotype"],
      correct: 2,
    },
    {
      q: "What is the frequency with which a specific allele manifests its effect among individuals of a population?",
      a: [
        "Expressivity",
        "Pleiotropy",
        "Penetrance",
        "Anticipation",
        "Mosaicism",
      ],
      correct: 2,
    },
    {
      q: "What indicates how often a disease appears among individuals carrying a specific allele?",
      a: [
        "Expressivity",
        "Penetrance",
        "Dominance",
        "Codominance",
        "Heterogeneity",
      ],
      correct: 1,
    },
    {
      q: "What is the degree to which a particular allele is phenotypically expressed among different individuals?",
      a: [
        "Penetrance",
        "Expressivity",
        "Mosaicism",
        "Pleiotropy",
        "Heteroplasmy",
      ],
      correct: 1,
    },
    {
      q: "In which type of chromosome is the centromere located in the middle, dividing the chromosome into two equal arms?",
      a: [
        "Acrocentric",
        "Telocentric",
        "Metacentric",
        "Submetacentric",
        "Holocentric",
      ],
      correct: 2,
    },
    {
      q: "In which type of chromosome is the centromere slightly off-center, resulting in unequal arms?",
      a: [
        "Acrocentric",
        "Metacentric",
        "Submetacentric",
        "Telocentric",
        "Holocentric",
      ],
      correct: 2,
    },
    {
      q: "In which type of chromosome is the p arm extremely short compared with the q arm and may contain a satellite segment?",
      a: [
        "Metacentric",
        "Submetacentric",
        "Acrocentric",
        "Telocentric",
        "Dicentric",
      ],
      correct: 2,
    },
    {
      q: "Gametes are formed by meiosis and contain a haploid number of chromosomes. How many chromosomes do human gametes contain?",
      a: ["22", "23", "44", "46", "48"],
      correct: 1,
    },
    {
      q: "Somatic cells divide through:",
      a: ["Meiosis I", "Meiosis II", "Mitosis", "Binary fission", "Amitosis"],
      correct: 2,
    },
    {
      q: "Somatic cells contain:",
      a: [
        "Haploid chromosome set",
        "Triploid chromosome set",
        "Diploid chromosome set",
        "Tetraploid chromosome set",
        "Monoploid chromosome set",
      ],
      correct: 2,
    },
    {
      q: "What is it called when a single gene influences two or more distinct phenotypic traits?",
      a: [
        "Penetrance",
        "Pleiotropy",
        "Mosaicism",
        "Heteroplasmy",
        "Anticipation",
      ],
      correct: 1,
    },
    {
      q: "What is the phenomenon in which the severity of a genetic mutation increases when the mutated gene is passed from parent to offspring?",
      a: [
        "Pleiotropy",
        "Penetrance",
        "Anticipation",
        "Mosaicism",
        "Heterodisomy",
      ],
      correct: 2,
    },
    {
      q: "The increasing severity seen in Huntington disease and myotonic dystrophy across generations is called:",
      a: [
        "Expressivity",
        "Anticipation",
        "Mosaicism",
        "Heteroplasmy",
        "Penetrance",
      ],
      correct: 1,
    },
    {
      q: "What is the presence of genetically distinct cell populations within an organism?",
      a: ["Heteroplasmy", "Mosaicism", "Chimerism", "Pleiotropy", "Isodisomy"],
      correct: 1,
    },
    {
      q: "Down syndrome, McCune-Albright syndrome, Turner syndrome, and Klinefelter syndrome may exhibit:",
      a: [
        "Penetrance",
        "Expressivity",
        "Mosaicism",
        "Anticipation",
        "Heteroplasmy",
      ],
      correct: 2,
    },
    {
      q: "What is it called when different mutations within the same gene produce a similar phenotypic outcome?",
      a: [
        "Locus heterogeneity",
        "Allelic heterogeneity",
        "Mosaicism",
        "Heteroplasmy",
        "Pleiotropy",
      ],
      correct: 1,
    },
    {
      q: "Alkaptonuria, cystic fibrosis, and β-thalassemia are examples of:",
      a: [
        "Locus heterogeneity",
        "Allelic heterogeneity",
        "Anticipation",
        "Mosaicism",
        "Expressivity",
      ],
      correct: 1,
    },
    {
      q: "What is it called when the same phenotype is produced by mutations in different genes or loci?",
      a: [
        "Allelic heterogeneity",
        "Locus heterogeneity",
        "Penetrance",
        "Heteroplasmy",
        "Pleiotropy",
      ],
      correct: 1,
    },
    {
      q: "Cornelia de Lange syndrome, albinism, retinitis pigmentosa, and familial hypercholesterolemia are examples of:",
      a: [
        "Allelic heterogeneity",
        "Locus heterogeneity",
        "Anticipation",
        "Mosaicism",
        "Expressivity",
      ],
      correct: 1,
    },
    {
      q: "What is the presence of different forms of mitochondrial DNA (mtDNA) within a single cell called?",
      a: ["Mosaicism", "Heteroplasmy", "Isodisomy", "Pleiotropy", "Penetrance"],
      correct: 1,
    },
  ],

  cellb9: [
    {
      q: "Isodisomy involves two identical chromosome copies from one parent and usually results from:",
      a: [
        "Mitosis error",
        "Meiosis I error",
        "Meiosis II error",
        "DNA replication error",
        "Crossing over",
      ],
      correct: 2,
    },
    {
      q: "Heterodisomy involves two different homologous chromosomes from one parent and usually results from:",
      a: [
        "Mitosis error",
        "Meiosis I error",
        "Meiosis II error",
        "DNA repair error",
        "Gene conversion",
      ],
      correct: 1,
    },
    {
      q: "What law is used to determine the frequency of genotypes and alleles in a population?",
      a: [
        "Mendel's Law of Segregation",
        "Hardy–Weinberg Law",
        "Law of Independent Assortment",
        "Law of Dominance",
        "Chromosome Theory of Inheritance",
      ],
      correct: 1,
    },
    {
      q: "What refers to random changes in allele frequencies from one generation to the next due to chance events?",
      a: [
        "Gene flow",
        "Natural selection",
        "Gene drift",
        "Mutation",
        "Genetic recombination",
      ],
      correct: 2,
    },
    {
      q: "Which is a clear example of gene drift that occurs when population size drastically decreases?",
      a: [
        "Founder effect",
        "Natural selection",
        "Bottleneck effect",
        "Gene flow",
        "Mutation",
      ],
      correct: 2,
    },
    {
      q: "Which is an example of gene drift that occurs when a small group separates from a larger population to establish a new colony?",
      a: [
        "Bottleneck effect",
        "Founder effect",
        "Crossing over",
        "Genetic recombination",
        "Natural selection",
      ],
      correct: 1,
    },
    {
      q: "Prader–Willi syndrome and Angelman syndrome are examples of:",
      a: [
        "Trinucleotide repeat disorders",
        "Imprinting diseases",
        "Mitochondrial diseases",
        "Autosomal dominant diseases",
        "X-linked recessive diseases",
      ],
      correct: 1,
    },
    {
      q: "In Prader–Willi syndrome, the chromosome loss or mutation affects the:",
      a: [
        "Maternal chromosome 15",
        "Paternal chromosome 15",
        "Maternal X chromosome",
        "Paternal Y chromosome",
        "Chromosome 21",
      ],
      correct: 1,
    },
    {
      q: "What is the disorder caused by a mutation in the maternal UBE3A gene on chromosome 15?",
      a: [
        "Prader–Willi syndrome",
        "Angelman syndrome",
        "Rett syndrome",
        "Fragile X syndrome",
        "Down syndrome",
      ],
      correct: 1,
    },
    {
      q: "In which type of inheritance does a child develop the disease after inheriting one mutated gene from either parent?",
      a: [
        "Autosomal recessive",
        "X-linked recessive",
        "Autosomal dominant",
        "Mitochondrial inheritance",
        "Y-linked inheritance",
      ],
      correct: 2,
    },
    {
      q: "Marfan syndrome, Huntington disease, polycystic kidney disease, and achondroplasia are examples of:",
      a: [
        "Autosomal recessive diseases",
        "Autosomal dominant diseases",
        "X-linked recessive diseases",
        "X-linked dominant diseases",
        "Mitochondrial diseases",
      ],
      correct: 1,
    },
    {
      q: "In which type of inheritance must a child inherit two mutated copies of a gene to develop the disease?",
      a: [
        "Autosomal dominant",
        "X-linked dominant",
        "Autosomal recessive",
        "Mitochondrial inheritance",
        "Y-linked inheritance",
      ],
      correct: 2,
    },
    {
      q: "Phenylketonuria, sickle cell anemia, thalassemia, Tay–Sachs disease, and Wilson disease are examples of:",
      a: [
        "Autosomal dominant diseases",
        "Autosomal recessive diseases",
        "X-linked dominant diseases",
        "X-linked recessive diseases",
        "Mitochondrial diseases",
      ],
      correct: 1,
    },
    {
      q: "Bruton agammaglobulinemia, Duchenne and Becker muscular dystrophies, Fabry disease, hemophilia A and B, and ocular albinism are examples of:",
      a: [
        "Autosomal dominant diseases",
        "Autosomal recessive diseases",
        "X-linked dominant diseases",
        "X-linked recessive diseases",
        "Mitochondrial diseases",
      ],
      correct: 3,
    },
    {
      q: "In X-linked dominant inheritance, if the father is affected and the mother is healthy, all daughters will be:",
      a: [
        "Healthy",
        "Carriers only",
        "Affected",
        "Unaffected carriers",
        "Either healthy or affected with equal probability",
      ],
      correct: 2,
    },
    {
      q: "In X-linked dominant inheritance, if the father is affected and the mother is healthy, all sons will be:",
      a: [
        "Affected",
        "Carriers",
        "Healthy",
        "Have a 50% risk of disease",
        "Mosaic",
      ],
      correct: 2,
    },
    {
      q: "Fragile X syndrome, Alport syndrome, and hypophosphatemic rickets are examples of:",
      a: [
        "Autosomal recessive diseases",
        "Autosomal dominant diseases",
        "X-linked dominant diseases",
        "X-linked recessive diseases",
        "Mitochondrial diseases",
      ],
      correct: 2,
    },
    {
      q: "Fragile X syndrome results from a mutation in the:",
      a: ["HTT gene", "DMPK gene", "FMR1 gene", "FXN gene", "CFTR gene"],
      correct: 2,
    },
    {
      q: "Compared with nuclear DNA, mitochondrial DNA does not contain:",
      a: ["RNA", "Histones", "Adenine", "Cytosine", "Ribose"],
      correct: 1,
    },
    {
      q: "In mitochondrial DNA, which codons function as stop codons?",
      a: [
        "UAA and UAG",
        "UGA and UAA",
        "AGA and AGG",
        "AUG and UGA",
        "UAG and AGG",
      ],
      correct: 2,
    },
    {
      q: "Which of the following is a mitochondrial disease?",
      a: [
        "Marfan syndrome",
        "MELAS",
        "Hemophilia A",
        "Tay–Sachs disease",
        "Achondroplasia",
      ],
      correct: 1,
    },
    {
      q: "Which of the following is a mitochondrial disease?",
      a: [
        "Leber hereditary optic neuropathy (LHON)",
        "Huntington disease",
        "Down syndrome",
        "Phenylketonuria",
        "Fragile X syndrome",
      ],
      correct: 0,
    },
    {
      q: "Which of the following is a mitochondrial disease?",
      a: [
        "Myoclonic epilepsy with ragged red fibers (MERRF)",
        "Cystic fibrosis",
        "Wilson disease",
        "Duchenne muscular dystrophy",
        "Alkaptonuria",
      ],
      correct: 0,
    },
    {
      q: "Which mitochondrial disease is characterized by sudden, painless bilateral vision loss in late adolescence or early adulthood?",
      a: [
        "MELAS",
        "MERRF",
        "Leber hereditary optic neuropathy (LHON)",
        "Kearns–Sayre syndrome",
        "Leigh syndrome",
      ],
      correct: 2,
    },
    {
      q: "What is an abnormally increased number of repeating three-nucleotide sequences in genes called?",
      a: [
        "Gene duplication",
        "Trinucleotide repeat disorder",
        "Mosaicism",
        "Robertsonian translocation",
        "Heteroplasmy",
      ],
      correct: 1,
    },
    {
      q: "Which of the following is a trinucleotide repeat disorder?",
      a: [
        "Huntington disease, Myotonic dystrophy type 1, Friedreich ataxia, and Fragile X syndrome",
        "Down syndrome, Turner syndrome, and Klinefelter syndrome",
        "Marfan syndrome, Achondroplasia, and PKD",
        "Hemophilia A, Fabry disease, and DMD",
        "Cystic fibrosis, PKU, and Wilson disease",
      ],
      correct: 0,
    },
    {
      q: "Huntington disease results from expansion of which trinucleotide repeat?",
      a: ["CGG", "CTG", "CAG", "GAA", "GCG"],
      correct: 2,
    },
    {
      q: "Huntington disease is caused by CAG repeat expansion in the:",
      a: [
        "FMR1 gene on chromosome X",
        "DMPK gene on chromosome 19",
        "HTT gene on chromosome 4",
        "FXN gene on chromosome 9",
        "CFTR gene on chromosome 7",
      ],
      correct: 2,
    },
    {
      q: "The CAG codon codes for which amino acid?",
      a: ["Glycine", "Lysine", "Glutamine", "Alanine", "Serine"],
      correct: 2,
    },
    {
      q: "Which trinucleotide repeat disorder primarily damages the basal ganglia and causes neuronal atrophy?",
      a: [
        "Fragile X syndrome",
        "Friedreich ataxia",
        "Huntington disease",
        "Myotonic dystrophy type 1",
        "MELAS",
      ],
      correct: 2,
    },
  ],
  cellb10: [
    {
      q: "Myotonic dystrophy type 1 results from expansion of which trinucleotide repeat in the 3′ UTR?",
      a: ["CGG", "GAA", "CTG", "CAG", "GCG"],
      correct: 2,
    },
    {
      q: "Myotonic dystrophy type 1 is caused by mutation in the:",
      a: ["HTT gene", "DMPK gene", "FMR1 gene", "FXN gene", "BRCA1 gene"],
      correct: 1,
    },
    {
      q: "Friedreich ataxia is caused by expansion of which trinucleotide repeat?",
      a: ["CAG", "CGG", "GAA", "CTG", "GCG"],
      correct: 2,
    },
    {
      q: "Which disease is caused by GAA repeat expansion in the intron of the frataxin (FXN) gene on chromosome 9?",
      a: [
        "Huntington disease",
        "Fragile X syndrome",
        "Friedreich ataxia",
        "Myotonic dystrophy type 1",
        "MELAS",
      ],
      correct: 2,
    },
    {
      q: "Fragile X syndrome develops due to expansion of which trinucleotide repeat?",
      a: ["CAG", "GAA", "CGG", "CTG", "GCG"],
      correct: 2,
    },
    {
      q: "In Fragile X syndrome, the CGG repeat expansion occurs in the:",
      a: [
        "Exon region",
        "Intron region",
        "5′ promoter region",
        "3′ UTR",
        "Mitochondrial genome",
      ],
      correct: 2,
    },
    {
      q: "Which disease results from CGG repeat expansion in the FMR1 gene on the X chromosome?",
      a: [
        "Huntington disease",
        "Friedreich ataxia",
        "Fragile X syndrome",
        "Myotonic dystrophy type 1",
        "Edwards syndrome",
      ],
      correct: 2,
    },
    {
      q: "What is the second most common genetic cause of intellectual disability after Down syndrome?",
      a: [
        "Phenylketonuria",
        "Huntington disease",
        "Fragile X syndrome",
        "Tay–Sachs disease",
        "Marfan syndrome",
      ],
      correct: 2,
    },
    {
      q: "What is an increase of one chromosome called?",
      a: ["Monosomy", "Trisomy", "Polyploidy", "Euploidy", "Haploidy"],
      correct: 1,
    },
    {
      q: "Trisomy of chromosome 21 is called:",
      a: [
        "Edwards syndrome",
        "Patau syndrome",
        "Down syndrome",
        "Turner syndrome",
        "Klinefelter syndrome",
      ],
      correct: 2,
    },
    {
      q: "Trisomy of chromosome 18 is called:",
      a: [
        "Down syndrome",
        "Edwards syndrome",
        "Patau syndrome",
        "Cri-du-chat syndrome",
        "Turner syndrome",
      ],
      correct: 1,
    },
    {
      q: "Trisomy of chromosome 13 is called:",
      a: [
        "Edwards syndrome",
        "Down syndrome",
        "Patau syndrome",
        "Klinefelter syndrome",
        "Turner syndrome",
      ],
      correct: 2,
    },
    {
      q: "What occurs when the long arm of one acrocentric chromosome joins the long arm of another acrocentric chromosome to form a single chromosome?",
      a: [
        "Reciprocal translocation",
        "Inversion",
        "Robertsonian translocation",
        "Deletion",
        "Duplication",
      ],
      correct: 2,
    },
    {
      q: "Which chromosomes are acrocentric and can participate in Robertsonian translocation?",
      a: [
        "1, 2, 3, 4, 5",
        "6, 7, 8, 9, 10",
        "11, 12, 16, 17, 18",
        "13, 14, 15, 21, 22",
        "X, Y, 19, 20, 21",
      ],
      correct: 3,
    },
    {
      q: "What leads to abnormal chromosome numbers when sister chromatids fail to separate normally during meiosis I or II?",
      a: [
        "Crossing over",
        "Robertsonian translocation",
        "Nondisjunction during meiosis",
        "Gene conversion",
        "Mosaicism",
      ],
      correct: 2,
    },
    {
      q: "What occurs when a female has only one X chromosome or a defective second X chromosome?",
      a: [
        "Triple X syndrome",
        "Klinefelter syndrome",
        "Turner syndrome",
        "XYY syndrome",
        "Down syndrome",
      ],
      correct: 2,
    },
    {
      q: "What is the condition in which a male has an extra X chromosome?",
      a: [
        "Turner syndrome",
        "Triple X syndrome",
        "Klinefelter syndrome",
        "XYY syndrome",
        "Edwards syndrome",
      ],
      correct: 2,
    },
    {
      q: "What is the condition in which a female has an extra X chromosome and may have tall stature with mild intellectual disability?",
      a: [
        "Turner syndrome",
        "Klinefelter syndrome",
        "Triple X syndrome (47,XXX)",
        "XYY syndrome",
        "Down syndrome",
      ],
      correct: 2,
    },
    {
      q: "What is the condition in which a male has an extra Y chromosome?",
      a: [
        "Turner syndrome",
        "Klinefelter syndrome",
        "Triple X syndrome",
        "XYY syndrome (47,XYY)",
        "Patau syndrome",
      ],
      correct: 3,
    },
    {
      q: "In which syndrome is a Barr body (an inactive X chromosome) typically present because of an extra X chromosome?",
      a: [
        "Turner syndrome",
        "Down syndrome",
        "Klinefelter syndrome",
        "XYY syndrome",
        "Edwards syndrome",
      ],
      correct: 2,
    },
  ],
};
