window.TEST_QUESTIONS = {
  L6: [
    {
      q: "At which vertebral level does the aorta pass through the diaphragm?",
      a: ["T8", "T10", "T12", "L1", "L4"],
      correct: 2,
    },
    {
      q: "Into which arteries does the abdominal aorta bifurcate?",
      a: [
        "Renal arteries",
        "Common iliac arteries",
        "Lumbar arteries",
        "Middle suprarenal arteries",
        "Inferior phrenic arteries",
      ],
      correct: 1,
    },
    {
      q: "Which arteries arise immediately below the aortic hiatus to supply the diaphragm?",
      a: [
        "Renal arteries",
        "Inferior phrenic arteries",
        "Lumbar arteries",
        "Middle suprarenal arteries",
        "Ovarian arteries",
      ],
      correct: 1,
    },
    {
      q: "The left inferior phrenic artery passes posterior to which structure?",
      a: ["Inferior vena cava", "Esophagus", "Aorta", "Duodenum", "Renal vein"],
      correct: 1,
    },
    {
      q: "Middle suprarenal arteries arise from which vessel?",
      a: [
        "Aorta",
        "Renal artery",
        "Inferior vena cava",
        "Common iliac artery",
        "Hepatic artery",
      ],
      correct: 0,
    },
    {
      q: "Which artery is longer and slightly lower than its counterpart?",
      a: [
        "Left renal artery",
        "Right renal artery",
        "Left ovarian artery",
        "Right ovarian artery",
        "Middle suprarenal artery",
      ],
      correct: 1,
    },
    {
      q: "Renal arteries give rise to which branches?",
      a: [
        "Superior and middle suprarenal arteries",
        "Inferior suprarenal and ureteric arteries",
        "Lumbar arteries",
        "Ovarian arteries",
        "Testicular arteries",
      ],
      correct: 1,
    },
    {
      q: "The testicular artery supplies which of the following?",
      a: [
        "Ovary",
        "Spermatic cord, epididymis, and testis",
        "Kidney",
        "Ureter",
        "Bladder",
      ],
      correct: 1,
    },
    {
      q: "Lumbar arteries pass posterior to which structure on the right side?",
      a: [
        "Aorta",
        "Inferior vena cava",
        "Psoas major",
        "Quadratus lumborum",
        "Transverse abdominal muscle",
      ],
      correct: 1,
    },
    {
      q: "The middle sacral artery arises from which location?",
      a: [
        "Aortic bifurcation",
        "Superior mesenteric artery",
        "Renal artery",
        "Inferior phrenic artery",
        "Common iliac artery",
      ],
      correct: 0,
    },
    {
      q: "The inferior vena cava is formed at which vertebral level?",
      a: ["L3", "L4", "L5", "T12", "T10"],
      correct: 2,
    },
    {
      q: "Which veins drain into the inferior vena cava?",
      a: [
        "Renal, gonadal, suprarenal, and inferior phrenic veins",
        "Portal veins only",
        "Lumbar veins only",
        "Hepatic veins only",
        "Splenic veins only",
      ],
      correct: 0,
    },
    {
      q: "The left renal vein passes between which arteries?",
      a: [
        "Superior mesenteric and aorta",
        "Aorta and inferior vena cava",
        "Renal artery and aorta",
        "Gonadal artery and vein",
        "Lumbar artery and vein",
      ],
      correct: 0,
    },
    {
      q: "Cisterna chyli lies in relation to the aorta where?",
      a: [
        "Anterior and right",
        "Posterior and left",
        "Posterior and right",
        "Anterior and left",
        "Anterior only",
      ],
      correct: 2,
    },
    {
      q: "Preaortic lymph nodes drain lymph from which organs?",
      a: [
        "GI tract, spleen, pancreas, gallbladder, liver",
        "Kidneys and adrenals",
        "Testes or ovaries",
        "Pelvis only",
        "Thorax",
      ],
      correct: 0,
    },
    {
      q: "Para-aortic lymph nodes drain lymph from which structures?",
      a: [
        "GI tract",
        "Kidneys, suprarenals, gonads, uterus, uterine tubes",
        "Liver only",
        "Spleen only",
        "Stomach only",
      ],
      correct: 1,
    },
    {
      q: "Lumbar plexus is formed by which nerves?",
      a: [
        "Ventral rami of L1-L4",
        "Dorsal rami of L1-L5",
        "Ventral rami of L1-L3 plus part of L4",
        "L2-L5 only",
        "Sacral nerves only",
      ],
      correct: 2,
    },
    {
      q: "Subcostal nerve (T12) innervates which muscles?",
      a: [
        "Rectus abdominis, external oblique, internal oblique, transverse abdominal, pyramidalis",
        "Psoas major only",
        "Quadratus lumborum only",
        "Gluteus muscles",
        "Iliacus only",
      ],
      correct: 0,
    },
    {
      q: "Iliohypogastric nerve provides cutaneous innervation to which areas?",
      a: [
        "Anterior pubis and lateral gluteal region",
        "Anterior thigh only",
        "Scrotum only",
        "Labium majus only",
        "Umbilical region only",
      ],
      correct: 0,
    },
    {
      q: "Ilioinguinal nerve travels through which structure?",
      a: [
        "Femoral triangle",
        "Inguinal canal",
        "Obturator foramen",
        "Pelvic cavity",
        "Sacral hiatus",
      ],
      correct: 1,
    },
    {
      q: "Genitofemoral nerve genital branch innervates what?",
      a: [
        "Cremaster muscle and scrotum/labium majus",
        "Quadriceps",
        "Adductors of thigh",
        "Rectus abdominis",
        "Transverse abdominal muscle",
      ],
      correct: 0,
    },
    {
      q: "Lateral femoral cutaneous nerve provides sensory innervation to:",
      a: [
        "Anterior and lateral thigh",
        "Medial thigh",
        "Posterior thigh",
        "Gluteal region",
        "Lower leg",
      ],
      correct: 0,
    },
    {
      q: "Femoral nerve innervates which muscles?",
      a: [
        "Quadriceps femoris, pectineus, sartorius",
        "Adductor longus and magnus",
        "Gluteus maximus",
        "Obturator externus",
        "Iliopsoas only",
      ],
      correct: 0,
    },
    {
      q: "Obturator nerve innervates which muscle group?",
      a: [
        "Quadriceps",
        "Adductors of thigh",
        "Gluteals",
        "Hamstrings",
        "Psoas only",
      ],
      correct: 1,
    },
    {
      q: "Accessory obturator nerve is present in approximately what percentage of people?",
      a: ["1%", "5%", "9%", "15%", "20%"],
      correct: 2,
    },
    {
      q: "Lumbosacral trunk contributes to the formation of which plexus?",
      a: [
        "Lumbar plexus",
        "Sacral plexus",
        "Cervical plexus",
        "Brachial plexus",
        "Coccygeal plexus",
      ],
      correct: 1,
    },
    {
      q: "Renal arteries give rise to which arteries supplying the adrenals?",
      a: [
        "Superior suprarenal arteries",
        "Inferior suprarenal arteries",
        "Middle suprarenal arteries",
        "Phrenic arteries",
        "Lumbar arteries",
      ],
      correct: 1,
    },
    {
      q: "Which arteries descend retroperitoneally along the psoas major?",
      a: [
        "Testicular or ovarian arteries",
        "Renal arteries",
        "Lumbar arteries",
        "Inferior phrenic arteries",
        "Middle sacral artery",
      ],
      correct: 0,
    },
    {
      q: "Middle sacral artery anastomoses with which arteries?",
      a: [
        "Lateral sacral and superior/inferior rectal arteries",
        "Renal arteries",
        "Lumbar arteries",
        "Gonadal arteries",
        "Inferior phrenic arteries",
      ],
      correct: 0,
    },
  ],
};
