// ============================================================
//  PULSE GO — TEST GROUPS & CARDS DATA
//  course: 1 | 2 | 3  — used by the wizard
//  img: optional cover image for product-style cards
// ============================================================

window.testGroups = [
  {
    id: "cellbiology",
    title: "Hujayra biologiyasi",
    subtitle: "Mavzular bo'yicha testlar",
    totalQuestions: 559,
    icon: "bi-virus",
    color: "success",
    course: 1,
    tests: [
      {
        id: "cellbio-all",
        title: "Cellbio Grant uchun",
        count: "290 ta",
        url: "/cellbiology",
        img: "./assets/hujayra2.png",
        tags: ["grant", "grand"],
      },
      {
        id: "cellbio-bytopics",
        title: "Mavzular bo'yicha testlar",
        count: "269 ta",
        url: "/cellbiology/bytopics.html",
        img: "./assets/hujayra2.png",
        tags: ["topics", "mavzu"],
      },
    ],
  },
  {
    id: "anatomy1",
    title: "Anatomiya",
    subtitle: "Mavzular bo'yicha testlar",
    totalQuestions: "Tez orada",
    icon: "bi-heart-pulse",
    color: "danger",
    course: 1,
    tests: [],
  },
  {
    id: "anatomy2",
    title: "Anatomiya 2-semester",
    subtitle: "Mavzular bo'yicha testlar",
    totalQuestions: 1000,
    icon: "bi-heart-pulse",
    color: "danger",
    course: 2,
    tests: [
      {
        id: "anatomy-all",
        title: "Barcha anatomiya testlari",
        count: "454 ta",
        url: "/anatomy",
        img: "./assets/anat1.png",
        tags: ["all"],
      },
      {
        id: "anatomy-yn",
        title: "Yakuniy rasmli testlar",
        count: "500+ ta",
        url: "/anatomy/yn/",
        img: "./assets/anat.png",
        tags: ["yn", "yakuniy"],
      },
    ],
  },
  {
    id: "anatomy3",
    title: "Anatomiya 3-semester",
    subtitle: "Mavzular bo'yicha testlar",
    totalQuestions: "Tez orada",
    icon: "bi-heart-pulse",
    color: "danger",
    course: 3,
    tests: [],
  },
  {
    id: "embriology2",
    title: "Embriologiya 2-semester",
    subtitle: "Mavzular bo'yicha testlar",
    totalQuestions: 350,
    icon: "bi-baby",
    color: "warning",
    course: 2,
    tests: [
      {
        id: "embryo-all",
        title: "Caselar (Mavzular bo'yicha)",
        count: "300+ ta",
        url: "/embriology",
        img: "/assets/img/tests/embryo-all.jpg",
        tags: ["all", "topics", "mavzu", "cases"],
      },
      {
        id: "embryo-cases",
        title: "Uworld caselari",
        count: "50+ ta",
        url: "/embriology/cases.html",
        img: "/assets/img/tests/embryo-cases.jpg",
        tags: ["cases", "case"],
      },
    ],
  },
  {
    id: "embriology3",
    title: "Embriologiya 3-semester",
    subtitle: "Mavzular bo'yicha testlar",
    totalQuestions: "Tez orada",
    icon: "bi-baby",
    color: "warning",
    course: 3,
    tests: [
      {
        id: "embryo-all",
        title: "Mavzular bo'yicha testlar",
        count: "250+ ta",
        url: "",
        img: "/assets/img/tests/chem-all.jpg",
        tags: ["topics", "mavzu"],
      },
      {
        id: "embryo-bytopics",
        title: "Caselar (Mavzular bo'yicha)",
        count: "250+ ta",
        url: "",
        img: "/assets/img/tests/chem-topics.jpg",
        tags: ["topics", "mavzu", "cases"],
      },
      {
        id: "embryo-yn",
        title: "Real tushgan YN testlar",
        count: "150+ ta",
        url: "",
        img: "/assets/img/tests/chem-topics.jpg",
        tags: ["yn", "yakuniy"],
      },
    ],
  },
  {
    id: "chemistry",
    title: "Biokimyo",
    subtitle: "Mavzular bo'yicha testlar",
    totalQuestions: 250,
    icon: "bi-flask",
    color: "info",
    course: 2,
    tests: [
      {
        id: "chem-all",
        title: "Mavzular bo'yicha testlar",
        count: "250+ ta",
        url: "/chemistry",
        img: "/assets/img/tests/chem-all.jpg",
        tags: ["topics", "mavzu"],
      },
      {
        id: "biochem-bytopics",
        title: "Caselar (Mavzular bo'yicha)",
        count: "250+ ta",
        url: "/chemistry/book.html",
        img: "/assets/img/tests/chem-topics.jpg",
        tags: ["topics", "mavzu", "cases"],
      },
      {
        id: "biochem-yn",
        title: "Real tushgan YN testlar",
        count: "150+ ta",
        url: "",
        img: "/assets/img/tests/chem-topics.jpg",
        tags: ["yn", "yakuniy"],
      },
    ],
  },
  {
    id: "cases",
    title: "Caselar",
    subtitle: "Klinik vaziyatlar bo'yicha testlar",
    totalQuestions: 100,
    icon: "bi-journal-text",
    color: "primary",
    course: 0, // all courses
    tests: [
      {
        id: "cases-all",
        title: "Barcha caselar",
        count: "100+ ta",
        url: "/cases",
        img: "./assets/cases.png",
        tags: ["cases", "case"],
      },
    ],
  },
];
