// ============================================================
//  PULSE GO — PREPARATION DATA
//  Edit this file to add / remove / update exam types and subjects.
// ============================================================

const PREP_EXAM_TYPES = [
  { id: "final", title: "Final Exam" },
  { id: "grant", title: "Grant Exam" },
];

const PREP_SUBJECTS = [
  {
    id: "anatomy",
    title: "Anatomiya",
    subtitle: "Mavzular bo'yicha testlar",
    icon: "bi-heart-pulse",
    color: "danger",
    script: "/anatomy/tests.js",
    page: "/anatomy/",
    tests: [
      { id: "mock1", title: "Peritoneum", count: 20 },
      { id: "mock2", title: "Anatomy Chapter 1", count: 20 },
      { id: "mock3", title: "Accessory GI Organs", count: 20 },
      { id: "mock4", title: "Celiac and Mesenteric Arteries", count: 20 },
      { id: "mock5", title: "Portal Vena", count: null },
      { id: "mock6", title: "Kidney (1)", count: 20 },
      { id: "mock7", title: "Kidney (2)", count: 20 },
      { id: "mock8", title: "Posterior Abdominal Wall Vessels", count: 20 },
      { id: "L22", title: "Upper Limb", count: 20 },
      { id: "mockUpperLimb2", title: "Upper Limb 2", count: 10 },
      { id: "mockLowerLimbArteries", title: "Lower Limb Arteries", count: 20 },
    ],
  },
  {
    id: "anatomy-yn",
    title: "Anatomiya Yakuniy",
    subtitle: "Yakuniy nazorat rasmli testlari",
    icon: "bi-journal-check",
    color: "danger",
    script: "/anatomy/imgtests.js",
    page: "/anatomy/yn/",
    tests: Array.from({ length: 15 }, (_, index) => ({
      id: `mock${index + 1}`,
      title: `Yakuniy test ${index + 1}`,
      count: null,
    })),
  },
  {
    id: "cellbiology",
    title: "Hujayra biologiyasi",
    subtitle: "Mavzular bo'yicha testlar",
    icon: "bi-virus",
    color: "success",
    script: "/cellbiology/tests.js",
    page: "/cellbiology/",
    tests: Array.from({ length: 11 }, (_, index) => ({
      id: `cellb${index + 1}`,
      title: `Bo'lim ${index + 1}`,
      count: null,
    })),
  },
  {
    id: "embriology",
    title: "Embriologiya",
    subtitle: "Mavzular bo'yicha testlar",
    icon: "bi-baby",
    color: "warning",
    script: "/embriology/tests.js",
    page: "/embriology/",
    tests: [
      { id: "u1", title: "Test 1", count: 17 },
      { id: "u2", title: "Test 2", count: 10 },
      { id: "u3", title: "Test 3", count: 16 },
      { id: "u4", title: "Test 4", count: 15 },
      { id: "u5", title: "Test 5", count: 36 },
      { id: "u6", title: "Test 6", count: 11 },
      { id: "u7", title: "Test 7", count: 23 },
      { id: "u8", title: "Test 8", count: 10 },
      { id: "u9", title: "Test 9", count: 10 },
      { id: "review", title: "Review", count: 35 },
    ],
  },
  {
    id: "embriology-cases",
    title: "Embriologiya caselar",
    subtitle: "Klinik vaziyatlar bo'yicha",
    icon: "bi-journal-text",
    color: "warning",
    script: "/embriology/cases.js",
    page: "/embriology/cases.html",
    tests: [
      { id: "c1", title: "Test 1", count: 20 },
      { id: "c2", title: "Test 2", count: 20 },
      { id: "c3", title: "Test 3", count: 20 },
      { id: "c4", title: "Test 4", count: 20 },
      { id: "c5", title: "Test 5", count: 22 },
      { id: "c6", title: "Test 6", count: 12 },
      { id: "c7", title: "Test 7", count: 7 },
      { id: "c8", title: "Test 8", count: 6 },
    ],
  },
  {
    id: "chemistry",
    title: "Kimyo",
    subtitle: "Mavzular bo'yicha testlar",
    icon: "bi-flask",
    color: "info",
    script: "/chemistry/tests.js",
    page: "/chemistry/",
    tests: [
      { id: "aminoacids", title: "Amino Acids", count: null },
      { id: "vitamins", title: "Vitamins", count: null },
      { id: "enzymes", title: "Enzymes", count: null },
      { id: "nucleicAcids", title: "Nucleic Acids", count: null },
      { id: "lipids", title: "Lipids", count: null },
      {
        id: "peptidesAndProteins",
        title: "Peptides and Proteins",
        count: null,
      },
      { id: "carbohydrates", title: "Carbohydrates", count: null },
      { id: "q50", title: "Q50", count: 30 },
      { id: "q100", title: "Q100", count: 30 },
      { id: "q150", title: "Q150", count: 30 },
      { id: "all", title: "All Questions", count: null },
      { id: "latin1", title: "Latin 1", count: null },
      { id: "latin2", title: "Latin 2", count: null },
      { id: "latin3", title: "Latin 3", count: null },
    ],
  },
];
