window.TEST_QUESTIONS = {
  mock1: [
    {
      q: "2?",
      photo: "../../anatomy/assets/img/image1.png",
      a: ["Jigar", "Oshqozon", "Buyrak", "Oshqozon osti bezi", "Taloq"],
      correct: 1,
    },
    {
      q: "hepar?",
      photo: "../../anatomy/assets/img/image1.png",
      a: ["2", "4", "3", "1"],
      correct: 1,
    },
    {
      q: "Greater omentum?",
      photo: "../../anatomy/assets/img/image1.png",
      a: ["2", "3", "4", "1"],
      correct: 1,
    },
    {
      q: "Hepar?",
      photo: "../../anatomy/assets/img/image2.png",
      a: ["1", "9", "8", "4", "7"],
      correct: 0,
    },
    {
      q: "2?",
      photo: "../../anatomy/assets/img/image2.png",
      a: [
        "Lesser omentum (kichik charvi)",
        "Greater omentum (katta charvi)",
        "Oshqozon",
        "Oshqozon osti bezi",
        "Ingichka ichak",
      ],
      correct: 0,
    },
    {
      q: "Lesser curvature (kichik egirlik?)",
      photo: "../../anatomy/assets/img/image2.png",
      a: ["3", "4", "2", "6", "5"],
      correct: 0,
    },
    {
      q: "Descending colon",
      photo: "../../anatomy/assets/img/image2.png",
      a: ["5", "6", "7", "9", "4"],
      correct: 0,
    },
    {
      q: "Ascending colon ",
      photo: "../../anatomy/assets/img/image2.png",
      a: ["6", "5", "7", "9", "4"],
      correct: 0,
    },
    {
      q: "Duodenum",
      photo: "../../anatomy/assets/img/image2.png",
      a: ["7", "5", "6", "9", "4"],
      correct: 0,
    },
    {
      q: "Omental foramen ",
      photo: "../../anatomy/assets/img/image2.png",
      a: ["8", "2", "7", "9", "4"],
      correct: 0,
    },
    {
      q: "Gallbladder",
      photo: "../../anatomy/assets/img/image2.png",
      a: ["9", "1", "8", "7", "4"],
      correct: 0,
    },
    {
      q: "Cardiac notch ( yurak o’ymasi)",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["1", "7", "6", "2", "3"],
      correct: 0,
    },
    {
      q: "Fundus",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["2", "7", "6", "4", "3"],
      correct: 0,
    },
    {
      q: "3?",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["corpus", "fundus", "pylorus", "cardia", "major curvature"],
      correct: 0,
    },
    {
      q: "Major  curvature",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["4", "8", "5", "2", "3"],
      correct: 0,
    },
    {
      q: "Pyloric antrum ",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["5", "6", "7", "1", "3"],
      correct: 0,
    },
    {
      q: "Pyloric canal ",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["6", "5", "7", "1", "3"],
      correct: 0,
    },
    {
      q: "Angular incisure",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["7", "5", "6", "1", "3"],
      correct: 0,
    },
    {
      q: "Minor curvature ",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["8", "4", "3", "6", "9"],
      correct: 0,
    },
    {
      q: "Cardia",
      photo: "../../anatomy/assets/img/image3.png",
      a: ["9", "2", "1", "7", "3"],
      correct: 0,
    },
    {
      q: "Ileum",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["1", "2", "8", "7", "5"],
      correct: 0,
    },
    {
      q: "Appendix",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["2", "1", "3", "7", "5"],
      correct: 0,
    },
    {
      q: "Cecum",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["3", "2", "4", "6", "10"],
      correct: 0,
    },
    {
      q: "Ascending colon",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["4", "8", "5", "9", "6"],
      correct: 0,
    },
    {
      q: "Right colic flexure",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["5", "7", "6", "4", "8"],
      correct: 0,
    },
    {
      q: "Transverse colon",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["6", "4", "8", "11", "9"],
      correct: 0,
    },
    {
      q: "Left colic flexure ",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["7", "5", "6", "11", "9"],
      correct: 0,
    },
    {
      q: "Descending colon",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["8", "4", "6", "10", "9"],
      correct: 0,
    },
    {
      q: "Sigmoid colon",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["9", "8", "3", "10", "11"],
      correct: 0,
    },
    {
      q: "Rectum",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["10", "11", "2", "1", "9"],
      correct: 0,
    },
    {
      q: "Anal canal",
      photo: "../../anatomy/assets/img/image4.png",
      a: ["11", "10", "2", "1", "6"],
      correct: 0,
    },
    {
      q: "Quadrate lobe",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["1", "6", "4", "3", "10"],
      correct: 0,
    },
    {
      q: "Ductus hepaticus",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["2", "7", "3", "11", "6"],
      correct: 0,
    },
    {
      q: "Fissura ligamenti teretis",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["3", "5", "7", "1", "9"],
      correct: 0,
    },
    {
      q: "Lobus hepatis sinister",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["4", "8", "6", "1", "2"],
      correct: 0,
    },
    {
      q: "Fissura ligamenti venosi",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["5", "2", "4", "3", "10"],
      correct: 0,
    },
    {
      q: "Lobus caudatus",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["6", "1", "8", "11", "4"],
      correct: 0,
    },
    {
      q: "Porta hepatis",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["7", "2", "9", "3", "5"],
      correct: 0,
    },
    {
      q: "Lobus hepatis dexter",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["8", "6", "4", "3", "10"],
      correct: 0,
    },
    {
      q: "Collum vesicae biliaris",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["9", "10", "11", "7", "2"],
      correct: 0,
    },
    {
      q: "Corpus vesicae biliaris",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["10", "11", "9", "8", "6"],
      correct: 0,
    },
    {
      q: "Fundus vesicae biliaris",
      photo: "../../anatomy/assets/img/image5.png",
      a: ["11", "9", "6", "2", "3"],
      correct: 0,
    },
  ],
  mock2: [
    {
      q: "Cauda pancreatis(dumi)?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["1", "7", "2", "6", "4"],
      correct: 0,
    },
    {
      q: "Ren sinister?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["2", "7", "8", "6", "1"],
      correct: 0,
    },
    {
      q: "Jejunum?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["3", "7", "9", "6", "1"],
      correct: 0,
    },
    {
      q: "Arteria mesenterica superior?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["4", "10", "9", "6", "7"],
      correct: 0,
    },
    {
      q: "Processus uncinatus (pancreatis)?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["5", "10", "9", "6", "7"],
      correct: 0,
    },
    {
      q: "Duodenum?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["6", "10", "9", "3", "7"],
      correct: 0,
    },
    {
      q: "Caput pancreatis?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["7", "10", "9", "6", "5"],
      correct: 0,
    },
    {
      q: "8?",
      photo: "../../anatomy/assets/img/image6.png",
      a: [
        "Ren dexter",
        "Ren sinister",
        "Duodenum",
        "Cauda pancreatis",
        "Arteria mesenterica superior",
      ],
      correct: 0,
    },
    {
      q: "Collum pancreatis?",
      photo: "../../anatomy/assets/img/image6.png",
      a: ["9", "10", "2", "1", "5"],
      correct: 0,
    },
    {
      q: "10?",
      photo: "../../anatomy/assets/img/image6.png",
      a: [
        "Corpus pancreatis",
        "Collum pancreatis",
        "Caput pancreatis",
        "Processus uncinatus (pancreatis)",
        "Cauda pancreatis",
      ],
      correct: 0,
    },
    {
      q: "Vesica biliaris (O‘t qopi)?",
      photo: "../../anatomy/assets/img/image7.png",
      a: ["1", "3", "2", "6", "5"],
      correct: 0,
    },
    {
      q: "Ductus cysticus?",
      photo: "../../anatomy/assets/img/image7.png",
      a: ["2", "3", "1", "6", "5"],
      correct: 0,
    },
    {
      q: "Ductus hepaticus dexter?",
      photo: "../../anatomy/assets/img/image7.png",
      a: ["3", "2", "1", "6", "5"],
      correct: 0,
    },
    {
      q: "Ductus hepaticus sinister?",
      photo: "../../anatomy/assets/img/image7.png",
      a: ["4", "2", "1", "6", "5"],
      correct: 0,
    },
    {
      q: "5?",
      photo: "../../anatomy/assets/img/image7.png",
      a: [
        "Common hepatic duct",
        "Vesica biliaris",
        "Ductus choledochus",
        "Ductus pancreaticus major",
        "Ductus hepaticus dexter",
      ],
      correct: 0,
    },
    {
      q: "Bile duct(Ductus choledochus)?",
      photo: "../../anatomy/assets/img/image7.png",
      a: ["6", "2", "1", "5", "4"],
      correct: 0,
    },
    {
      q: "Ductus pancreaticus major ( Asosiy pankreatik yo’l)?",
      photo: "../../anatomy/assets/img/image7.png",
      a: ["7", "2", "1", "5", "4"],
      correct: 0,
    },
    {
      q: "Common hepatic artery?",
      photo: "../../anatomy/assets/img/image8.png",
      a: ["1", "13", "11", "8", "2"],
      correct: 0,
    },
    {
      q: "Esophageal branch(tarmoq)?",
      photo: "../../anatomy/assets/img/image8.png",
      a: ["2", "13", "11", "8", "1"],
      correct: 0,
    },
    {
      q: "Sinister gastric artery?",
      photo: "../../anatomy/assets/img/image8.png",
      a: ["3", "2", "11", "8", "10"],
      correct: 0,
    },
    {
      q: "Short gastric artery (qisqa oshqozon arteriyasi)?",
      photo: "../../anatomy/assets/img/image8.png",
      a: ["4", "5", "9", "14", "10"],
      correct: 0,
    },
    {
      q: "Lien (taloq)?",
      photo: "../../anatomy/assets/img/image8.png",
      a: ["5", "4", "9", "14", "10"],
      correct: 0,
    },
    {
      q: "6?",
      photo: "../../anatomy/assets/img/image8.png",
      a: [
        "sinister gastro-omental artery",
        "Dexter  gastro-omental artery ",
        "Superior pancreaticoduodenal arteries ",
        "Sinister gastric artery",
        "dexter hepatic artery",
      ],
      correct: 0,
    },
    {
      q: "Splenic artery?",
      photo: "../../anatomy/assets/img/image8.png",
      a: ["7", "8", "6", "9", "10"],
      correct: 0,
    },
    {
      q: "Dexter  gastro-omental artery?",
      photo: "../anatomy/assets/img/image8.png",
      a: ["8", "7", "6", "9", "10"],
      correct: 0,
    },
    {
      q: "Superior pancreaticoduodenal arteries?",
      photo: "../anatomy/assets/img/image8.png",
      a: ["9", "7", "6", "8", "10"],
      correct: 0,
    },
    {
      q: "Dexter gastric artery?",
      photo: "../anatomy/assets/img/image8.png",
      a: ["10", "3", "6", "8", "1"],
      correct: 0,
    },
    {
      q: "11?",
      photo: "../anatomy/assets/img/image8.png",
      a: [
        "Gastroduodenal artery",
        "Superior pancreaticoduodenal arteries",
        "sinister gastro-omental artery",
        "Dexter  gastro-omental artery ",
        "Hepatic artery proper ",
      ],
      correct: 0,
    },
    {
      q: "dexter hepatic artery?",
      photo: "../anatomy/assets/img/image8.png",
      a: ["12", "13", "3", "2", "9"],
      correct: 0,
    },
    {
      q: "sinister  hepatic artery?",
      photo: "../anatomy/assets/img/image8.png",
      a: ["13", "12", "3", "2", "9"],
      correct: 0,
    },
    {
      q: "Hepatic artery proper?",
      photo: "../anatomy/assets/img/image8.png",
      a: ["14", "12", "3", "13", "9"],
      correct: 0,
    },
    {
      q: "Hepatic artery proper?",
      photo: "../anatomy/assets/img/image8.png",
      a: ["14", "12", "3", "13", "9"],
      correct: 0,
    },
    {
      q: "Transverse colon?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["1", "14", "3", "13", "9"],
      correct: 0,
    },
    {
      q: "Inferior pancreaticoduodenal artery?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["2", "15", "3", "13", "9"],
      correct: 0,
    },
    {
      q: "Superior mesenteric artery?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["3", "15", "2", "13", "8"],
      correct: 0,
    },
    {
      q: "Jejunum?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["4", "6", "7", "13", "8"],
      correct: 0,
    },
    {
      q: "5?",
      photo: "../anatomy/assets/img/image9.png",
      a: [
        "Jejunal arteries",
        " Vasa recta",
        "Ileum",
        "Dexter  colic artery",
        "Middle colic artery",
      ],
      correct: 0,
    },
    {
      q: " Vasa recta?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["6", "5", "7", "15", "16"],
      correct: 0,
    },
    {
      q: "Ileum?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["7", "5", "6", "15", "16"],
      correct: 0,
    },
    {
      q: "Ileal arteries?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["8", "5", "6", "11", "16"],
      correct: 0,
    },
    {
      q: "Appendix?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["9", "10", "1", "11", "16"],
      correct: 0,
    },
    {
      q: "Appendicular artery?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["10", "9", "1", "11", "16"],
      correct: 0,
    },
    {
      q: "Posterior cecal artery?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["11", "9", "1", "10", "12"],
      correct: 0,
    },
    {
      q: "12?",
      photo: "../anatomy/assets/img/image9.png",
      a: [
        "Anterior cecal artery",
        "Appendix",
        "Posterior cecal artery ",
        "Appendicular artery",
        "Middle colic artery",
      ],
      correct: 0,
    },
    {
      q: "Iliocolic artery?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["13", "9", "15", "10", "6"],
      correct: 0,
    },
    {
      q: "Ascending colon?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["14", "4", "7", "8", "12"],
      correct: 0,
    },
    {
      q: "Dexter  colic artery?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["15", "16", "5", "8", "12"],
      correct: 0,
    },
    {
      q: "Middle colic artery?",
      photo: "../anatomy/assets/img/image9.png",
      a: ["16", "15", "5", "8", "12"],
      correct: 0,
    },
    {
      q: "1?",
      photo: "../anatomy/assets/img/image10.png",
      a: [
        "Sinister  gastric vein",
        "Short  gastric vein",
        "Superior mesenteric vein ",
        "Portal vein",
        "Splenic vein",
      ],
      correct: 0,
    },
    {
      q: "Splenic vein?",
      photo: "../anatomy/assets/img/image10.png",
      a: ["2", "1", "3", "4", "5"],
      correct: 0,
    },
    {
      q: "3?",
      photo: "../anatomy/assets/img/image10.png",
      a: [
        "Inferior mesenteric vein",
        "Superior mesenteric vein ",
        "Sinister  gastric vein",
        "Portal vein",
        "Splenic vein",
      ],
      correct: 0,
    },
    {
      q: "Superior mesenteric vein?",
      photo: "../anatomy/assets/img/image10.png",
      a: ["4", "1", "2", "3", "5"],
      correct: 0,
    },
    {
      q: "Portal vein?",
      photo: "../anatomy/assets/img/image10.png",
      a: ["5", "1", "2", "3", "4"],
      correct: 0,
    },
  ],
};
