// Gray's Anatomy for Students Flash Cards (3E, 2014) - Upper Limb Muscles
// Source: Section 7 (Upper Limb) flashcard diagrams, cropped to remove answer text.
// 58 questions covering all muscles in Tables 7.1, 7.3-7.6 plus key clinical structures.
window.TEST_QUESTIONS = {
  mock1: [
    {
      q: "Pectoralis major?",
      photo: "./img/image1.png",
      a: ["1", "2", "3", "4"],
      correct: 2,
    },
    {
      q: "Pectoralis minor?",
      photo: "./img/image2.png",
      a: ["1", "2", "7", "8", "10"],
      correct: 2,
    },
    {
      q: "Subclavius?",
      photo: "./img/image2.png",
      a: ["1", "6", "7", "9", "10"],
      correct: 0,
    },
    {
      q: "Deltoid (cut edge)?",
      photo: "./img/image3.png",
      a: ["1", "3", "8", "13"],
      correct: 0,
    },
    {
      q: "Teres minor?",
      photo: "./img/image3.png",
      a: ["2", "4", "10", "12"],
      correct: 0,
    },
    {
      q: "Teres major?",
      photo: "./img/image3.png",
      a: ["2", "9", "10", "12"],
      correct: 2,
    },
    {
      q: "Infraspinatus?",
      photo: "./img/image3.png",
      a: ["2", "10", "12", "14"],
      correct: 2,
    },
    {
      q: "Supraspinatus?",
      photo: "./img/image3.png",
      a: ["10", "12", "13", "14"],
      correct: 3,
    },
    {
      q: "Serratus anterior?",
      photo: "./img/image19.png",
      a: ["47", "48", "51", "53"],
      correct: 2,
    },
    {
      q: "Biceps brachii (muscle belly, anterior view)?",
      photo: "./img/image19.png",
      a: ["44", "45", "50", "52"],
      correct: 2,
    },
    {
      q: "Supinator (superficial head, anterior view)?",
      photo: "./img/image19.png",
      a: ["12", "14", "18", "20"],
      correct: 1,
    },
    {
      q: "Latissimus dorsi?",
      photo: "./img/image20.png",
      a: ["12", "54", "55", "56"],
      correct: 2,
    },
    {
      q: "Which numbered structure marks the aperture for the subtendinous bursa of subscapularis?",
      photo: "./img/image21.png",
      a: ["1", "2", "3", "4"],
      correct: 2,
    },
    {
      q: "Coracobrachialis?",
      photo: "./img/image4.png",
      a: ["1", "2", "3", "4"],
      correct: 0,
    },
    {
      q: "Brachialis?",
      photo: "./img/image4.png",
      a: ["1", "2", "3", "4"],
      correct: 1,
    },
    {
      q: "Biceps brachii (tendon, cubital fossa)?",
      photo: "./img/image17.png",
      a: ["3", "4", "5", "8"],
      correct: 3,
    },
    {
      q: "Triceps brachii (long head)?",
      photo: "./img/image6.png",
      a: ["1", "2", "4", "5"],
      correct: 3,
    },
    {
      q: "Triceps brachii (lateral head)?",
      photo: "./img/image6.png",
      a: ["1", "2", "4", "5"],
      correct: 1,
    },
    {
      q: "Triceps brachii (medial head)?",
      photo: "./img/image6.png",
      a: ["1", "2", "4", "5"],
      correct: 2,
    },
    {
      q: "Anconeus?",
      photo: "./img/image10.png",
      a: ["1", "4", "6", "7"],
      correct: 3,
    },
    {
      q: "Pronator teres?",
      photo: "./img/image7.png",
      a: ["1", "2", "3", "4"],
      correct: 3,
    },
    {
      q: "Flexor carpi radialis?",
      photo: "./img/image7.png",
      a: ["1", "2", "3", "4"],
      correct: 2,
    },
    {
      q: "Palmaris longus?",
      photo: "./img/image7.png",
      a: ["1", "2", "3", "4"],
      correct: 0,
    },
    {
      q: "Flexor carpi ulnaris?",
      photo: "./img/image7.png",
      a: ["1", "2", "3", "4"],
      correct: 1,
    },
    {
      q: "Flexor digitorum superficialis?",
      photo: "./img/image8.png",
      a: ["1"],
      correct: 0,
    },
    {
      q: "Flexor digitorum profundus?",
      photo: "./img/image9.png",
      a: ["1", "2", "3"],
      correct: 0,
    },
    {
      q: "Pronator quadratus?",
      photo: "./img/image9.png",
      a: ["1", "2", "3"],
      correct: 1,
    },
    {
      q: "Flexor pollicis longus?",
      photo: "./img/image9.png",
      a: ["1", "2", "3"],
      correct: 2,
    },
    {
      q: "Brachioradialis?",
      photo: "./img/image10.png",
      a: ["1", "2", "3", "7"],
      correct: 0,
    },
    {
      q: "Extensor carpi radialis longus?",
      photo: "./img/image10.png",
      a: ["1", "2", "3", "6"],
      correct: 1,
    },
    {
      q: "Extensor carpi radialis brevis?",
      photo: "./img/image10.png",
      a: ["2", "3", "4", "6"],
      correct: 1,
    },
    {
      q: "Extensor digitorum?",
      photo: "./img/image10.png",
      a: ["3", "4", "5", "6"],
      correct: 1,
    },
    {
      q: "Extensor digiti minimi?",
      photo: "./img/image10.png",
      a: ["3", "4", "5", "6"],
      correct: 2,
    },
    {
      q: "Extensor carpi ulnaris?",
      photo: "./img/image10.png",
      a: ["4", "5", "6", "7"],
      correct: 2,
    },
    {
      q: "Supinator?",
      photo: "./img/image11.png",
      a: ["1", "2", "3", "4"],
      correct: 0,
    },
    {
      q: "Abductor pollicis longus?",
      photo: "./img/image11.png",
      a: ["1", "2", "3", "4"],
      correct: 1,
    },
    {
      q: "Extensor pollicis longus?",
      photo: "./img/image11.png",
      a: ["2", "3", "4", "5"],
      correct: 1,
    },
    {
      q: "Extensor pollicis brevis?",
      photo: "./img/image11.png",
      a: ["2", "3", "4", "5"],
      correct: 2,
    },
    {
      q: "Extensor indicis?",
      photo: "./img/image11.png",
      a: ["2", "3", "4", "5"],
      correct: 3,
    },
    {
      q: "Flexor pollicis brevis?",
      photo: "./img/image13.png",
      a: ["1", "6", "8", "16"],
      correct: 0,
    },
    {
      q: "Abductor pollicis brevis?",
      photo: "./img/image13.png",
      a: ["1", "6", "8", "16"],
      correct: 2,
    },
    {
      q: "Opponens pollicis?",
      photo: "./img/image13.png",
      a: ["1", "6", "8", "14"],
      correct: 1,
    },
    {
      q: "Abductor digiti minimi?",
      photo: "./img/image13.png",
      a: ["8", "13", "14", "16"],
      correct: 1,
    },
    {
      q: "Opponens digiti minimi?",
      photo: "./img/image13.png",
      a: ["8", "13", "14", "16"],
      correct: 2,
    },
    {
      q: "Flexor digiti minimi brevis?",
      photo: "./img/image13.png",
      a: ["8", "13", "14", "16"],
      correct: 3,
    },
    {
      q: "Adductor pollicis?",
      photo: "./img/image15.png",
      a: ["1", "2", "3"],
      correct: 0,
    },
    {
      q: "Palmaris brevis?",
      photo: "./img/image12.png",
      a: ["1", "2", "3"],
      correct: 2,
    },
    {
      q: "Lumbricals?",
      photo: "./img/image14.png",
      a: ["1", "2"],
      correct: 1,
    },
    {
      q: "Dorsal interossei?",
      photo: "./img/image16.png",
      a: ["1", "2"],
      correct: 0,
    },
    {
      q: "Palmar interossei?",
      photo: "./img/image16.png",
      a: ["1", "2"],
      correct: 1,
    },
    {
      q: "Quadrangular space (transmits axillary nerve and posterior humeral circumflex vessels)?",
      photo: "./img/image3.png",
      a: ["5", "6", "9", "11"],
      correct: 0,
    },
    {
      q: "Triangular space (upper) \u2014 bounded by teres minor, teres major, and long head of triceps?",
      photo: "./img/image3.png",
      a: ["5", "6", "9", "11"],
      correct: 3,
    },
    {
      q: "Triangular interval (lower triangular space) \u2014 transmits the radial nerve and profunda brachii artery?",
      photo: "./img/image3.png",
      a: ["5", "6", "9", "11"],
      correct: 1,
    },
    {
      q: "Bicipital aponeurosis?",
      photo: "./img/image5.png",
      a: ["3", "4", "6", "7"],
      correct: 3,
    },
    {
      q: "Interosseous membrane of the forearm?",
      photo: "./img/image18.png",
      a: ["4", "6", "9", "10"],
      correct: 2,
    },
    {
      q: "Flexor retinaculum?",
      photo: "./img/image13.png",
      a: ["3", "9", "10", "12"],
      correct: 2,
    },
    {
      q: "Extensor expansion (extensor hood)?",
      photo: "./img/image13.png",
      a: ["3", "4", "5", "6"],
      correct: 1,
    },
    {
      q: "Palmar aponeurosis?",
      photo: "./img/image12.png",
      a: ["1", "2", "3"],
      correct: 0,
    },
  ],
};
