window.TEST_QUESTIONS = {
  mock1: [
    {
      q: "Qorin pardasi qanday hujayralardan tashkil topgan?",
      a: ["Epitelial", "Mezotelial", "Muskular", "Nerv", "Suyak"],
      correct: 1,
    },
    {
      q: "Qorin pardaning nechta asosiy qavati mavjud?",
      a: ["1", "2", "3", "4", "5"],
      correct: 1,
    },
    {
      q: "Parietal peritoneum qaysi nervlar orqali innervatsiya qilinadi?",
      a: [
        "Vegetativ nervlar",
        "Somatik nervlar",
        "Simpatik nervlar",
        "Parasimpatiк nervlar",
        "Kraniyal nervlar",
      ],
      correct: 1,
    },
    {
      q: "Visceral peritoneum qaysi tuzilmani qoplaydi?",
      a: [
        "Qorin devorini",
        "Diafragmani",
        "Viseral organlarni",
        "Qovurg‘alarni",
        "Orqa miya kanalini",
      ],
      correct: 2,
    },
    {
      q: "Visceral peritoneum og‘riqni qanday sezadi?",
      a: [
        "Juda aniq sezadi",
        "Somatik og‘riq sezadi",
        "Og‘riq sezmaydi",
        "Sovuqni sezadi",
        "Issiqni sezadi",
      ],
      correct: 2,
    },
    {
      q: "Omentum nima?",
      a: [
        "Muskul qavati",
        "Qon tomiri",
        "Qorin parda burmasi",
        "Nerv tolasi",
        "Limfa tuguni",
      ],
      correct: 2,
    },
    {
      q: "Kichik charvi necha qavatli tuzilma?",
      a: ["1", "2", "3", "4", "5"],
      correct: 1,
    },
    {
      q: "Kichik charvi qaysi boylamlarni o‘z ichiga oladi?",
      a: [
        "Gastrokolik va gastrolienal",
        "Gepatogastrik va gepatoduodenal",
        "Lienorenal va gastrofrenik",
        "Frenikokolik va gepatojejunal",
        "Sigmoid va mesoappendix",
      ],
      correct: 1,
    },
    {
      q: "Katta charvi embrion davrida qaysi tuzilmadan rivojlanadi?",
      a: [
        "Ventral mezenteriya",
        "Dorsal mezenteriya",
        "Allantois",
        "Amnion",
        "Yolk sac",
      ],
      correct: 1,
    },
    {
      q: "Katta charvi yallig‘lanishda qanday vazifa bajaradi?",
      a: [
        "Infeksiyani yoyadi",
        "Yallig‘lanishni chegaralaydi",
        "Qon aylanishni to‘xtatadi",
        "Organlarni parchalaydi",
        "Nervlarni bloklaydi",
      ],
      correct: 1,
    },
    {
      q: "Gastrolienal boylam qaysi organlar orasida joylashgan?",
      a: [
        "Oshqozon va taloq",
        "Jigar va taloq",
        "Ichak va buyrak",
        "Jigar va oshqozon",
        "Duodenum va jejunum",
      ],
      correct: 0,
    },
    {
      q: "Lienorenal boylam qaysi organlarni bog‘laydi?",
      a: [
        "Oshqozon va taloq",
        "Taloq va chap buyrak",
        "Jigar va oshqozon",
        "Duodenum va jejunum",
        "Sigmoid va rektum",
      ],
      correct: 1,
    },
    {
      q: "Gastrofrenik boylam qayerga tortilgan?",
      a: [
        "Oshqozondan diafragmaga",
        "Jigardan taloqqa",
        "Ichakdan buyrakka",
        "Duodenumdan jejunumga",
        "Sigmoiddan rektumga",
      ],
      correct: 0,
    },
    {
      q: "Mesentery proper qaysi ichaklarni bog‘laydi?",
      a: [
        "Duodenum va jejunum",
        "Jejunum va ileum",
        "Sigmoid ichak",
        "Appendix",
        "Oshqozon",
      ],
      correct: 1,
    },
    {
      q: "Mesentery proper taxminan qancha uzunlikka ega?",
      a: ["5 sm", "10 sm", "15 sm", "25 sm", "30 sm"],
      correct: 2,
    },
    {
      q: "Mesentary Proper qorin pardaning necha qavatli burmasi?",
      a: ["1", "2", "3", "4", "5"],
      correct: 1,
    },
    {
      q: "Transverse Mesocolon katta charvi bilan birlashib, qaysi boylamni hosil qiladi?",
      a: [
        "gastrokolik",
        "gastrofrenik",
        "lieonrenal",
        "gastroduodenal",
        "gastrojejunal",
      ],
      correct: 0,
    },
    {
      q: "Sigmoid mesocolon qaysi ichakni bog‘laydi?",
      a: [
        "Sigmasimon ichakni",
        "Ko‘ndalang ichakni",
        "Ko‘r ichakni",
        "Duodenumni",
        "Jejunumni",
      ],
      correct: 0,
    },
    {
      q: "Phrenicocolic boylam chap chambar ichak egriligidan qayerga tortilgan?",
      a: ["diafragmaga", "oshqozonga", "buyrakka", "ichakka", "jejunumga"],
      correct: 0,
    },
    {
      q: "Qaysi boylam jigarni diafragma va qorinni yuqori devori bilan bog’laydi?",
      a: [
        "lig. falciformis",
        "Ligamentum Teres Hepatis",
        "Coronary Ligament",
        "Ligamentum Venosum",
        "Tojsimon Boylam",
      ],
      correct: 0,
    },
    {
      q: "Ligamentum teres hepatis nimaning qoldig‘i hisoblanadi?",
      a: [
        "Chap kindik venasi",
        "O‘ng kindik venasi",
        "Portal vena",
        "Pastki kovak vena",
        "Jigar arteriyasi",
      ],
      correct: 0,
    },
    {
      q: "Ligamentum venosum nimaning qoldig‘i hisoblanadi?",
      a: [
        "Ductus venosus",
        "Umbilikal arteriya",
        "Portal vena",
        "Aorta",
        "Hepatik vena",
      ],
      correct: 0,
    },
    {
      q: "Peritoneal bo‘shliq erkaklarda qanday bo‘ladi?",
      a: [
        "Ochiq",
        "Yarim ochiq",
        "To‘liq yopiq",
        "Tashqariga ochiq",
        "Faqat qisman yopiq",
      ],
      correct: 2,
    },
    {
      q: "Peritoneal bo‘shliq ayollarda qaysi yo‘l orqali tashqariga ochiladi?",
      a: [
        "Bachadon naylari orqali",
        "Qizilo‘ngach orqali",
        "Traxeya shoxlari orqali",
        "Qovuq orqali",
        "Buyrak arteriyasi orqali",
      ],
      correct: 0,
    },
    {
      q: "Kichik qopcha yana qanday nom bilan ataladi?",
      a: [
        "Bursa omentalis",
        "Morrison haltachasi",
        "Parakolik chuqurcha",
        "Subfrenik chuqurcha",
        "Ileocecal chuqurcha",
      ],
      correct: 0,
    },
    {
      q: "Kichik va katta qopchalar orasidagi tabiiy ochiq qism?",
      a: [
        "Epiploik foramen",
        "Douglas pouch",
        "lig anterior posterioralis omentum",
        "Esophagus",
        "Bilmayman 😁",
      ],
      correct: 0,
    },
    {
      q: "Epiploik foramen yuqoridan qaysi tuzilmaga bog'langan?",
      a: [
        "jigarning dumsimon qismiga",
        "duodenumning 1-qismiga",
        "kichik charvining erkin burchagiga",
        "pastki kovak venaga",
        "Bilmaymanda 😁",
      ],
      correct: 0,
    },
    {
      q: "Epiploik foramen pastki tomondan qaysi tuzilmaga bog'langan?",
      a: [
        "jigarning dumsimon qismiga",
        "duodenumning 1-qismiga",
        "kichik charvining erkin burchagiga",
        "pastki kovak venaga",
        "Bilmaymanda 😁",
      ],
      correct: 1,
    },
    {
      q: "Epiploik foramen oldingi tomondan qaysi tuzilmaga bog'langan?",
      a: [
        "jigarning dumsimon qismiga",
        "duodenumning 1-qismiga",
        "kichik charvining erkin burchagiga",
        "pastki kovak venaga",
        "Bilmaymanda 😁",
      ],
      correct: 2,
    },
    {
      q: "Epiploik foramen orqa tomondan qaysi tuzilmaga bog'langan?",
      a: [
        "jigarning dumsimon qismiga",
        "duodenumning 1-qismiga",
        "kichik charvining erkin burchagiga",
        "pastki kovak venaga",
        "Bilmaymanda 😁",
      ],
      correct: 3,
    },
    {
      q: "Parasentez qaysi tomirlarni jarohatlashdan saqlash uchun Mak-Burney nuqtasidan lateral tomonda yoki kindikdan 2 sm pastroq qismda amalga oshiriladi?",
      a: [
        "pastki epigastral qon tomirlarni",
        "yuqori epigastral qon tomirlarni",
        "phrenic qon tomirlarni",
        "pastki kovak venani",
        "yurak arteriyalarini",
      ],
      correct: 0,
    },
  ],
  mock2: [
    {
      q: "Qizilo‘ngachning umumiy uzunligi taxminan qancha?",
      a: ["15 sm", "20 sm", "25 sm", "30 sm", "35 sm"],
      correct: 2,
    },
    {
      q: "Qizilo‘ngachning qorin bo‘shlig‘idagi qismi taxminan qancha?",
      a: ["2 sm", "3 sm", "5 sm", "7 sm", "10 sm"],
      correct: 2,
    },
    {
      q: "Qizilo‘ngach qorin bo‘shlig‘iga qaysi tuzilma orqali kiradi?",
      a: [
        "Diafragmaning chap oyoqchasi",
        "Diafragmaning o‘ng oyoqchasi",
        "Aorta teshigi",
        "Pastki kovak vena teshigi",
        "Ko‘ndalang ichak orqali",
      ],
      correct: 1,
    },
    {
      q: "Qizilo‘ngachning terminal qismida qanday sfinkter mavjud?",
      a: [
        "Pilorik sfinkter",
        "Anal sfinkter",
        "Fiziologik sfinkter",
        "Duodenal sfinkter",
        "Anatomik sfinkter",
      ],
      correct: 2,
    },
    {
      q: "Oshqozon qaysi sohalarda joylashgan?",
      a: [
        "Epigastral va umbilikal",
        "Chap gipoxondrik va epigastral",
        "O‘ng gipoxondrik va epigastral",
        "Umnilikal va lumbar",
        "Yonbosh sohasida",
      ],
      correct: 1,
    },
    {
      q: "Oshqozon nechta asosiy qismga bo‘linadi?",
      a: ["2", "3", "4", "5", "6"],
      correct: 2,
    },
    {
      q: "Quyidagilardan qaysi biri oshqozon qismi hisoblanadi?",
      a: [
        "Kardial qism",
        "Sigmoid qism",
        "Jejunal qism",
        "Ileal qism",
        "Rektal qism",
      ],
      correct: 0,
    },
    {
      q: "Oshqozon fundusi qaysi qovurg‘a sathida joylashadi?",
      a: ["3-qovurg‘a", "4-qovurg‘a", "5-qovurg‘a", "6-qovurg‘a", "7-qovurg‘a"],
      correct: 2,
    },
    {
      q: "Pilorik qism qanday bo‘limlarga bo‘linadi?",
      a: [
        "Fundus va tana",
        "Atrium va kanal",
        "Jejunum va ileum",
        "Sigmoid va rektum",
        "Ko‘ndalang va tushuvchi",
      ],
      correct: 1,
    },
    {
      q: "Pilorik sfinkter qaysi tizim orqali bo’shashadi?",
      a: [
        "parasimpatik tizim",
        "simpatik tizim",
        "lumbosacral tizim",
        "arterial tizim",
        "venoz tizim",
      ],
      correct: 0,
    },
    {
      q: "Oshqozon shilliq qavatidagi burmalar qanday ataladi?",
      a: ["Haustra", "Rugae", "Teniae coli", "Plicae circulares", "Villi"],
      correct: 1,
    },
    {
      q: "Oshqozon qaysi modda orqali o‘zini o‘zi zararlanishdan himoya qiladi?",
      a: ["Pepsin", "Gastrin", "Shilliq modda", "Xlorid kislota", "Safro"],
      correct: 2,
    },
    {
      q: "Pepsinning asosiy vazifasi nima?",
      a: [
        "Kislotalarni polipeptidlarga aylantiradi",
        "Oqsillarni polipeptidlarga aylantiradi",
        "Uglevodlarni parchalaydi",
        "Suvni so‘radi",
        "Minerallarni so‘radi",
      ],
      correct: 1,
    },
    {
      q: "Ingichka ichak Pilorik sfinkterdan qayergacha davom etadi?",
      a: [
        "Duodenojejunal kesishmagacha",
        "Ileocecal kesishmagacha",
        "Jejunorektal kesishmagacha",
        "Oshqozonning fundusigacha",
        "Anusgacha",
      ],
      correct: 1,
    },
    {
      q: "Ingichka ichakning asosiy vazifasi nima?",
      a: [
        "Qonni filtrlash",
        "Suv va minerallarni so‘rish",
        "Ovqatni saqlash",
        "Ferment ishlab chiqarish",
        "Nerv impulslarini uzatish",
      ],
      correct: 1,
    },
    {
      q: "Ingichka ichak qaysi qismlardan tashkil topgan?",
      a: [
        "Cecum, colon, rectum",
        "Duodenum, jejunum, ileum",
        "Colon, rectum, anus",
        "Appendix, colon, rectum",
        "Fundus, tana, pilorus",
      ],
      correct: 1,
    },
    {
      q: "Duodenumning taxminiy uzunligi qancha?",
      a: ["15 sm", "20 sm", "25 sm", "30 sm", "40 sm"],
      correct: 2,
    },
    {
      q: "Duodenum nechta qismga bo‘linadi?",
      a: ["2", "3", "4", "5", "6"],
      correct: 2,
    },
    {
      q: "Duodenumning birinchi qismi qanday ataladi?",
      a: [
        "Duodenal qopqoq",
        "Duodenal kapsula",
        "Duodenal kanal",
        "Duodenal bo‘g‘im",
        "Duodenal halqa",
      ],
      correct: 0,
    },
    {
      q: "Jejunum ingichka ichakning taxminan nechanchi qismini tashkil qiladi?",
      a: ["1/5", "2/5", "3/5", "4/5", "5/5"],
      correct: 1,
    },
    {
      q: "Jejunumda qaysi tuzilma mavjud emas?",
      a: [
        "Peyer pilakchalari",
        "Plicae circulares",
        "Vasa recta",
        "Arterial arcades",
        "Tutqich",
      ],
      correct: 0,
    },
    {
      q: "Ileum qorin bo‘shlig‘ining qaysi qismida joylashadi?",
      a: [
        "Chap yuqori kvadrant",
        "O‘ng pastki kvadrant",
        "Epigastral soha",
        "Chap pastki kvadrant",
        "Umbilikal soha",
      ],
      correct: 1,
    },
    {
      q: "Mekkel divertikulasi qayerdan hosil bo‘ladi?",
      a: [
        "Umbilikal arteriya",
        "Vitellin kanal",
        "Portal vena",
        "Aorta",
        "Safro yo‘li",
      ],
      correct: 1,
    },
    {
      q: "Mekkel divertikulasining uzunligi taxminan qancha?",
      a: ["2 sm", "3 sm", "5 sm", "7 sm", "10 sm"],
      correct: 2,
    },
    {
      q: "Yo‘g‘on ichakning umumiy uzunligi taxminan qancha?",
      a: ["1 m", "1.5 m", "2 m", "2.5 m", "3 m"],
      correct: 1,
    },
    {
      q: "Qorin bo’shlig’ida hosil qilingan suniy teshik?",
      a: [
        "Haustra",
        "Vasa recta",
        "Kolostoma",
        "Peyer pilakchalari",
        "Plicae circulares",
      ],
      correct: 2,
    },
    {
      q: "anterior superior iliac spine bilan kindik o’rtasidan tortilgan chiziqning lateral 1/3 qismida joylashgan nuqta?",
      a: [
        "Mak-Burney nuqtasi",
        "Douglas nuqtasi",
        "Xolesistektomiya nuqtasi",
        "Kardial aritmiya nuqtasi",
        "Plicae circulares nuqtasi",
      ],
      correct: 0,
    },
    {
      q: "Yog’on ichakning ko’r cho’ntagi?",
      a: ["Cecum", "Duodenum", "Ileum", "Appendix", "Sigmoid ichak"],
      correct: 0,
    },
    {
      q: "Duodenum jigarga qanday boylam bilan bog'langan?",
      a: [
        "hepatoduodenal",
        "Duodenojejunal",
        "hepatogastrik",
        "falciform",
        "gastrolienal",
      ],
      correct: 0,
    },
  ],
  mock3: [
    {
      q: "Jigar inson tanasida qanday organ hisoblanadi?",
      a: [
        "Eng kichik organ",
        "Eng katta bez",
        "Eng kichik bez",
        "Respirator organ",
        "Suyak",
      ],
      correct: 1,
    },
    {
      q: "Jigarning asosiy funksiyalaridan biri nima?",
      a: [
        "Insulin ishlab chiqarish",
        "Safro ishlab chiqarish",
        "Adrenalin ishlab chiqarish",
        "Siydik ishlab chiqarish",
        "Limfa ishlab chiqarish",
      ],
      correct: 1,
    },
    {
      q: "Jigar qaysi modda ko‘rinishida uglevodlarni saqlaydi?",
      a: ["Maltoza", "Glikogen", "Fruktoza", "Laktoza", "Kraxmal"],
      correct: 1,
    },
    {
      q: "Jigar qaysi plazma oqsillarini sintez qiladi?",
      a: [
        "Albumin va globulin",
        "Insulin va glukagon",
        "Pepsin va tripsin",
        "Aktin va miozin",
        "Keratin va elastin",
      ],
      correct: 0,
    },
    {
      q: "Jigar venoz qoni qayerga quyiladi?",
      a: [
        "Portal venaga",
        "Pastki kovak venaga",
        "Aortaga",
        "Yuqori kovak venaga",
        "O‘ng bo‘lmachaga",
      ],
      correct: 1,
    },
    {
      q: "Jigar kislorodli qonni qaysi tomirdan oladi?",
      a: [
        "Portal vena",
        "Jigar arteriyasi",
        "Aorta",
        "Pastki kovak vena",
        "Splenik vena",
      ],
      correct: 1,
    },
    {
      q: "Portal triada qaysi tuzilmalarni o‘z ichiga oladi?",
      a: [
        "Jigar arteriyasi, portal vena, o‘t yo‘li",
        "Aorta, vena cava, safro yo‘li",
        "Arteriya, vena, nerv",
        "Limfa tomiri, vena, arteriya",
        "Jigar vena, arteriya, nerv",
      ],
      correct: 0,
    },
    {
      q: "Jigar nechta funksional segmentga bo‘linadi?",
      a: ["4", "6", "8", "10", "12"],
      correct: 2,
    },
    {
      q: "Ligamentum teres hepatis qaysi yoriqda joylashgan?",
      a: [
        "Portal yoriqda",
        "Yumaloq boylam yorig‘ida",
        "O‘t pufagi chuqurchasida",
        "Pastki kovak vena yorig‘ida",
        "Kaudal yoriqda",
      ],
      correct: 1,
    },

    {
      q: "O‘t pufagining sig‘imi taxminan qancha?",
      a: ["10-20 ml", "30-50 ml", "60-80 ml", "80-100 ml", "100-150 ml"],
      correct: 1,
    },
    {
      q: "O‘t pufagi qaysi organ yuzasida joylashadi?",
      a: ["Oshqozon", "Jigar", "Duodenum", "Pankreas", "Taloq"],
      correct: 1,
    },
    {
      q: "O‘t pufagi qanday shaklga ega?",
      a: ["Dumaloq", "Noksimon", "Silindrsimon", "Kub shaklida", "U-simon"],
      correct: 1,
    },
    {
      q: "O‘t pufagi qanday qismlardan iborat?",
      a: [
        "Fundus, tana, bo‘yin",
        "Tana va dum",
        "Bosh va tana",
        "Bo‘yin va dum",
        "Fundus va kanal",
      ],
      correct: 0,
    },
    {
      q: "O‘t pufagi arteriyasi qayerdan keladi?",
      a: [
        "O‘ng jigar arteriyasidan",
        "Chap jigar arteriyasidan",
        "Portal venadan",
        "Aortadan",
        "Splenik arteriyadan",
      ],
      correct: 0,
    },
    {
      q: "Pankreas qorin bo‘shlig‘ida qanday joylashgan?",
      a: [
        "Intrapertioneal",
        "Asosan retroperitoneal",
        "Torakal",
        "Pelvik",
        "Subkutan",
      ],
      correct: 1,
    },
    {
      q: "Pankreas qaysi gormonlarni ishlab chiqaradi?",
      a: [
        "Adrenalin va noradrenalin",
        "Insulin va glukagon",
        "Tiroksin va kalsitonin",
        "Melatonin va serotonin",
        "Aldosteron va kortizol",
      ],
      correct: 1,
    },
    {
      q: "Insulin qanday ta’sir qiladi?",
      a: [
        "Qon shakarini oshiradi",
        "Qon shakarini kamaytiradi",
        "Safro ishlab chiqaradi",
        "Ferment ishlab chiqaradi",
        "Qonni ivitadi",
      ],
      correct: 1,
    },
    {
      q: "Glukagonning vazifasi nima?",
      a: [
        "Qon shakarini kamaytiradi",
        "Qon shakarini oshiradi",
        "Safro chiqaradi",
        "Oqsillarni parchalaydi",
        "Qon ivishini oshiradi",
      ],
      correct: 1,
    },
    {
      q: "Asosiy pankreatik kanal qanday ataladi?",
      a: [
        "Santorini kanali",
        "Wirsung kanali",
        "Oddi kanali",
        "Boyden kanali",
        "Treitz kanali",
      ],
      correct: 1,
    },
    {
      q: "Qo‘shimcha pankreatik kanal qanday ataladi?",
      a: ["Wirsung", "Santorini", "Oddi", "Boyden", "Treitz"],
      correct: 1,
    },
    {
      q: "Vater ampulasi qanday hosil bo‘ladi?",
      a: [
        "O‘t yo‘li va pankreatik kanal qo‘shilishidan",
        "Jigar arteriyasi va vena qo‘shilishidan",
        "O‘t pufagi va duodenum qo‘shilishidan",
        "Pankreas va taloq qo‘shilishidan",
        "Portal vena va arteriya qo‘shilishidan",
      ],
      correct: 0,
    },
    {
      q: "Katta o'n ikki barmoqli ichak papillasi atrofidagi dumaloq mushak qatlami nima deb ataladi?",
      a: [
        "Oddi sfinkteri",
        "Wirsung sfinkteri",
        "Santorini sfinkteri",
        "Boyden sfinkteri",
        "Treitz sfinkteri",
      ],
      correct: 0,
    },
    {
      q: "Taloq qaysi sohada joylashadi?",
      a: [
        "O‘ng gipoxondrik",
        "Chap gipoxondrik",
        "Epigastral",
        "Umbilikal",
        "Chanoq",
      ],
      correct: 1,
    },
    {
      q: "Taloqning asosiy funksiyasi nima?",
      a: [
        "Qonni filtrlash",
        "Safro ishlab chiqarish",
        "Insulin ishlab chiqarish",
        "Siydik ishlab chiqarish",
        "Hazm fermentlari ishlab chiqarish",
      ],
      correct: 0,
    },
    {
      q: "Taloq qaysi arteriya bilan ta’minlanadi?",
      a: [
        "Jigar arteriyasi",
        "Splenik arteriya",
        "Renal arteriya",
        "Mesenterik arteriya",
        "Aorta",
      ],
      correct: 1,
    },
    {
      q: "Taloq yorilganda qanday operatsiya bajariladi?",
      a: [
        "Hepatektomiya",
        "Gastrektomiya",
        "Splenektomiya",
        "Appendektomiya",
        "Cholecystektomiya",
      ],
      correct: 2,
    },
    {
      q: "Taloqda immun va fagotsitar javobning markazi hisoblanadi",
      a: [
        "Oq pulpa",
        "Qizil pulpa",
        "Insulin",
        "Ductus Choledochus)",
        "Cholecystektomiya",
      ],
      correct: 0,
    },
    {
      q: "kaudal bo’lak",
      a: [
        "Medial superior",
        "medial inferior",
        "lateral superior",
        "lateral posterior",
        "lateral inferior",
      ],
      correct: 0,
    },
    {
      q: "kvadrat bo’lak",
      a: [
        "Medial superior",
        "medial inferior",
        "lateral superior",
        "lateral posterior",
        "lateral inferior",
      ],
      correct: 1,
    },
    {
      q: "Kvadrat bo'lak qonni qayerdan oladi",
      a: [
        "chap jigar arteriyasidan",
        "o'ng jigar arteriyasidan",
        "chap va o'ng jigar arteriyasidan",
        "lateral posterior arteriyasidan",
        "lateral inferior arteriyasidan",
      ],
      correct: 0,
    },
    {
      q: "Kaudal bo'lak qonni qayerdan oladi",
      a: [
        "chap jigar arteriyasidan",
        "o'ng jigar arteriyasidan",
        "chap va o'ng jigar arteriyasidan",
        "lateral posterior arteriyasidan",
        "lateral inferior arteriyasidan",
      ],
      correct: 2,
    },
  ],
  mock4: [
    {
      q: "Seliak trunk qaysi arteriyalarga bo‘linadi?",
      a: [
        "Chap kolik, sigmoid, rektal",
        "Chap gastrik, taloq, umumiy jigar",
        "O‘ng kolik, ileokolik, o‘rta kolik",
        "Gastroepiploik va pankreatik",
        "Renal va suprarenal",
      ],
      correct: 1,
    },
    {
      q: "Seliak poyaning eng kichik shoxchasi qaysi?",
      a: [
        "Taloq arteriyasi",
        "Chap gastrik arteriya",
        "Umumiy jigar arteriyasi",
        "Gastroduodenal arteriya",
        "O‘ng kolik arteriya",
      ],
      correct: 1,
    },
    {
      q: "Seliak poyaning eng katta tarmog‘i qaysi?",
      a: [
        "Chap gastrik arteriya",
        "O‘ng gastrik arteriya",
        "Taloq arteriyasi",
        "Umumiy jigar arteriyasi",
        "Ileokolik arteriya",
      ],
      correct: 2,
    },
    {
      q: "Qizilo‘ngach va jigar shoxlari qaysi arteriyadan keladi?",
      a: [
        "Taloq arteriyasi",
        "Chap gastrik arteriya",
        "O‘ng gastrik arteriya",
        "Gastroduodenal arteriya",
        "O‘rta kolik arteriya",
      ],
      correct: 1,
    },
    {
      q: "Dorsal pankreatik arteriya qaysi arteriyadan keladi?",
      a: [
        "Umumiy jigar arteriyasi",
        "Taloq arteriyasi",
        "Chap gastrik arteriya",
        "O‘rta kolik arteriya",
        "Ileokolik arteriya",
      ],
      correct: 1,
    },
    {
      q: "Qisqa me’da arteriyalari qaysi arteriyadan keladi?",
      a: [
        "Chap gastrik arteriya",
        "Taloq arteriyasi",
        "O‘ng gastrik arteriya",
        "Gastroduodenal arteriya",
        "Chap kolik arteriya",
      ],
      correct: 1,
    },
    {
      q: "Chap gastroepiploik arteriya qaysi arteriyadan keladi?",
      a: [
        "Taloq arteriyasi",
        "Umumiy jigar arteriyasi",
        "Chap gastrik arteriya",
        "O‘rta kolik arteriya",
        "Pastki mezenterial arteriya",
      ],
      correct: 0,
    },
    {
      q: "Xususiy jigar arteriyasi qaysi arteriyalarga bo‘linadi?",
      a: [
        "O‘ng va chap jigar arteriyalariga",
        "Gastrik va pankreatik arteriyalarga",
        "Kolik arteriyalarga",
        "Sigmoid arteriyalarga",
        "Renal arteriyalarga",
      ],
      correct: 0,
    },
    {
      q: "Sistik arteriya qayerdan kelib chiqadi?",
      a: [
        "Chap jigar arteriyasidan",
        "O‘ng jigar arteriyasidan",
        "Gastroduodenal arteriyadan",
        "Chap gastrik arteriyadan",
        "Taloq arteriyasidan",
      ],
      correct: 1,
    },
    {
      q: "O‘ng gastrik arteriya qaysi arteriya bilan anastomoz qiladi?",
      a: [
        "Chap gastroepiploik arteriya",
        "Chap gastrik arteriya",
        "Taloq arteriyasi",
        "O‘rta kolik arteriya",
        "Sigmoid arteriya",
      ],
      correct: 1,
    },
    {
      q: "O‘ng gastroepiploik arteriya qaysi arteriyadan keladi?",
      a: [
        "Taloq arteriyasi",
        "Gastroduodenal arteriya",
        "Chap gastrik arteriya",
        "Yuqori mezenterial arteriya",
        "Chap kolik arteriya",
      ],
      correct: 1,
    },
    {
      q: "Yuqori pankreatikoduodenal arteriya qaysi arteriyadan keladi?",
      a: [
        "Yuqori mezenterial arteriya",
        "Gastroduodenal arteriya",
        "Taloq arteriyasi",
        "Chap gastrik arteriya",
        "Pastki mezenterial arteriya",
      ],
      correct: 1,
    },
    {
      q: "Pastki pankreatikoduodenal arteriya qaysi arteriyadan keladi?",
      a: [
        "Pastki mezenterial arteriya",
        "Yuqori mezenterial arteriya",
        "Taloq arteriyasi",
        "Umumiy jigar arteriyasi",
        "Chap gastrik arteriya",
      ],
      correct: 1,
    },
    {
      q: "O‘rta kolik arteriya qaysi ichakka kiradi?",
      a: [
        "Sigmoid ichak",
        "Ko‘ndalang chambar ichak",
        "To‘g‘ri ichak",
        "Ileum",
        "Ko‘tariluvchi kolon",
      ],
      correct: 1,
    },
    {
      q: "O‘ng kolik arteriya qaysi ichakka tarqaladi?",
      a: [
        "Tushuvchi kolon",
        "Ko‘tariluvchi kolon",
        "Sigmoid ichak",
        "Ko‘ndalang chambar ichak",
        "Jejunum",
      ],
      correct: 1,
    },
    {
      q: "Appendikulyar arteriya qaysi arteriyadan keladi?",
      a: [
        "O‘rta kolik arteriya",
        "Ileokolik arteriya",
        "Chap kolik arteriya",
        "Sigmoid arteriya",
        "Taloq arteriyasi",
      ],
      correct: 1,
    },
    {
      q: "Ichak arteriyalari soni nechta bo‘ladi?",
      a: ["2–4", "5–7", "12–15", "20–25", "8–10"],
      correct: 2,
    },
    {
      q: "Chap kolik arteriya qaysi arteriyadan keladi?",
      a: [
        "Yuqori mezenterial arteriya",
        "Pastki mezenterial arteriya",
        "Taloq arteriyasi",
        "Umumiy jigar arteriyasi",
        "Aorta",
      ],
      correct: 1,
    },
    {
      q: "Sigmoid arteriyalar nechta bo‘ladi?",
      a: ["1 ta", "2–3 ta", "4–5 ta", "6–7 ta", "8 ta"],
      correct: 1,
    },
    {
      q: "Chap kolik arteriya qaysi ichak bo‘ylab yuradi?",
      a: [
        "Ko‘tariluvchi kolon",
        "Tushuvchi kolon",
        "Ileum",
        "Jejunum",
        "Rektum",
      ],
      correct: 1,
    },
    {
      q: "Yuqori rektal arteriya qaysi arteriyalar bilan anastomoz qiladi?",
      a: [
        "Gastrik arteriyalar bilan",
        "O‘rta va pastki rektal arteriyalar bilan",
        "Gastrik va pankreatik arteriyalarga",
        "Hepatik arteriyalar bilan",
        "Splenik arteriya bilan",
      ],
      correct: 1,
    },
  ],
  mock5: [
    {
      q: "Portal vena uzunligi odatda nechaga teng?",
      a: ["3 sm", "8 sm", "10 sm", "12 sm", "15 sm"],
      correct: 1,
    },
    {
      q: "Portal vena qaysi venalarning qo‘shilishidan hosil bo‘ladi?",
      a: [
        "Pastki kovak vena va jigar venalari",
        "Taloq vena va yuqori tutqich vena",
        "Pastki tutqich vena va jigar venalari",
        "Chap oshqozon va o‘ng oshqozon venalari",
        "Buyrak va taloq venalari",
      ],
      correct: 1,
    },
    {
      q: "Pastki tutqich vena odatda qaysi venaga quyiladi?",
      a: [
        "Yuqori tutqich vena",
        "Pastki kovak vena",
        "Taloq vena",
        "Jigar vena",
        "Chap oshqozon vena",
      ],
      correct: 2,
    },
    {
      q: "Portal vena qaysi venani qabul qiladi?",
      a: [
        "Jigar venalari",
        "Buyrak vena",
        "Chap oshqozon vena",
        "Pastki kovak vena",
        "Son vena",
      ],
      correct: 2,
    },
    {
      q: "Portal vena qanday qonni olib yuradi?",
      a: [
        "Kislorodga boy arterial qon",
        "Aralash qon",
        "Oziq moddalarga boy venoz qon",
        "Faqat limfa",
        "Toza arterial qon",
      ],
      correct: 2,
    },
    {
      q: "Pastki tutqich vena qaysi venalarning qo‘shilishidan hosil bo‘ladi?",
      a: [
        "Yuqori to‘g‘ri ichak venasi va o‘rta, pastki to‘g‘ri ichak venalari.",
        "Son venalari",
        "Yuqori to'g'ri ichak va sigmasimon venalari",
        "Buyrak venalari",
        "Toq venaning qizilo'ngach tarmoqlari",
      ],
      correct: 2,
    },
    {
      q: "Pastki tutqich vena qaysi venani qabul qiladi?",
      a: [
        "Portal vena",
        "Jigar venalari",
        "Chap kolikal vena",
        "Yuqori tutqich vena",
        "Pastki tutqich vena",
      ],
      correct: 2,
    },
    {
      q: "Paraumbilikal venalar qayerda joylashgan?",
      a: [
        "Hepatoduodenal ligamentda",
        "O’roqsimon boylamda",
        "Yumaloq boylamda",
        "Ligamentum teres hepatisda",
        "O‘t pufagi bo‘shlig‘ida",
      ],
      correct: 1,
    },
    {
      q: "Paraumbilikal venalar portal gipertenziyada qanday o‘zgaradi?",
      a: [
        "To‘liq yopiladi",
        "O‘zgarmaydi",
        "Kengayadi",
        "Qisqaradi",
        "Qattiqlashadi",
      ],
      correct: 2,
    },
    {
      q: "Porto-kaval anastomozlar nechta asosiy turga ega?",
      a: ["2 ta", "3 ta", "4 ta", "5 ta", "6 ta"],
      correct: 2,
    },
    {
      q: "Chap oshqozon venasi qaysi tizim bilan anastomoz qiladi?",
      a: [
        "Portal vena",
        "Azygos tizimi venalari",
        "Buyrak venasi",
        "Son venasi",
        "Jigar venasi",
      ],
      correct: 1,
    },
    {
      q: "O‘rta va pastki rektal venalar qaysi vena bilan anastomoz qiladi?",
      a: [
        "Yuqori rektal vena",
        "Jigar venasi",
        "Buyrak venasi",
        "Taloq venasi",
        "Chap oshqozon vena",
      ],
      correct: 0,
    },
    {
      q: "Epigastrial venalar qaysi venalar bilan anastomoz qiladi?",
      a: [
        "Paraumbilikal venalar",
        "Jigar venalari",
        "Buyrak venalari",
        "Taloq venasi",
        "O‘pka venalari",
      ],
      correct: 0,
    },
    {
      q: "Qaysi jigar venalari pastki kovak venaga quyilishdan oldin birlashadi?",
      a: [
        "O‘ng jigar venasi",
        "Chap va o‘rta jigar venalari",
        "Faqat o‘rta jigar venasi",
        "O'ng va o‘rta jigar venalari",
        "Barchasi alohida quyiladi",
      ],
      correct: 1,
    },
  ],
  mock6: [
    {
      q: "Buyrak odatda qaysi umurtqalar darajasida joylashadi?",
      a: ["T10–L1", "T12–L3", "L1–L5", "T8–T12", "L2–S1"],
      correct: 1,
    },
    {
      q: "Nima sababdan o‘ng buyrak chap buyrakka nisbatan pastroq joylashadi?",
      a: [
        "Yurak bosimi tufayli",
        "Jigar o‘ng bo‘lagi bosib turadi",
        "Ichaklar ta’siri tufayli",
        "Diafragma bosimi sabab",
        "Qon tomirlar sabab",
      ],
      correct: 1,
    },
    {
      q: "Chap buyrak qaysi qovurg‘alarga to‘g‘ri keladi?",
      a: ["10–11", "11–12", "12–13", "9–10", "8–9"],
      correct: 1,
    },
    {
      q: "Buyrakni o‘rab turuvchi kapsula qanday tabiatga ega?",
      a: ["Mushakli", "Yog‘li", "Fibroz", "Seroz", "Limfoid"],
      correct: 2,
    },
    {
      q: "Perirenal yog‘ qayerda joylashgan?",
      a: [
        "Fatsiyadan tashqarida",
        "Kapsula va fatsiya orasida",
        "Faqat jigar ichida",
        "Qorin bo‘shlig‘ida",
        "Siydik yo‘lida",
      ],
      correct: 1,
    },
    {
      q: "Pararenal yog‘ qayerda joylashgan?",
      a: [
        "Kapsula ichida",
        "Fatsiya ichida",
        "Fatsiyadan tashqarida",
        "Medulla ichida",
        "Pelvis ichida",
      ],
      correct: 2,
    },
    {
      q: "Buyrak darvozasi (hilum) qayerda joylashgan?",
      a: [
        "Lateral qirrada",
        "Yuqori qutbda",
        "Medial qirrada",
        "Pastki qutbda",
        "Old yuzada",
      ],
      correct: 2,
    },
    {
      q: "Buyrakning funksional birligi nima?",
      a: ["Glomerula", "Nefron", "Piramida", "Papilla", "Kanalcha"],
      correct: 1,
    },
    {
      q: "Har bir buyrakda taxminan nechta nefron mavjud?",
      a: ["100 ming", "500 ming", "1–2 million", "5 million", "10 million"],
      correct: 2,
    },
    {
      q: "Glomerula qaysi qismda joylashadi?",
      a: ["Medulla", "Papilla", "Cortex", "Pelvis", "Ureter"],
      correct: 2,
    },
    {
      q: "Genle halqalari qayerda joylashadi?",
      a: ["Cortex", "Medulla", "Pelvis", "Hilum", "Capsula"],
      correct: 1,
    },
    {
      q: "Buyrak segmentlariga qaysi kirmaydi?",
      a: [
        "Yuqorigi",
        "Oldingi yuqori",
        "Oldingi pastki",
        "Pastki",
        "Medial umumiy",
      ],
      correct: 4,
    },
    {
      q: "Buyrakning asosiy vazifasi nima?",
      a: [
        "Gormon ishlab chiqarish",
        "Qonni filtrlash va siydik hosil qilish",
        "Faqat suv saqlash",
        "Qon yaratish",
        "Limfa ishlab chiqarish",
      ],
      correct: 1,
    },
    {
      q: "Eritropoetin qayerda ishlab chiqariladi?",
      a: ["Jigar", "Buyrak", "Yurak", "O‘pka", "Taloq"],
      correct: 1,
    },
    {
      q: "Renin qaysi hujayralardan ajraladi?",
      a: [
        "Efferent arteriola",
        "Afferent arteriola",
        "Glomerula",
        "Tubulus",
        "Papilla",
      ],
      correct: 1,
    },
    {
      q: "Angiotenzin I qayerdagi ferment orqali Angiotenzin II ga aylanadi?",
      a: ["Jigar", "Buyrak", "O‘pka", "Yurak", "Ichak"],
      correct: 2,
    },
    {
      q: "Angiotenzin II ning asosiy vazifasi nima?",
      a: [
        "Qon bosimini pasaytiradi",
        "Qon bosimini oshiradi",
        "Siydikni kamaytiradi",
        "Qon ishlab chiqaradi",
        "Nafasni tezlashtiradi",
      ],
      correct: 1,
    },
    {
      q: "Nefroptoz nima?",
      a: [
        "Buyrak yallig‘lanishi",
        "Buyrak toshi",
        "Buyrakning pastga siljishi",
        "Buyrak kengayishi",
        "Buyrak infarkti",
      ],
      correct: 2,
    },
    {
      q: "Nefroptoz nimadan kelib chiqadi?",
      a: ["Qon bosimi", "Yog‘ erishi", "Infeksiya", "Travma", "Gormonlar"],
      correct: 1,
    },
    {
      q: "Buyrak toshlari nimadan hosil bo‘ladi?",
      a: [
        "Oqsil yig‘ilishi",
        "Yog‘ to‘planishi",
        "Tuz va kristallar",
        "Suv ortishi",
        "Qon ivishi",
      ],
      correct: 2,
    },
    {
      q: "Buyrak piramidalari qayerda joylashadi?",
      a: ["Cortex", "Medulla", "Pelvis", "Hilum", "Capsula"],
      correct: 1,
    },
    {
      q: "Buyrak papillasida nechta teshik bo‘ladi?",
      a: ["1–5", "5–10", "10–25", "30–40", "50+"],
      correct: 2,
    },
    {
      q: "Kichik kosachalar qayerga quyiladi?",
      a: ["Pelvis", "Ureter", "Katta kosachalar", "Papilla", "Medulla"],
      correct: 2,
    },
    {
      q: "Ureter qayerdan boshlanadi?",
      a: ["Cortex", "Medulla", "Pelvis renalis", "Hilum", "Papilla"],
      correct: 2,
    },
    {
      q: "Ureter qayergacha boradi?",
      a: ["Jigar", "Ichak", "Siydik pufagi", "Yurak", "Taloq"],
      correct: 2,
    },
    {
      q: "Ureter nechta joylarda torayadi?",
      a: ["3 ta joyda", "2 ta joyda", "4 ta joyda", "5 ta joyda", "1 ta joyda"],
      correct: 0,
    },
    {
      q: "Ureterning birinchi torayish joyi qayer?",
      a: [
        "Pelvis chiqishi",
        "Ichak oldi",
        "Yurak yaqinida",
        "Diafragma ostida",
        "Jigar ostida",
      ],
      correct: 0,
    },
    {
      q: "Buyrak usti bezi qayerda joylashgan?",
      a: [
        "Pastki qismda",
        "Superiomedial",
        "Lateral",
        "Old tomonda",
        "Orqa tomonda",
      ],
      correct: 1,
    },
    {
      q: "Buyrak usti bezining tashqi qavati nima?",
      a: ["Medulla", "Cortex", "Capsula", "Hilum", "Papilla"],
      correct: 1,
    },
    {
      q: "Aldosteron qaysi zonada ishlab chiqariladi?",
      a: ["Retikular", "Fascicular", "Glomerular", "Medulla", "Capsula"],
      correct: 2,
    },
    {
      q: "Kortizol qaysi zonada ishlab chiqariladi?",
      a: ["Glomerular", "Fascicular", "Retikular", "Medulla", "Capsula"],
      correct: 1,
    },
    {
      q: "Androgenlar qayerda ishlab chiqariladi?",
      a: ["Glomerular", "Fascicular", "Retikular", "Medulla", "Capsula"],
      correct: 2,
    },
    {
      q: "Medulla qaysi gormonlarni ishlab chiqaradi?",
      a: [
        "Kortizol",
        "Aldosteron",
        "Epinefrin va norepinefrin",
        "Insulin",
        "Glukagon",
      ],
      correct: 2,
    },
    {
      q: "Buyrak usti bezining yuqori arteriyasi qayerdan keladi?",
      a: [
        "Aorta",
        "Buyrak arteriyasi",
        "Pastki frenik arteriya",
        "Ichki yonbosh arteriya",
        "Taloq arteriyasi",
      ],
      correct: 2,
    },
    {
      q: "O‘ng suprarenal vena qayerga quyiladi?",
      a: [
        "Buyrak venasiga",
        "Pastki kovak venaga",
        "Portal venaga",
        "Aortaga",
        "Taloq venasiga",
      ],
      correct: 1,
    },
    {
      q: "Chap suprarenal vena qayerga quyiladi?",
      a: [
        "Pastki kovak vena",
        "Portal vena",
        "Buyrak vena",
        "Aorta",
        "Jigar vena",
      ],
      correct: 2,
    },
  ],
  mock7: [
    {
      q: "Buyrakning tik holatda umurtqa pog‘onasiga nisbatan qaysi darajalar oralig‘ida joylashadi?",
      a: [
        "T10 dan L2 gacha umurtqalar oralig‘ida joylashadi",
        "T11 dan L2 gacha umurtqalar oralig‘ida joylashadi",
        "T12 dan L3 gacha umurtqalar oralig‘ida joylashadi",
        "T12 dan L4 gacha umurtqalar oralig‘ida joylashadi",
        "L1 dan L3 gacha umurtqalar oralig‘ida joylashadi",
      ],
      correct: 2,
    },
    {
      q: "O‘ng buyrak chap buyrakka nisbatan nima sababdan pastroq joylashadi?",
      a: [
        "O‘pka bosimi sababli pastroq joylashadi",
        "Jigar o‘ng bo‘lagi bosimi sababli pastroq joylashadi",
        "Oshqozon bosimi sababli pastroq joylashadi",
        "Ichak bosimi sababli pastroq joylashadi",
        "Diafragma bosimi sababli pastroq joylashadi",
      ],
      correct: 1,
    },
    {
      q: "O‘ng buyrak orqa tomondan qaysi qovurg‘aga to‘g‘ri keladi?",
      a: [
        "10-qovurg‘aga to‘g‘ri keladi",
        "11-qovurg‘aga to‘g‘ri keladi",
        "12-qovurg‘aga to‘g‘ri keladi",
        "9-qovurg‘aga to‘g‘ri keladi",
        "8-qovurg‘aga to‘g‘ri keladi",
      ],
      correct: 2,
    },
    {
      q: "Chap buyrak orqa tomondan qaysi qovurg‘alar darajasiga to‘g‘ri keladi?",
      a: [
        "10 va 11-qovurg‘alarga to‘g‘ri keladi",
        "11 va 12-qovurg‘alarga to‘g‘ri keladi",
        "12 va 13-qovurg‘alarga to‘g‘ri keladi",
        "9 va 10-qovurg‘alarga to‘g‘ri keladi",
        "8 va 9-qovurg‘alarga to‘g‘ri keladi",
      ],
      correct: 1,
    },
    {
      q: "Buyrakni tashqi tomondan qaysi tuzilma mustahkam fibroz kapsula bilan o‘raydi?",
      a: [
        "Yog‘ qavati kapsulani o‘raydi",
        "Fascia renalis kapsulani o‘raydi",
        "Fibroz buyrak kapsulasi o‘raydi",
        "Peritoneum qavati o‘raydi",
        "Muskullar qavati o‘raydi",
      ],
      correct: 2,
    },
    {
      q: "Perirenal yog‘ qavati qaysi tuzilmalar orasida joylashadi?",
      a: [
        "Fascia va teri orasida joylashadi",
        "Kapsula va fascia orasida joylashadi",
        "Fascia va mushak orasida joylashadi",
        "Buyrak va jigar orasida joylashadi",
        "Ureter va vena orasida joylashadi",
      ],
      correct: 1,
    },
    {
      q: "Pararenal yog‘ qavati qayerda joylashadi?",
      a: [
        "Kapsula va fascia orasida joylashadi",
        "Fascia tashqarisida joylashadi",
        "Buyrak ichida joylashadi",
        "Ureter ichida joylashadi",
        "Jomcha ichida joylashadi",
      ],
      correct: 1,
    },
    {
      q: "Buyrak hilumi (darvozasi) qaysi qirg‘oqda joylashgan?",
      a: [
        "Yuqori qirg‘oqda joylashgan",
        "Pastki qirg‘oqda joylashgan",
        "Medial qirg‘oqda joylashgan",
        "Lateral qirg‘oqda joylashgan",
        "Oldingi qirg‘oqda joylashgan",
      ],
      correct: 2,
    },
    {
      q: "Buyrak hilumida qaysi tuzilmalar joylashadi?",
      a: [
        "Ureter, tomirlar va nervlar joylashadi",
        "Arteriya, mushak va teri joylashadi",
        "Jigar, vena va nerv joylashadi",
        "Plevra, arteriya va mushak joylashadi",
        "Oshqozon, vena va nerv joylashadi",
      ],
      correct: 0,
    },
    {
      q: "Nefronlarning asosiy funksional birligi qaysi qavatlarda joylashadi?",
      a: [
        "Faqat po‘stloq qavatda joylashadi",
        "Faqat mag‘iz qavatda joylashadi",
        "Ikkala qavatda joylashadi",
        "Faqat kapsulada joylashadi",
        "Faqat jomchada joylashadi",
      ],
      correct: 2,
    },
    {
      q: "Har bir buyrakda nefronlar soni taxminan qancha?",
      a: [
        "100 mingdan 500 minggacha bo‘ladi",
        "500 mingdan 1 milliongacha bo‘ladi",
        "1 milliondan 2 milliongacha bo‘ladi",
        "2 milliondan 3 milliongacha bo‘ladi",
        "3 milliondan 4 milliongacha bo‘ladi",
      ],
      correct: 2,
    },
    {
      q: "Nefronning qaysi qismi faqat po‘stloq qismda joylashadi?",
      a: [
        "Genli halqasi po‘stloqda joylashadi",
        "Buyrak koptokchasi po‘stloqda joylashadi",
        "Yig‘uvchi naychalar po‘stloqda joylashadi",
        "Jomcha po‘stloqda joylashadi",
        "Ureter po‘stloqda joylashadi",
      ],
      correct: 1,
    },
    {
      q: "Nefron tarkibiga qaysi tuzilmalar kiradi?",
      a: [
        "Faqat arteriya va vena kiradi",
        "Faqat kapsula va jomcha kiradi",
        "Koptokcha, kanalchalar va Genli halqasi kiradi",
        "Faqat ureter va arteriya kiradi",
        "Faqat medulla va kapsula kiradi",
      ],
      correct: 2,
    },
    {
      q: "Buyrak arterial segmentlariga qaysi biri kiradi?",
      a: [
        "Yuqori, pastki, oldingi va lateral segmentlar kiradi",
        "Yuqori, oldingi yuqori, oldingi pastki, pastki va orqa segmentlar kiradi",
        "Faqat yuqori va pastki segmentlar kiradi",
        "Oldingi va orqa segmentlar kiradi",
        "Faqat medial segmentlar kiradi",
      ],
      correct: 1,
    },
    {
      q: "Buyrakning asosiy funksiyalaridan biri qaysi?",
      a: [
        "Faqat ovqat hazm qilishni bajaradi",
        "Qonni filtrlaydi va siydik hosil qiladi",
        "Faqat gormon ishlab chiqaradi",
        "Faqat gaz almashinuvini bajaradi",
        "Faqat yog‘ to‘playdi",
      ],
      correct: 1,
    },
    {
      q: "Eritropoetin qaysi a’zo tomonidan ishlab chiqariladi?",
      a: [
        "Jigar tomonidan ishlab chiqariladi",
        "O‘pka tomonidan ishlab chiqariladi",
        "Buyrak tomonidan ishlab chiqariladi",
        "Yurak tomonidan ishlab chiqariladi",
        "Oshqozon tomonidan ishlab chiqariladi",
      ],
      correct: 2,
    },
    {
      q: "Renin qaysi hujayralar tomonidan ishlab chiqariladi?",
      a: [
        "Distal kanal hujayralari tomonidan ishlab chiqariladi",
        "Afferent arteriola hujayralari tomonidan ishlab chiqariladi",
        "Efferent arteriola hujayralari tomonidan ishlab chiqariladi",
        "Jomcha hujayralari tomonidan ishlab chiqariladi",
        "Kapsula hujayralari tomonidan ishlab chiqariladi",
      ],
      correct: 1,
    },
    {
      q: "Angiotenzin I qayerda angiotenzin II ga aylanadi?",
      a: [
        "Jigar hujayralarida aylanadi",
        "O‘pka endotelida aylanadi",
        "Buyrak kapsulasida aylanadi",
        "Yurak mushaklarida aylanadi",
        "Ichakda aylanadi",
      ],
      correct: 1,
    },
    {
      q: "Angiotenzin II ning asosiy ta’siri qaysi?",
      a: [
        "Qon bosimini pasaytiradi",
        "Qon bosimini oshiradi",
        "Qon ivishini to‘xtatadi",
        "Oqsil sintezini kamaytiradi",
        "Glyukoza parchalaydi",
      ],
      correct: 1,
    },
    {
      q: "Nefroptoz nima?",
      a: [
        "Buyrak yallig‘lanishi hisoblanadi",
        "Buyrakning yuqoriga ko‘tarilishi hisoblanadi",
        "Buyrakning pastga siljishi hisoblanadi",
        "Buyrak tosh hosil qilishi hisoblanadi",
        "Buyrakning kengayishi hisoblanadi",
      ],
      correct: 2,
    },
    {
      q: "Buyrak toshlari asosan qaysi moddalardan hosil bo‘ladi?",
      a: [
        "Oqsil va glyukoza birikmalaridan hosil bo‘ladi",
        "Kalsiy oksalat va fosfat birikmalaridan hosil bo‘ladi",
        "Yog‘ va xolesterin birikmalaridan hosil bo‘ladi",
        "Vitamin va fermentlardan hosil bo‘ladi",
        "Temir va mis birikmalaridan hosil bo‘ladi",
      ],
      correct: 1,
    },
    {
      q: "Buyrak piramidalari (medulla) soni qaysi diapazonda bo‘ladi?",
      a: [
        "4 dan 6 gacha bo‘ladi",
        "6 dan 8 gacha bo‘ladi",
        "8 dan 12 gacha bo‘ladi",
        "12 dan 15 gacha bo‘ladi",
        "15 dan 20 gacha bo‘ladi",
      ],
      correct: 2,
    },
    {
      q: "Buyrak papillasida nechta teshik bo‘lishi mumkin?",
      a: [
        "5–10 teshik bo‘ladi",
        "10–25 teshik bo‘ladi",
        "25–40 teshik bo‘ladi",
        "40–60 teshik bo‘ladi",
        "60–80 teshik bo‘ladi",
      ],
      correct: 1,
    },
    {
      q: "Kichik kosachalar siydikni qayerga quyadi?",
      a: [
        "Ureterga quyadi",
        "Buyrak jomiga quyadi",
        "Katta kosachaga quyadi",
        "Kapsulaga quyadi",
        "Arteriyaga quyadi",
      ],
      correct: 2,
    },
    {
      q: "Buyrak jomi (pelvis renalis) qaysi tuzilmadan hosil bo‘ladi?",
      a: [
        "Katta kosachalardan hosil bo‘ladi",
        "Kichik kosachalardan hosil bo‘ladi",
        "Ureterdan hosil bo‘ladi",
        "Kapsuladan hosil bo‘ladi",
        "Piramidadan hosil bo‘ladi",
      ],
      correct: 0,
    },
    {
      q: "Ureter qaysi a’zoga qadar cho‘ziladi?",
      a: [
        "Jigar gacha cho‘ziladi",
        "Buyrak gacha cho‘ziladi",
        "Siydik pufagigacha cho‘ziladi",
        "Oshqozongacha cho‘ziladi",
        "Yurakgacha cho‘ziladi",
      ],
      correct: 2,
    },
    {
      q: "Ureterning siydik toshlari bilan eng tor joyi qaysi?",
      a: [
        "O‘rta qismida tor joyi bo‘ladi",
        "Ureteropelvik birikmada tor joyi bo‘ladi",
        "Diafragma darajasida tor joyi bo‘ladi",
        "Jigar darajasida tor joyi bo‘ladi",
        "O‘pka darajasida tor joyi bo‘ladi",
      ],
      correct: 1,
    },
    {
      q: "Ureterning qaysi qismi siydik pufagiga kirishda torayadi?",
      a: [
        "Ureteropelvik birikma qismi torayadi",
        "Ureterovezikular birikma qismi torayadi",
        "O‘rta qism torayadi",
        "Yuqori qism torayadi",
        "Pastki qism toraymaydi",
      ],
      correct: 1,
    },
    {
      q: "Ureterning simpatik innervatsiyasi qaysi tizim orqali amalga oshadi?",
      a: [
        "Somatik nerv tizimi orqali amalga oshadi",
        "Bel splanxnik nervlari orqali amalga oshadi",
        "Vagus nervi orqali amalga oshadi",
        "Frenik nerv orqali amalga oshadi",
        "Spinal nerv orqali amalga oshadi",
      ],
      correct: 1,
    },
    {
      q: "Buyrak usti bezi qaysi joyda joylashadi?",
      a: [
        "Buyrakning inferiomedial tomonida joylashadi",
        "Buyrakning superiomedial tomonida joylashadi",
        "Buyrakning lateral tomonida joylashadi",
        "Buyrakning orqa tomonida joylashadi",
        "Buyrakning pastki qismida joylashadi",
      ],
      correct: 1,
    },
    {
      q: "O‘ng buyrak usti bezining shakli qaysi?",
      a: [
        "Yarim oy shaklida bo‘ladi",
        "Uchburchak shaklida bo‘ladi",
        "Piramida shaklida bo‘ladi",
        "Dumaloq shaklida bo‘ladi",
        "Yassi shaklida bo‘ladi",
      ],
      correct: 2,
    },
    {
      q: "Chap buyrak usti bezining shakli qaysi?",
      a: [
        "Piramida shaklida bo‘ladi",
        "Yarim oy shaklida bo‘ladi",
        "Dumaloq shaklida bo‘ladi",
        "Yassi shaklida bo‘ladi",
        "Kub shaklida bo‘ladi",
      ],
      correct: 1,
    },
    {
      q: "Aldosteron qaysi zonada ishlab chiqariladi?",
      a: [
        "Retikulyar zonada ishlab chiqariladi",
        "Fascikulyar zonada ishlab chiqariladi",
        "Glomerulyar zonada ishlab chiqariladi",
        "Medullada ishlab chiqariladi",
        "Kapsulada ishlab chiqariladi",
      ],
      correct: 2,
    },
    {
      q: "Kortizol qaysi zonada ishlab chiqariladi?",
      a: [
        "Glomerulyar zonada ishlab chiqariladi",
        "Fascikulyar zonada ishlab chiqariladi",
        "Retikulyar zonada ishlab chiqariladi",
        "Medullada ishlab chiqariladi",
        "Kapsulada ishlab chiqariladi",
      ],
      correct: 1,
    },
    {
      q: "Androgenlar qaysi zonada ishlab chiqariladi?",
      a: [
        "Glomerulyar zonada ishlab chiqariladi",
        "Fascikulyar zonada ishlab chiqariladi",
        "Retikulyar zonada ishlab chiqariladi",
        "Medullada ishlab chiqariladi",
        "Kapsulada ishlab chiqariladi",
      ],
      correct: 2,
    },
    {
      q: "Adrenal medulla embrional qaysi hujayralardan hosil bo‘ladi?",
      a: [
        "Endoderm hujayralaridan hosil bo‘ladi",
        "Mezoderm hujayralaridan hosil bo‘ladi",
        "Neyral krest hujayralaridan hosil bo‘ladi",
        "Ektoderm hujayralaridan hosil bo‘ladi",
        "Epiteliy hujayralaridan hosil bo‘ladi",
      ],
      correct: 2,
    },
    {
      q: "Adrenal bez medullasi qaysi gormonlarni ishlab chiqaradi?",
      a: [
        "Faqat kortizol ishlab chiqaradi",
        "Epinefrin va norepinefrin ishlab chiqaradi",
        "Faqat aldosteron ishlab chiqaradi",
        "Faqat androgen ishlab chiqaradi",
        "Faqat insulin ishlab chiqaradi",
      ],
      correct: 1,
    },
    {
      q: "O‘ng buyrak usti bezining venoz drenaji qaysi tomirga quyiladi?",
      a: [
        "Chap buyrak venasiga quyiladi",
        "Pastki kovak venaga quyiladi",
        "Yuqori kovak venaga quyiladi",
        "Jigar venasiga quyiladi",
        "Aortaga quyiladi",
      ],
      correct: 1,
    },
  ],
  mock8: [
    {
      q: "Aorta diafragmadagi teshikdan qaysi darajada o‘tadi?",
      a: [
        "Aorta diafragmadagi teshikdan T10 darajasida o‘tadi",
        "Aorta diafragmadagi teshikdan T11 darajasida o‘tadi",
        "Aorta diafragmadagi teshikdan T12 darajasida o‘tadi",
        "Aorta diafragmadagi teshikdan L1 darajasida o‘tadi",
        "Aorta diafragmadagi teshikdan L2 darajasida o‘tadi",
      ],
      correct: 2,
    },
    {
      q: "Aorta qaysi darajada umumiy yonbosh arteriyalarga bo‘linadi?",
      a: [
        "Aorta L3 darajada umumiy yonbosh arteriyalarga bo‘linadi",
        "Aorta L4 darajada umumiy yonbosh arteriyalarga bo‘linadi",
        "Aorta L5 darajada umumiy yonbosh arteriyalarga bo‘linadi",
        "Aorta L2 darajada umumiy yonbosh arteriyalarga bo‘linadi",
        "Aorta S1 darajada umumiy yonbosh arteriyalarga bo‘linadi",
      ],
      correct: 1,
    },
    {
      q: "Pastki frenik arteriyaning asosiy vazifasi nima?",
      a: [
        "Diafragmani qon bilan ta’minlaydi",
        "Buyrakni qon bilan ta’minlaydi",
        "Jigarni qon bilan ta’minlaydi",
        "Ichakni qon bilan ta’minlaydi",
        "O‘pkani qon bilan ta’minlaydi",
      ],
      correct: 0,
    },
    {
      q: "Buyrak arteriyalari qaysi tomirlarni hosil qiladi?",
      a: [
        "Faqat gonadal arteriyalarni hosil qiladi",
        "Pastki buyrak usti va ureterik arteriyalarni hosil qiladi",
        "Faqat diafragma arteriyalarini hosil qiladi",
        "Faqat jigar arteriyalarini hosil qiladi",
        "Faqat ichak arteriyalarini hosil qiladi",
      ],
      correct: 1,
    },
    {
      q: "O‘ng buyrak arteriyasi qaysi tuzilma orqasidan o‘tadi?",
      a: [
        "Aorta orqasidan o‘tadi",
        "Pastki kovak vena orqasidan o‘tadi",
        "Chap buyrak venasi orqasidan o‘tadi",
        "Portal vena orqasidan o‘tadi",
        "Jigar venasi orqasidan o‘tadi",
      ],
      correct: 1,
    },
    {
      q: "Chap buyrak arteriyasi qaysi tuzilma orqasidan o‘tadi?",
      a: [
        "Chap buyrak venasi orqasidan o‘tadi",
        "Aorta orqasidan o‘tadi",
        "Pastki kovak vena orqasidan o‘tadi",
        "Jigar venasi orqasidan o‘tadi",
        "Portal vena orqasidan o‘tadi",
      ],
      correct: 0,
    },
    {
      q: "Tuxumdon arteriyasi qaysi boylam orqali kiradi?",
      a: [
        "Ligamentum hepatoduodenale orqali kiradi",
        "Ligamentum inguinale orqali kiradi",
        "Suspensor boylam orqali kiradi",
        "Ligamentum falciforme orqali kiradi",
        "Ligamentum teres orqali kiradi",
      ],
      correct: 2,
    },
    {
      q: "Moyak arteriyasi qaysi tuzilma bilan birga tushadi?",
      a: [
        "Ureter bilan birga tushadi",
        "Ductus deferens bilan birga tushadi",
        "Aorta bilan birga tushadi",
        "Pastki kovak vena bilan birga tushadi",
        "Iliak arteriya bilan birga tushadi",
      ],
      correct: 1,
    },
    {
      q: "Lumbar arteriyalar soni nechta juft bo‘ladi?",
      a: [
        "2–3 juft bo‘ladi",
        "3–4 juft bo‘ladi",
        "4–5 juft bo‘ladi",
        "5–6 juft bo‘ladi",
        "6–7 juft bo‘ladi",
      ],
      correct: 2,
    },
    {
      q: "O‘rta sakral arteriya qayerdan boshlanadi?",
      a: [
        "Aorta bifurkatsiyasidan pastda boshlanadi",
        "Aorta bifurkatsiyasidan biroz yuqorida boshlanadi",
        "L3 darajada boshlanadi",
        "L5 darajada boshlanadi",
        "T10 darajada boshlanadi",
      ],
      correct: 1,
    },
    {
      q: "O‘rta sakral arteriya qayerda tugaydi?",
      a: [
        "Buyrakda tugaydi",
        "Dum suyagida tugaydi",
        "Jigar ichida tugaydi",
        "Aorta ichida tugaydi",
        "Diafragmada tugaydi",
      ],
      correct: 1,
    },
    {
      q: "Pastki kovak vena qayerda hosil bo‘ladi?",
      a: [
        "Chap umumiy yonbosh venalar birlashishidan hosil bo‘ladi",
        "O‘ng va chap buyrak venalari birlashishidan hosil bo‘ladi",
        "Ikkita umumiy yonbosh venalar birlashishidan hosil bo‘ladi",
        "Jigar venalari birlashishidan hosil bo‘ladi",
        "Portal vena birlashishidan hosil bo‘ladi",
      ],
      correct: 2,
    },
    {
      q: "IVC qaysi darajada diafragmadan o‘tadi?",
      a: [
        "T10 darajada o‘tadi",
        "T12 darajada o‘tadi",
        "T8 darajada o‘tadi",
        "L1 darajada o‘tadi",
        "L4 darajada o‘tadi",
      ],
      correct: 2,
    },
    {
      q: "IVC qaysi bo‘lmaga kiradi?",
      a: [
        "Chap atriumga kiradi",
        "O‘ng atriumga kiradi",
        "Chap ventrikulga kiradi",
        "Aortaga kiradi",
        "O‘pka arteriyasiga kiradi",
      ],
      correct: 1,
    },
    {
      q: "Cisterna chyli qayerda joylashadi?",
      a: [
        "Aorta oldida joylashadi",
        "Aorta o‘ng va orqasida joylashadi",
        "Jigar ichida joylashadi",
        "Buyrak ichida joylashadi",
        "O‘pka ichida joylashadi",
      ],
      correct: 1,
    },
    {
      q: "Cisterna chyli nimadan hosil bo‘ladi?",
      a: [
        "Jigar venalaridan hosil bo‘ladi",
        "Ichak va bel limfa yo‘llaridan hosil bo‘ladi",
        "Buyrak arteriyalaridan hosil bo‘ladi",
        "Aorta tarmoqlaridan hosil bo‘ladi",
        "Portal venadan hosil bo‘ladi",
      ],
      correct: 1,
    },
    {
      q: "Lumbar chigal qaysi nervlardan hosil bo‘ladi?",
      a: [
        "T12–L1 nervlardan hosil bo‘ladi",
        "L1–L4 nervlardan hosil bo‘ladi",
        "L4–S1 nervlardan hosil bo‘ladi",
        "S1–S3 nervlardan hosil bo‘ladi",
        "T10–T12 nervlardan hosil bo‘ladi",
      ],
      correct: 1,
    },
    {
      q: "Subkostal nerv qaysi darajada joylashadi?",
      a: [
        "T10 darajada joylashadi",
        "T11 darajada joylashadi",
        "T12 darajada joylashadi",
        "L1 darajada joylashadi",
        "L2 darajada joylashadi",
      ],
      correct: 2,
    },
    {
      q: "Iliohipogastric nerv qaysi ildizdan chiqadi?",
      a: [
        "T12 ildizdan chiqadi",
        "L1 ildizdan chiqadi",
        "L2 ildizdan chiqadi",
        "L3 ildizdan chiqadi",
        "L4 ildizdan chiqadi",
      ],
      correct: 1,
    },
    {
      q: "Ilioinguinal nerv qaysi kanal orqali chiqadi?",
      a: [
        "Femoral kanal orqali chiqadi",
        "Chov kanali orqali chiqadi",
        "Obturator kanal orqali chiqadi",
        "Vertebral kanal orqali chiqadi",
        "Aorta kanali orqali chiqadi",
      ],
      correct: 1,
    },
    {
      q: "Genitofemoral nerv qayerda paydo bo‘ladi?",
      a: [
        "Psoas old yuzasida paydo bo‘ladi",
        "Psoas orqa yuzasida paydo bo‘ladi",
        "Quadratus lumborumda paydo bo‘ladi",
        "Iliacus mushagida paydo bo‘ladi",
        "Aorta ichida paydo bo‘ladi",
      ],
      correct: 0,
    },
    {
      q: "Lateral femoral cutaneous nerv qaysi segmentlardan chiqadi?",
      a: [
        "L1–L2 segmentlardan chiqadi",
        "L2–L3 segmentlardan chiqadi",
        "L3–L4 segmentlardan chiqadi",
        "L4–L5 segmentlardan chiqadi",
        "T12–L1 segmentlardan chiqadi",
      ],
      correct: 1,
    },
    {
      q: "Femoral nerv qayerga kiradi?",
      a: [
        "Obturator kanalga kiradi",
        "Femoral uchburchakka kiradi",
        "Aorta ichiga kiradi",
        "Chov kanaliga kiradi",
        "Sakral kanalga kiradi",
      ],
      correct: 1,
    },
    {
      q: "Obturator nerv qayerdan o‘tadi?",
      a: [
        "Femoral kanal orqali o‘tadi",
        "Obturator teshigi orqali o‘tadi",
        "Chov kanali orqali o‘tadi",
        "Aorta teshigi orqali o‘tadi",
        "Diafragma teshigi orqali o‘tadi",
      ],
      correct: 1,
    },
    {
      q: "Qo‘shimcha obturator nerv necha foiz odamlarda uchraydi?",
      a: [
        "5% odamlarda uchraydi",
        "7% odamlarda uchraydi",
        "9% odamlarda uchraydi",
        "12% odamlarda uchraydi",
        "15% odamlarda uchraydi",
      ],
      correct: 2,
    },
    {
      q: "Obturator nerv qaysi mushak guruhini innervatsiya qiladi?",
      a: [
        "Ekstensor mushak guruhini innervatsiya qiladi",
        "Adduktor mushak guruhini innervatsiya qiladi",
        "Fleksor mushak guruhini innervatsiya qiladi",
        "Abduktor mushak guruhini innervatsiya qiladi",
        "Rotator mushak guruhini innervatsiya qiladi",
      ],
      correct: 1,
    },
    {
      q: "Femoral nerv qaysi mushakni innervatsiya qiladi?",
      a: [
        "Adductor longus mushagini innervatsiya qiladi",
        "Quadriceps femoris mushagini innervatsiya qiladi",
        "Gluteus maximus mushagini innervatsiya qiladi",
        "Obturator internus mushagini innervatsiya qiladi",
        "Piriformis mushagini innervatsiya qiladi",
      ],
      correct: 1,
    },
    {
      q: "Lumbosakral tarmoq qaysi nervlardan hosil bo‘ladi?",
      a: [
        "L1–L3 nervlardan hosil bo‘ladi",
        "L2–L4 nervlardan hosil bo‘ladi",
        "L4 pastki qismi va L5 to‘liq nervidan hosil bo‘ladi",
        "L3–L5 nervlardan hosil bo‘ladi",
        "T12–L2 nervlardan hosil bo‘ladi",
      ],
      correct: 2,
    },
  ],
};
